### ISSUE TITLE
'grin wallet info' crashes

### ISSUE THREAD

**Issue by chri2** [mimblewimble/grin#1040]
The wallet is running on a node that is not mining. It is started on its own and not by 'grin server run'. Miners do connect to the grin stratum server and send solutions. The call of 'grin wallet info' in the wallets directory looks like below - sometimes it works, other times it produces errors like 'EofWhileParsingString' and 'EofWhileParsingValue'.

```
grin@grin:~/wallet$ date; time grin wallet info; date
So 6. Mai 21:38:44 CEST 2018
May 06 21:38:44.405 INFO This is Grin version 0.2.0 (git testnet2-92-gf8732d7), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27).
May 06 21:38:44.419 DEBG Built with profile "release", features "" on Sat, 28 Apr 2018 12:26:29 GMT.
May 06 21:38:44.423 DEBG Using wallet seed file at: ./wallet.seed
May 06 21:38:44.597 DEBG Refreshing wallet outputs
May 06 21:39:48.916 INFO Acquiring wallet lock ...
May 06 21:40:39.927 INFO ... released wallet lock
May 06 21:41:54.278 ERRO 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { code: EofWhileParsingValue, line: 27238, column: 2 }

Wallet data error: Error reading wallet file  }': /checkout/src/libcore/result.rs:916stack backtrace:
   0:     0x56006f88677c - backtrace::backtrace::trace::h9a9788e0a4feb260
   1:     0x56006f885de2 - backtrace::capture::Backtrace::new::h259826679d88d08f
   2:     0x56006f80a713 - grin_util::logger::send_panic_to_log::{{closure}}::h477e9823471f7d75
   3:     0x56006f8a23a5 - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x56006f8a21be - std::panicking::begin_panic::h215af23ff6354aaf
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x56006f8a212a - std::panicking::begin_panic_fmt::h752224a2c436be23
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x56006f8a20c2 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x56006f9032b0 - core::panicking::panic_fmt::h68e7715928be641f
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x56006f35a258 - core::result::unwrap_failed::h72372c1b5f2475c4
   9:     0x56006f400d47 - grin_wallet::info::retrieve_info::he76fce20e94c930f
  10:     0x56006f3ff90c - grin_wallet::info::show_info::h1700ffd0aac1604a
  11:     0x56006f1d29f9 - grin::main::h572050bdc9c1e9ec
  12:     0x56006f1c0772 - std::rt::lang_start::{{closure}}::ha9ad688139d3a73f
  13:     0x56006f8a2027 - std::rt::lang_start_internal::{{closure}}::h6ddc513d95d559ac
                        at /checkout/src/libstd/rt.rs:59
                         - std::panicking::try::do_call::h7d33aea9be52481f
                        at /checkout/src/libstd/panicking.rs:480
  14:     0x56006f8c520e - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  15:     0x56006f8a90a9 - std::panicking::try::h33108b08b6395be5
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind::hb0149e8b5a4339ed
                        at /checkout/src/libstd/panic.rs:365
                         - std::rt::lang_start_internal::h16c0c37ef62d8e5a
                        at /checkout/src/libstd/rt.rs:58
  16:     0x56006f1d4f13 - main
  17:     0x7f2efa0e4b44 - __libc_start_main
  18:     0x56006f1913c9 - <unknown>
  19:                0x0 - <unknown>


Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { code: EofWhileParsingValue, line: 27238, column: 2 }

Wallet data error: Error reading wallet file  }"
See grin.log for further details.

real	3m10.269s
user	1m15.256s
sys	1m15.736s
So 6. Mai 21:41:54 CEST 2018
grin@grin:~/wallet$ date; time grin wallet info; date
So 6. Mai 22:27:04 CEST 2018
May 06 22:27:04.497 INFO This is Grin version 0.2.0 (git testnet2-92-gf8732d7), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27).
May 06 22:27:04.542 DEBG Built with profile "release", features "" on Sat, 28 Apr 2018 12:26:29 GMT.
May 06 22:27:04.546 DEBG Using wallet seed file at: ./wallet.seed
May 06 22:27:04.755 DEBG Refreshing wallet outputs
May 06 22:28:34.444 DEBG Splitting query: 1000 ids
May 06 22:28:34.642 DEBG Splitting query: 1000 ids
May 06 22:28:34.881 DEBG Splitting query: 1000 ids
May 06 22:28:35.046 DEBG Splitting query: 1000 ids
May 06 22:28:36.422 DEBG Splitting query: 1000 ids
May 06 22:28:36.558 DEBG Splitting query: 1000 ids
May 06 22:28:36.652 DEBG Splitting query: 1000 ids
May 06 22:28:36.787 DEBG Splitting query: 1000 ids
May 06 22:28:36.875 DEBG Splitting query: 1000 ids
May 06 22:28:36.946 DEBG Splitting query: 1000 ids
May 06 22:28:37.489 DEBG Splitting query: 1000 ids
May 06 22:28:37.641 DEBG Splitting query: 485 ids
May 06 22:28:37.708 INFO Acquiring wallet lock ...
May 06 22:30:28.155 INFO ... released wallet lock
May 06 22:31:33.278 DEBG Refreshing missing block hashes (and heights) for 12 outputs
May 06 22:31:33.283 DEBG Splitting query: 12 ids
May 06 22:31:33.285 DEBG "http://127.0.0.1:13413/v1/chain/outputs/byheight?start_height=0&end_height=55707&id=0988b2f58897f5016275b630acb5888637a868beba668e0561f58716c31130a43d&id=09c6387516a14389b3efce92b015912ad4e1b92754c98da8424d835650fb453ab8&id=09ae2f6c288732a0dfae55c8d2cdf27871133a11f6987a2cf990f1ab25c3187273&id=094af63d785a69511c7140fb9277590c48034e7dfa95c7effcab9598839d848287&id=08364900b10d95e416c08bd5420da2fd815b511066e2961e2e74bb3606020942da&id=09cea2978b0fa35e6e3c549d8113b4acd887cbbfd52062e4c541098b1e375d8f64&id=09406731f652c59de71f0ba01f31ebe8554730f6f98a20d1e9dcec0fb4973aa8c8&id=09a6caa8898e53d947304b30416923f2561a379dc665b22fec6491d2998c29fda7&id=09c8b9402a262eef46a7a1825175fd867f5800684b3255fb9987fbf70abd6594fe&id=08ca2cb07ae7731ecf446bbb6d99107e9578480fa5996e6a2f99a76d20f9f24d1c&id=095d4482ab9137d7e12f6200ae5ef6b55228e5b8c0d576f4a7527cdd00d6e6991e&id=085a2efa9f0116ad8388cbd9d09a73ece5d4124c56f8240439077d7e6867b19745"
May 06 22:31:49.809 INFO Acquiring wallet lock ...
May 06 22:33:00.030 INFO ... released wallet lock

____ Wallet Summary Info at 55710 (from server node) ____

 Total                            | 1741.989000000 
 Awaiting Confirmation            | 0.000000000 
 Confirmed but Still Locked       | 120.000000000 
 Currently Spendable              | 1621.989000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 


real	7m11.951s
user	2m19.676s
sys	2m8.732s
So 6. Mai 22:34:16 CEST 2018
grin@grin:~/wallet$ date; time grin wallet info; date
So 6. Mai 22:43:55 CEST 2018
May 06 22:43:55.510 INFO This is Grin version 0.2.0 (git testnet2-92-gf8732d7), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27).
May 06 22:43:55.537 DEBG Built with profile "release", features "" on Sat, 28 Apr 2018 12:26:29 GMT.
May 06 22:43:55.547 DEBG Using wallet seed file at: ./wallet.seed
May 06 22:43:55.802 DEBG Refreshing wallet outputs
May 06 22:43:58.822 INFO Acquiring wallet lock ...
May 06 22:44:55.005 INFO ... released wallet lock
May 06 22:46:20.281 ERRO 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { code: EofWhileParsingString, line: 10791, column: 25 }

Wallet data error: Error reading wallet file  }': /checkout/src/libcore/result.rs:916stack backtrace:
   0:     0x55df6fd6077c - backtrace::backtrace::trace::h9a9788e0a4feb260
   1:     0x55df6fd5fde2 - backtrace::capture::Backtrace::new::h259826679d88d08f
   2:     0x55df6fce4713 - grin_util::logger::send_panic_to_log::{{closure}}::h477e9823471f7d75
   3:     0x55df6fd7c3a5 - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55df6fd7c1be - std::panicking::begin_panic::h215af23ff6354aaf
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55df6fd7c12a - std::panicking::begin_panic_fmt::h752224a2c436be23
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55df6fd7c0c2 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55df6fddd2b0 - core::panicking::panic_fmt::h68e7715928be641f
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55df6f834258 - core::result::unwrap_failed::h72372c1b5f2475c4
   9:     0x55df6f8dad47 - grin_wallet::info::retrieve_info::he76fce20e94c930f
  10:     0x55df6f8d990c - grin_wallet::info::show_info::h1700ffd0aac1604a
  11:     0x55df6f6ac9f9 - grin::main::h572050bdc9c1e9ec
  12:     0x55df6f69a772 - std::rt::lang_start::{{closure}}::ha9ad688139d3a73f
  13:     0x55df6fd7c027 - std::rt::lang_start_internal::{{closure}}::h6ddc513d95d559ac
                        at /checkout/src/libstd/rt.rs:59
                         - std::panicking::try::do_call::h7d33aea9be52481f
                        at /checkout/src/libstd/panicking.rs:480
  14:     0x55df6fd9f20e - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  15:     0x55df6fd830a9 - std::panicking::try::h33108b08b6395be5
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind::hb0149e8b5a4339ed
                        at /checkout/src/libstd/panic.rs:365
                         - std::rt::lang_start_internal::h16c0c37ef62d8e5a
                        at /checkout/src/libstd/rt.rs:58
  16:     0x55df6f6aef13 - main
  17:     0x7ff5bdcb9b44 - __libc_start_main
  18:     0x55df6f66b3c9 - <unknown>
  19:                0x0 - <unknown>


Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { code: EofWhileParsingString, line: 10791, column: 25 }

Wallet data error: Error reading wallet file  }"
See grin.log for further details.

real	2m25.002s
user	0m55.824s
sys	0m54.932s
So 6. Mai 22:46:20 CEST 2018
grin@grin:~/wallet$ date; time grin wallet info; date
So 6. Mai 22:50:14 CEST 2018
May 06 22:50:14.897 INFO This is Grin version 0.2.0 (git testnet2-92-gf8732d7), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27).
May 06 22:50:14.901 DEBG Built with profile "release", features "" on Sat, 28 Apr 2018 12:26:29 GMT.
May 06 22:50:14.902 DEBG Using wallet seed file at: ./wallet.seed
May 06 22:50:15.291 DEBG Refreshing wallet outputs
May 06 22:51:28.744 INFO Acquiring wallet lock ...
May 06 22:52:24.442 INFO ... released wallet lock
May 06 22:53:49.765 ERRO 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { code: EofWhileParsingObject, line: 5546, column: 3 }

Wallet data error: Error reading wallet file  }': /checkout/src/libcore/result.rs:916stack backtrace:
   0:     0x55865520d77c - backtrace::backtrace::trace::h9a9788e0a4feb260
   1:     0x55865520cde2 - backtrace::capture::Backtrace::new::h259826679d88d08f
   2:     0x558655191713 - grin_util::logger::send_panic_to_log::{{closure}}::h477e9823471f7d75
   3:     0x5586552293a5 - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x5586552291be - std::panicking::begin_panic::h215af23ff6354aaf
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55865522912a - std::panicking::begin_panic_fmt::h752224a2c436be23
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x5586552290c2 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55865528a2b0 - core::panicking::panic_fmt::h68e7715928be641f
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x558654ce1258 - core::result::unwrap_failed::h72372c1b5f2475c4
   9:     0x558654d87d47 - grin_wallet::info::retrieve_info::he76fce20e94c930f
  10:     0x558654d8690c - grin_wallet::info::show_info::h1700ffd0aac1604a
  11:     0x558654b599f9 - grin::main::h572050bdc9c1e9ec
  12:     0x558654b47772 - std::rt::lang_start::{{closure}}::ha9ad688139d3a73f
  13:     0x558655229027 - std::rt::lang_start_internal::{{closure}}::h6ddc513d95d559ac
                        at /checkout/src/libstd/rt.rs:59
                         - std::panicking::try::do_call::h7d33aea9be52481f
                        at /checkout/src/libstd/panicking.rs:480
  14:     0x55865524c20e - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  15:     0x5586552300a9 - std::panicking::try::h33108b08b6395be5
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind::hb0149e8b5a4339ed
                        at /checkout/src/libstd/panic.rs:365
                         - std::rt::lang_start_internal::h16c0c37ef62d8e5a
                        at /checkout/src/libstd/rt.rs:58
  16:     0x558654b5bf13 - main
  17:     0x7f4677471b44 - __libc_start_main
  18:     0x558654b183c9 - <unknown>
  19:                0x0 - <unknown>


Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { code: EofWhileParsingObject, line: 5546, column: 3 }

Wallet data error: Error reading wallet file  }"
See grin.log for further details.

real	3m35.155s
user	1m16.104s
sys	1m17.024s
So 6. Mai 22:53:49 CEST 2018
```

**Comment by yeastplume** [comment]
wallet has undergone significant refactoring, so this is likely no longer relevant to the current state of the code. Please open again if you see this happening (particularly on the testnet3 branch)
