### ISSUE TITLE
grin wallet restore fails

### ISSUE THREAD

**Issue by chri2** [mimblewimble/grin#1046]
Happened on at least three consecutive tries:

```
May 03 18:29:55.394 INFO Retrieved 1000 outputs, up to index 41888. (Highest index: 80181)
May 03 18:29:55.394 INFO Acquiring wallet lock ...
May 03 18:29:55.396 INFO Scanning 1000 outputs
May 03 18:30:17.089 DEBG Found 0 wallet_outputs
May 03 18:30:17.090 INFO ... released wallet lock
May 03 18:30:17.218 ERRO outputs_batch: Restore failed... unable to contact API http://localhost:13413. Error: Internal error: Server error:
```

grin.log
```
May 07 15:40:37.225 ERRO 
thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: TxHashSetErr("Output and rangeproof sets don\'t match")': /checko
ut/src/libcore/result.rs:916stack backtrace:
   0:     0x55c916c0f77c - backtrace::backtrace::trace::h9a9788e0a4feb260
   1:     0x55c916c0ede2 - backtrace::capture::Backtrace::new::h259826679d88d08f
   2:     0x55c916b93713 - grin_util::logger::send_panic_to_log::{{closure}}::h477e9823471f7d75
   3:     0x55c916c2b3a5 - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55c916c2b1be - std::panicking::begin_panic::h215af23ff6354aaf
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55c916c2b12a - std::panicking::begin_panic_fmt::h752224a2c436be23
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55c916c2b0c2 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55c916c8c2b0 - core::panicking::panic_fmt::h68e7715928be641f
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55c9167f4d88 - core::result::unwrap_failed::hd454efddbfb54506
   9:     0x55c9167d8d17 - <grin_api::handlers::TxHashSetHandler as iron::middleware::Handler>::handle::hdc143ea8853160ce
  10:     0x55c91690ddb0 - <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle::h7bbbe3bf1af08e64
  11:     0x55c9168acd33 - router::router::Router::handle_method::ha1c23ab7a04c7d26
  12:     0x55c9168ad3d6 - <router::router::Router as iron::middleware::Handler>::handle::h736b236e1da0f349
  13:     0x55c91690ddb0 - <alloc::boxed::Box<iron::middleware::Handler + 'static> as iron::middleware::Handler>::handle::h7bbbe3bf1af08e64
  14:     0x55c91685bddc - <mount::mount::Mount as iron::middleware::Handler>::handle::hc24e743b7da9d577
  15:     0x55c9166ba712 - <iron::iron::RawHandler<H> as hyper::server::Handler>::handle::h9b11ec9388454d26
  16:     0x55c91668dcb4 - <hyper::server::Worker<H>>::handle_connection::h6116d193f0061956
  17:     0x55c916665f9b - std::sys_common::backtrace::__rust_begin_short_backtrace::h9eecd5ace39ab0a2
  18:     0x55c9166cd8c6 - std::panicking::try::do_call::h6658fbc8cdecdbe6
  19:     0x55c916c4e20e - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  20:     0x55c9166d0338 - <F as alloc::boxed::FnBox<A>>::call_box::h5b1454299fba9446
  21:     0x55c916c3a587 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h45bad4268ff813ab
                        at /checkout/src/liballoc/boxed.rs:825
                         - std::sys_common::thread::start_thread::h97260957c81cf142
                        at /checkout/src/libstd/sys_common/thread.rs:24
  22:     0x55c916c2b918 - std::sys::unix::thread::Thread::new::thread_start::h3838be2df5be642c
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  23:     0x7fce3bed0063 - start_thread
  24:     0x7fce3b9ef62c - clone
  25:                0x0 - <unknown>
```

This is Grin version 0.2.0 (git testnet2-92-gf8732d7), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27).                                                                                            Built with profile "release", features "" on Sat, 28 Apr 2018 12:26:29 GMT.

**Comment by chri2** [comment]
might be the result of a broken chain on the node - chat from gitter:

Antioch Peverell @antiochp 20:26
it should only do it for a single block on init
(the latest valid block)
that's what you're seeing right? Or are you seeing it do it multiple times on init?

chri2 @chri2 20:28
Then there might be this error relevant:
```
May 07 20:26:47.229 DEBG chain: init: rewinding and validating before we start... 1c174299 at 55945
May 07 20:26:47.230 DEBG Rewind to header 55945 @ 1c174299
May 07 20:26:47.230 DEBG Rewind txhashset to 55945, BlockMarker { output_pos: 168997, kernel_pos: 140454 }
May 07 20:26:47.246 DEBG chain: init: building (missing) block sums for 55945 @ 1c174299
May 07 20:26:49.707 DEBG txhashset: summed 68946 outputs, pmmr size 168997, took 2s
May 07 20:26:52.247 DEBG txhashset: summed 70231 kernels, pmmr size 140454, took 2s
May 07 20:26:52.250 DEBG Error returned, discarding txhashset extension.
```
after that it starts over with
```
May 07 20:26:52.272 DEBG chain: init: rewinding and validating before we start... 77f00b6b at 55944
May 07 20:26:52.272 DEBG Rewind to header 55944 @ 77f00b6b
May 07 20:26:52.273 DEBG Rewind txhashset to 55944, BlockMarker { output_pos: 168995, kernel_pos: 140453 }
May 07 20:26:52.290 DEBG chain: init: building (missing) block sums for 55944 @ 77f00b6b
May 07 20:26:54.750 DEBG txhashset: summed 68945 outputs, pmmr size 168995, took 2s
May 07 20:26:57.296 DEBG txhashset: summed 70230 kernels, pmmr size 140453, took 2s
May 07 20:26:57.299 DEBG Error returned, discarding txhashset extension.
```
So it steps back block by block like it seems...

Antioch Peverell @antiochp 20:30
oh interesting - yes the latest code (past week or so?) will step back through blocks until it finds one that it can successfully validate
which suggests your MMRs are corrupted somehow
your node is not able to validate these blocks against the full chain state (held in the txhashset MMR files)
and we are preventing your node from starting up in an inconsistent/out-of-consensus state

chri2 @chri2 20:32
Hm, might that be the reason why the wallet couldn't restore, also?

Antioch Peverell @antiochp 20:32
normally it will rewind 0 (or possibly 1 blocks) to get to a valid block
yeah - might be the same issue

**Comment by chri2** [comment]
Couldn't reproduce with version testnet2-111-g0d9242e.
