### ISSUE TITLE
Corrupted storage, could not read an entry from hash store

### ISSUE THREAD

**Issue by chri2** [mimblewimble/grin#1056]
This is Grin version 0.2.0 (git testnet2-100-gad6e781), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9
e0 2018-02-27)

Started on an old server with slow I/O a sync from block 0. Two times the sync went up to around ~56000 of ~59000 blocks. Had to stop by pressing 'q' in the tui and starting grin server again two or three times to keep the sync going and after two or three times got the following message trying to start in grin.log:

```
May 08 13:18:06.108 INFO This is Grin version 0.2.0 (git testnet2-100-gad6e781), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27).
May 08 13:18:06.110 DEBG Built with profile "release", features "" on Mon, 07 May 2018 15:32:07 GMT.
May 08 13:18:06.110 INFO Starting the Grin server from configuration file at /home/grin/server/grin.toml
May 08 13:18:06.113 INFO Starting server, genesis block: 3346f63c
May 08 13:18:06.612 DEBG chain: init: rewinding and validating before we start... 1b088239 at 55975
May 08 13:18:06.613 DEBG Rewind to header 55975 @ 1b088239
May 08 13:18:06.614 DEBG Rewind txhashset to 55975, BlockMarker { output_pos: 169057, kernel_pos: 140514 }
May 08 13:18:06.931 ERRO Corrupted storage, could not read an entry from hash store: IOErr(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) })
May 08 13:18:06.932 ERRO Corrupted storage, could not read an entry from hash store: IOErr(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) })
May 08 13:18:06.932 ERRO Corrupted storage, could not read an entry from hash store: IOErr(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) })
May 08 13:18:06.933 ERRO Corrupted storage, could not read an entry from hash store: IOErr(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) })
May 08 13:18:06.933 ERRO Corrupted storage, could not read an entry from hash store: IOErr(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) })
May 08 13:18:06.934 ERRO Corrupted storage, could not read an entry from hash store: IOErr(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) })
May 08 13:18:06.934 ERRO Corrupted storage, could not read an entry from hash store: IOErr(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) })
May 08 13:18:07.725 ERRO 
thread 'main' panicked at 'no root, invalid tree': /checkout/src/libcore/option.rs:891stack backtrace:
   0:     0x563d362b8b1c - backtrace::backtrace::trace::h9a9788e0a4feb260
   1:     0x563d362b8182 - backtrace::capture::Backtrace::new::h259826679d88d08f
   2:     0x563d3623c903 - grin_util::logger::send_panic_to_log::{{closure}}::h477e9823471f7d75
   3:     0x563d362d4745 - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x563d362d455e - std::panicking::begin_panic::h215af23ff6354aaf
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x563d362d44ca - std::panicking::begin_panic_fmt::h752224a2c436be23
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x563d362d4462 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x563d36335650 - core::panicking::panic_fmt::h68e7715928be641f
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x563d36335f88 - core::option::expect_failed::h31f1de0db1aef2d6
                        at /checkout/src/libcore/option.rs:891
   9:     0x563d36056302 - <grin_core::core::pmmr::PMMR<'a, T, B>>::root::h1ad7a4dafa7a230e
  10:     0x563d36047b3c - grin_chain::txhashset::Extension::validate_roots::hfac89bfcff9a7fb1
  11:     0x563d36042c7d - grin_chain::txhashset::extending::h64714740050ac1a9
  12:     0x563d36020cb5 - grin_chain::chain::Chain::init::h0ed096235a94efdb
  13:     0x563d35d0251a - grin_servers::grin::server::Server::new::h1de70ade2c2873e6
  14:     0x563d35bed7d3 - grin_servers::grin::server::Server::start::h01fb55b9da699c8d
  15:     0x563d35bfd85b - grin::start_server::h4bbf3b4db327fcb0
  16:     0x563d35c0283e - grin::server_command::h931ce59c0ffc7f7b
  17:     0x563d35bffad5 - grin::main::h572050bdc9c1e9ec
  18:     0x563d35beead2 - std::rt::lang_start::{{closure}}::ha9ad688139d3a73f
  19:     0x563d362d43c7 - std::rt::lang_start_internal::{{closure}}::h6ddc513d95d559ac
                        at /checkout/src/libstd/rt.rs:59
                         - std::panicking::try::do_call::h7d33aea9be52481f
                        at /checkout/src/libstd/panicking.rs:480
  20:     0x563d362f75ae - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  21:     0x563d362db449 - std::panicking::try::h33108b08b6395be5
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind::hb0149e8b5a4339ed
                        at /checkout/src/libstd/panic.rs:365
                         - std::rt::lang_start_internal::h16c0c37ef62d8e5a
                        at /checkout/src/libstd/rt.rs:58
  22:     0x563d35c03273 - main
  23:     0x7f363b9afb44 - __libc_start_main
  24:     0x563d35bbf729 - <unknown>
  25:                0x0 - <unknown>
```

@duup complaint about something similar on grin-forum: https://www.grin-forum.org/t/corrupted-storage/371

**Comment by ignopeverell** [comment]
Would you have a big zip of your `.grin` folder handy by any chance?

**Comment by chri2** [comment]
Here's a .grin and the logfile of a unsuccesful sync:

http://z9.de/grin-dir-and-log-after-unsuccessfull-sync.tar.gz

**Comment by ignopeverell** [comment]
After checking, all I can see is that Grin is right :P Your range proof MMR is oddly truncated. These 2 files should both have the same size:

```
.grin/txhashet/output/pmmr_hash.bin
.grin/txhashet/rangeproof/pmmr_hash.bin
```

They all store hashes and so their sizes should also be a multiple of 32 bytes. The ouput hashes look fine and seem to validate, the issue is the range proof one that has less than half the size and not at all a multiple of 32. So it looks like it got corrupted somehow.

Anything special you did prior to that? Any chance of maybe 2 running instances of grin that could have been running over each other or something similar?

**Comment by antiochp** [comment]
@ignopeverell sort of related but this got me thinking - 
If the `output/pmmr_hash.bin` and `rangeproof/pmmr_hash.bin` files should _always_ be the same size (contents are identical) then presumably it would be a reasonably straightforward optimization to only store a single copy of this file?
Or do we see cases in the future where these get pruned/compacted differently?

**Comment by ignopeverell** [comment]
They have the same size but not the same content. The output one has output hashes while the range proof one has range proof hashes. Their rm_log should be the same tho, so we could eventually unify that, but it's not that big right now.

**Comment by antiochp** [comment]
Of course - the hashes are different...

**Comment by ignopeverell** [comment]
Looking at the logs, we have a previous restart with:

```
DEBG Rewind txhashset to 55950, BlockMarker { output_pos: 169006, kernel_pos: 140465 }
```

That succeeded, so the range proof MMR hash file must have been at least 5,408,192 bytes (169006*32). Then 25 blocks get downloaded and added to the chain, and the server is stopped when it starts to process 55976. Next restart some time later we have:

```
Rewind txhashset to 55975, BlockMarker { output_pos: 169057, kernel_pos: 140514 }
```

That totally makes sense but also totally fails as at that point, the hash file is only 2,399,924 bytes. The only thing in grin that could lead to that is a truncation of the file to a much smaller value than desired as we call the underlying OS function `ftruncate64(fd, offs as off64_t)`.

@chri2 so anything particular about that environment? Your logs tell me it's a 64 bits linux, is that correct?

**Comment by chri2** [comment]
Yes, correct. I/O is kind of slow on that virtual machine. It's running btrfs on top of lvm.

**Comment by jochemin** [comment]
Maybe related, I installed a node yesterday and it has been working fine, today I stopped it from the node pressing Q and it hasn't started again. Looking at the logs I see this error:
20190118 07:26:48.201 ERROR grin_store::types - Corrupted storage, could not rea                                                                             d an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)

Attached log:
[error.log](https://github.com/mimblewimble/grin/files/2771812/error.log)

To solve this, I have deleted all files and folders form data folder except wallet_data, after this it started syncing again.

**Comment by blkgrin** [comment]
I have gotten same error

```
0190122 16:45:46.641 INFO grin_util::logger - log4rs is initialized, file level: Debug,
20190122 16:45:46.641 INFO grin - Using configuration file at /home/v/grin-mainnet/grin-s
20190122 16:45:46.641 INFO grin - This is Grin version 1.0.0 (git v1.0.0-25-g55f4ee3), bu
20190122 16:45:46.641 DEBUG grin - Built with profile "release", features "".
20190122 16:45:46.641 WARN grin::cmd::server - Starting GRIN in UI mode...
20190122 16:45:46.641 INFO grin_servers::grin::server - Starting server, genesis block: 4
20190122 16:45:46.644 DEBUG grin_chain::txhashset::txhashset - Rewind to header 000004ca5
20190122 16:45:46.644 DEBUG grin_chain::txhashset::txhashset - txhashset: rewind_to_pos:
20190122 16:45:46.644 ERROR grin_store::types - Corrupted storage, could not read an entr
20190122 16:45:46.644 ERROR grin_store::types - Corrupted storage, could not read an entr
20190122 16:45:46.644 ERROR grin_store::types - Corrupted storage, could not read an entr
20190122 16:45:46.644 ERROR grin_store::types - Corrupted storage, could not read an entr
20190122 16:45:46.644 ERROR grin_store::types - Corrupted storage, could not read an entr
20190122 16:45:46.644 ERROR grin_store::types - Corrupted storage, could not read an entr
20190122 16:45:46.644 ERROR grin_store::types - Corrupted storage, could not read an entr
20190122 16:45:46.672 ERROR grin_util::logger - 
thread 'main' panicked at 'no root, invalid tree': libcore/option.rs:1008stack backtrace:
   0:     0x56091398babd - backtrace::backtrace::trace::hbaeac1dffd0b1b14
   1:     0x56091398a412 - backtrace::capture::Backtrace::new::h3509f99a179e939f
   2:     0x56091391b2e0 - grin_util::logger::send_panic_to_log::{{closure}}::haad0bb0c92
   3:     0x560913a5efa6 - std::panicking::rust_panic_with_hook::hef18d07c33eb725f
   4:     0x560913a5eaf1 - std::panicking::continue_panic_fmt::h3f92b0b1386b9b5e
   5:     0x560913a5e9d5 - rust_begin_unwind
   6:     0x560913a7d3dc - core::panicking::panic_fmt::hf131eae6172f8504
   7:     0x560913a7d452 - core::option::expect_failed::h7f4bf44987d20592
   8:     0x56091388d9ab - <grin_core::core::pmmr::pmmr::PMMR<'a, T, B>>::root::h18d2eeb7
   9:     0x560913849b9c - grin_chain::txhashset::txhashset::Extension::validate_roots::h
  10:     0x56091383d661 - grin_chain::txhashset::txhashset::extending::he0dc352d13e731
```

**Comment by kbs1** [comment]
Unable to sync here. If you get so lucky thay you get "waiting for remote peer to start" for 20000+ seconds (!!!!), and you press Q, you get this exact panic next time you attempt to resume syncing. 

This is Grin version 1.0.3 (git v1.0.3-1-g1b7d710), built for x86_64-unknown-linux-gnu by rustc 1.32.0 (9fda7c223 2019-01-16).

Is there any way to configure remote peer timeout?

**Comment by setovi** [comment]
What kbs1 said happened to me, too.

**Comment by antiochp** [comment]
I strongly suspect `v1.1.0` will resolve this as we change the way we download the txhashset with some more robust handling of various download failures.
I'm not 100% certain this will avoid the error described here, but pretty sure it will.
