### ISSUE TITLE
Failed to run grin server : thread 'main' panicked at 'Pre-set': core/src/global.rs:192stack

### ISSUE THREAD

**Issue by slashbinslashnoname** [mimblewimble/grin#1079]
I failed to launch previously built grin:

After running ```grin server run```, it outputs on Debian : 

````
May 18 16:11:22.318 DEBG Built with profile "release", features "" on Fri, 18 May 2018 13:48:50 GMT.
May 18 16:11:22.318 INFO Starting the Grin server (no configuration file) ...
Thread 'main' panicked with message:
"Pre-set"
See grin.log for further details.
May 18 16:11:22.339 ERRO pi server (e.g. transaction pool api)
thread 'main' panicked at 'Pre-set': core/src/global.rs:192stack  onbacktrace:nect to
   0:      0xc84efb536cc - backtrace::backtrace::trace::heaba8652 mining rewards will be sentfc04e149
   1:      0xc84efb51e52 - backtrace::capture::Backtrace::new::hfe8602475f4016d0and(s)
   2:      0xc84efad94ff - grin_util::logger::send_panic_to_log::{{closure}}::hacaac99e8b6fde30
   3:      0xc84efc0cf69 - std::panicking::rust_panic_with_hook::hed3a578f3d672948run
                        at libstd/panicking.rs:403-115-g4bbaa8d), built for x86_64-unknown-linux-gnu by rustc 1.26.0 (a77568041 2018-05-07).
   4:      0xc84efabd445 - std::panicking::begin_panic::h5b056853" on Fri, 18 May 2018 13:48:50 GMT.243ead19on file) ...
   5:      0xc84efabd162 - grin_core::global::get_genesis_nonce::hd52090c2671f1b04
   6:      0xc84efabbd10 - grin_core::genesis::genesis_dev::hba60c8750a640c03
   7:      0xc84ef570f76 - grin_servers::grin::server::Server::nebacktrace:w::hf25ef8ea52d3cc0afc04e149
   8:      0xc84ef4afaba - grin_servers::grin::server::Server::ste8602475f4016d0art::ha2733f1d62d4b0b1{{closure}}::hacaac99e8b6fde30
   9:      0xc84ef4ee21d - grin::start_server_tui::h19223ae8a5545hed3a578f3d6729486e4
  10:      0xc84ef4f3f60 - grin::server_command::h844ec2b52d32caf243ead197hd52090c2671f1b04
  11:      0xc84ef4f06ad - grin::main::h0df9dac4edf85f90c8750a640c03
  12:      0xc84ef4ba832 - std::rt::lang_start::{{closure}}::h3bbw::hf25ef8ea52d3cc0a08a10c4a587f9art::ha2733f1d62d4b0b1
  13:      0xc84efc0cbe7 - std::rt::lang_start_internal::{{closur6e4e}}::h30a15dfbaf2db7417
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h84e823e08a10c4a587f9f113bafaae}}::h30a15dfbaf2db741
                        at libstd/panicking.rs:306
  14:      0xc84efc2041e - __rust_maybe_catch_panicf113bafaa
                        at libpanic_unwind/lib.rs:102
  15:      0xc84efc09695 - std::panicking::try::h29c76d75c597e452
                        at libstd/panicking.rs:285
                         - std::panic::catch_unwind::h33ca23d1ecc573a8
                        at libstd/panic.rs:361573a8
                         - std::rt::lang_start_internal::h26bd2a105967b45905967b459
                        at libstd/rt.rs:58
  16:      0xc84ef4f4553 - main
  17:     0x70c0a1466b44 - __libc_start_main
  18:      0xc84ef49cb09 - <unknown>
  19:                0x0 - <unknown>
````

**Comment by slashbinslashnoname** [comment]
Yep, no ``grin.toml```file in the directory

I did 
```cd&&cd grin/target/release
touch grin.toml
cargo run```

Cargo compiled .

Then finished everything and launched `grin`but with an error : 
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

I've moved in the `grin`directory : `cd && cd grin` and launched `cargo run` and it worked.
<img width="520" alt="Grin Mimble Wimble Much Crazy Such Wow" src="https://user-images.githubusercontent.com/515119/40379723-30d806b6-5df7-11e8-8f46-81056d646984.png">

 ¯\_(ツ)_/¯

**Comment by ignopeverell** [comment]
Pushed 9074653 to crash loudly instead and avoid future confusion.
