### ISSUE TITLE
Borrow Error

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1144]
Sometimes, when the node accepts a block I get this error message:
```
thread 'peer' panicked at 'already mutably borrowed: BorrowError':
```

More logs:
```
Jun 07 14:18:56.424 DEBG ping/pong: 159.89.151.111:13414: 97020 @ 72000 vs us: 137651 @ 100284
Jun 07 14:18:57.059 DEBG ping/pong: 155.94.230.21:13414: 118966 @ 86221 vs us: 137651 @ 100284
Jun 07 14:18:57.096 DEBG ping/pong: 144.202.92.115:13414: 129489 @ 94000 vs us: 137651 @ 100284
Jun 07 14:18:58.651 DEBG ping/pong: 109.74.202.16:13414: 137516 @ 100149 vs us: 137651 @ 100284
Jun 07 14:18:59.119 DEBG handle_payload: CompactBlock: 6ebc3005
Jun 07 14:18:59.120 DEBG Received compact_block 6ebc3005 at 100285 from 94.130.229.193:13414, going to process.
Jun 07 14:18:59.121 DEBG pipe: process_block 6ebc3005 at 100285 with 0 inputs, 1 outputs, 1 kernels
Jun 07 14:18:59.156 DEBG pipe: chain head reached 100285 @ 137652 [6ebc3005]
Jun 07 14:18:59.723 DEBG adapter: block_accepted: 6ebc3005
Jun 07 14:18:59.729 ERRO 
thread 'peer' panicked at 'already mutably borrowed: BorrowError': libcore/result.rs:945stack backtrace:
   0:     0x559f1b5c2694 - backtrace::backtrace::libunwind::trace::h5820195e11aea42c
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h9f5a7f7c3d9acf78
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/mod.rs:42
   1:     0x559f1b5c030c - backtrace::capture::Backtrace::new_unresolved::h993011d448440454
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:88
   2:     0x559f1b5c025e - backtrace::capture::Backtrace::new::hd86b1c76133310b3
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:63
   3:     0x559f1b43f8ac - grin_util::logger::send_panic_to_log::{{closure}}::h41b2cd4e8f5112eb
                        at util/src/logger.rs:119
   4:     0x559f1b8b94b9 - std::panicking::rust_panic_with_hook::hed3a578f3d672948
                        at libstd/panicking.rs:403
   5:     0x559f1b8b92a2 - std::panicking::begin_panic_fmt::h3e8fdd00db89fef8
                        at libstd/panicking.rs:349
   6:     0x559f1b8b91d2 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x559f1b908dd0 - core::panicking::panic_fmt::h16b501044b4579f2
                        at libcore/panicking.rs:72
   8:     0x559f1a5edaab - core::result::unwrap_failed::hf511c6a990a6078d
                        at /checkout/src/libcore/macros.rs:26
   9:     0x559f1a5e56a5 - <core::result::Result<T, E>>::expect::hea30ff336941bdc8
                        at /checkout/src/libcore/result.rs:809
  10:     0x559f1a687f98 - <core::cell::RefCell<T>>::borrow::h819291c1578c46f7
                        at /checkout/src/libcore/cell.rs:709
  11:     0x559f1a637374 - <grin_util::OneTime<T>>::borrow::hf4bac145de54f65b
                        at /root/grin/util/src/lib.rs:105
  12:     0x559f1a6969e4 - grin_servers::common::adapters::wo::h186a81f9397efbe7
                        at servers/src/common/adapters.rs:49
  13:     0x559f1a57938c - <grin_servers::common::adapters::ChainToPoolAndNetAdapter as grin_chain::types::ChainAdapter>::block_accepted::h1aa5d94feeb09c45
                        at servers/src/common/adapters.rs:606
  14:     0x559f1aed6829 - grin_chain::chain::Chain::process_block_no_orphans::h5ed80e94917dbc61
                        at chain/src/chain.rs:336
  15:     0x559f1aed5d79 - grin_chain::chain::Chain::process_block::hbea10a80eb80f95b
                        at chain/src/chain.rs:295
  16:     0x559f1a5779d3 - grin_servers::common::adapters::NetToChainAdapter::process_block::h52d633ffca9d956a
                        at servers/src/common/adapters.rs:409
  17:     0x559f1a572cf9 - <grin_servers::common::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::h1bff6323fd3b5829
                        at servers/src/common/adapters.rs:123
  18:     0x559f1adf2f5b - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::compact_block_received::h6b0320f7cc986317
                        at p2p/src/peers.rs:570
  19:     0x559f1add95d8 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::ha5f0b2185a1edfb0
                        at p2p/src/peer.rs:407
  20:     0x559f1adff361 - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::hb57acf5cb963184b
                        at p2p/src/protocol.rs:151
  21:     0x559f1ae2dd98 - grin_p2p::conn::poll::{{closure}}::h07060ed7739a9aad
                        at p2p/src/conn.rs:215
  22:     0x559f1ae89d45 - std::sys_common::backtrace::__rust_begin_short_backtrace::hae80365391222b3f
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  23:     0x559f1ae198b9 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h763cb6bb77003eff
                        at /checkout/src/libstd/thread/mod.rs:406
  24:     0x559f1ae6fa15 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h35053a7473f2ea5f
                        at /checkout/src/libstd/panic.rs:296
  25:     0x559f1ae40431 - std::panicking::try::do_call::h824ed027c17b647a
                        at /checkout/src/libstd/panicking.rs:306
  26:     0x559f1b8ccaae - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  27:     0x559f1ae401e9 - std::panicking::try::h4829fec20d0618a8
                        at /checkout/src/libstd/panicking.rs:285
  28:     0x559f1ae6fac5 - std::panic::catch_unwind::hd694bd20ddbc16c8
                        at /checkout/src/libstd/panic.rs:361
  29:     0x559f1ae196bd - std::thread::Builder::spawn::{{closure}}::he7be586196f489b5
                        at /checkout/src/libstd/thread/mod.rs:405
  30:     0x559f1ae19936 - <F as alloc::boxed::FnBox<A>>::call_box::h36e8053670089019
                        at /checkout/src/liballoc/boxed.rs:784
  31:     0x559f1b8c1c47 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h3a46ab40d44ff8db
                        at /checkout/src/liballoc/boxed.rs:794
                         - std::sys_common::thread::start_thread::heca3dbba8ff4f46a
                        at libstd/sys_common/thread.rs:24
  32:     0x559f1b8ada98 - std::sys::unix::thread::Thread::new::thread_start::ha1ecaaa6d3efa77d
                        at libstd/sys/unix/thread.rs:90
  33:     0x7fd0de71f493 - start_thread
  34:     0x7fd0de24aace - __clone
  35:                0x0 - <unknown>


Jun 07 14:18:59.859 DEBG Received block header 6ebc3005 at 100285 from 185.80.129.70:13414, going to process.
Jun 07 14:18:59.859 DEBG pipe: process_block_header at 100285 [6ebc3005]
Jun 07 14:18:59.860 DEBG Block header 6ebc3005 refused by chain: Unfit("already known")
Jun 07 14:19:00.291 DEBG ping/pong: 45.61.156.122:13414: 64734 @ 42164 vs us: 137652 @ 100285
```

**Comment by hashmap** [comment]
@quentinlesceller have you experienced this bug since that time? I tried to reproduce it a few times and was checking the source code, don't see how it may happen to be fair, but it looks very interesting.

**Comment by quentinlesceller** [comment]
Nope @hashmap closing that one since it's a very old bug. Will reopen if I step on it again.
