### ISSUE TITLE
MDB_READERS_FULL: Environment maxreaders limit reached

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1267]
```
thread 'peer' panicked at 'called `Result::unwrap()` on an `Err` value: LmdbErr(Error::Code(-30790, 'MDB_READERS_FULL: Environment maxreaders limit reached'))': libcore/result.rs:945stack backtrace:
   0:     0x5601f7f4a83c - backtrace::backtrace::trace::hc453d8de04fccd1c
   1:     0x5601f7f48fc2 - backtrace::capture::Backtrace::new::h90cc83bd4260d831
   2:     0x5601f7ec8eff - grin_util::logger::send_panic_to_log::{{closure}}::heac79271798e8137
   3:     0x5601f8023a09 - std::panicking::rust_panic_with_hook::habacef8c65a3b0d4
                        at libstd/panicking.rs:403
   4:     0x5601f80237f2 - std::panicking::begin_panic_fmt::h20e14b91a98870b3
                        at libstd/panicking.rs:349
   5:     0x5601f8023722 - rust_begin_unwind
                        at libstd/panicking.rs:325
   6:     0x5601f80733e0 - core::panicking::panic_fmt::h8a30aa26a6a035a8
                        at libcore/panicking.rs:72
   7:     0x5601f7dbd1f8 - core::result::unwrap_failed::hd0d146f1ac749054
   8:     0x5601f7d8b4ca - grin_p2p::store::PeerStore::find_peers::h598097deb7764b0f
   9:     0x5601f7d98eba - <grin_p2p::peers::Peers as grin_p2p::types::NetAdapter>::find_peer_addrs::h05ef945d72ce0bdb
  10:     0x5601f7d86df1 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::find_peer_addrs::h2a21fb2819920891
  11:     0x5601f7da171b - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::hbab0618c616e9f28
  12:     0x5601f7d9dd83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h688fff81f33ee577
  13:     0x5601f7da9b58 - std::panicking::try::do_call::h8aa62ba59eb7a3fa
  14:     0x5601f8036efe - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  15:     0x5601f7dac425 - <F as alloc::boxed::FnBox<A>>::call_box::h37b722bcc2b83bf0
  16:     0x5601f802c097 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h4b3bd62cb4ac177f
                        at /checkout/src/liballoc/boxed.rs:794
                         - std::sys_common::thread::start_thread::h0b7f53596953c14b
                        at libstd/sys_common/thread.rs:24
  17:     0x5601f8018038 - std::sys::unix::thread::Thread::new::thread_start::hce65be213f90eb53
                        at libstd/sys/unix/thread.rs:90
  18:     0x7ff674fe8493 - start_thread
  19:     0x7ff674b13ace - __clone
  20:                0x0 - <unknown>

```

**Comment by ignopeverell** [comment]
Anything unusual you were doing at that time? Default is 126 readers, which is a fair amount.

**Comment by bladedoyle** [comment]
Possibly.   This grin instance is being used by my pool, so the wallet and API are being used often.  A few examples:
* There is a process that calls the /v1/status api once every second looking for new block height
* There is a process that runs every hour and queries the latest 1000 blocks using /v1/blocks/ API
* There is a process that attempts to make a wallet send tx several times per hour

**Comment by ignopeverell** [comment]
Okay, that makes more sense. I need to see if there's any downside un bumping that value up by default.

**Comment by mfronczyk** [comment]
I don’t know the internals very well, but 126 simultaneous readers should be fine to handle that activity. Should we check if all the reading code gently closes db connections before increasing the constant?

**Comment by ignopeverell** [comment]
It'd be good to double-check yes. But I'm assuming we would see that in longer-running grin instances (like seed nodes) if it was leaking readers.

**Comment by bladedoyle** [comment]
FTR: I do continue to see this issue, but it isnt as deterministic as I would expect it to be.  Sometimes I dont see it for several days, one time it re-occurred an hour after restarting.

**Comment by antiochp** [comment]
Anecdotal: I left a grin server running and put my laptop to sleep.
On waking the laptop I think I saw this happen and I'm guessing it is related to the network connections dropping and what appeared to be a *lot* of peering attempts all happening simultaneously.

**Comment by hashmap** [comment]
Closing for now, it seems to be fixed
