### ISSUE TITLE
Error creating wallet: Serde JSON error

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1270]
```
root@grin-6c5dd87ff9-prw7q:/server# grin wallet info
Thread 'main' panicked with message:
"Error creating wallet: Serde JSON error 
 Cause: EOF while parsing a string at line 1114 column 8 
 Backtrace:  Config: WalletConfig { api_listen_interface: "0.0.0.0", api_listen_port: 13415, check_node_api_http_addr: "http://localhost:13413", data_file_dir: "." }"
See grin.log for further details.
Jul 16 18:07:09.162 ERRO 
thread 'main' panicked at 'Error creating wallet: Serde JSON error 
 Cause: EOF while parsing a string at line 1114 column 8 
 Backtrace:  Config: WalletConfig { api_listen_interface: "0.0.0.0", api_listen_port: 13415, check_node_api_http_addr: "http://localhost:13413", data_file_dir: "." }': src/bin/grin.rs:572stack backtrace:
   0:     0x56543b05b83c - backtrace::backtrace::trace::hc453d8de04fccd1c
   1:     0x56543b059fc2 - backtrace::capture::Backtrace::new::h90cc83bd4260d831
   2:     0x56543afd9eff - grin_util::logger::send_panic_to_log::{{closure}}::heac79271798e8137
   3:     0x56543b134a09 - std::panicking::rust_panic_with_hook::habacef8c65a3b0d4
                        at libstd/panicking.rs:403
   4:     0x56543b1347f2 - std::panicking::begin_panic_fmt::h20e14b91a98870b3
                        at libstd/panicking.rs:349
   5:     0x56543abe206c - grin::instantiate_wallet::h2c42b025440f47b5
   6:     0x56543abdedb7 - grin::main::hbadde614667b559e
   7:     0x56543ab6f302 - std::rt::lang_start::{{closure}}::h75b6fae3e5a3fc7a
   8:     0x56543b134687 - std::rt::lang_start_internal::{{closure}}::hb3d070a2bac9f126
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hfce3050be9508e94
                        at libstd/panicking.rs:306
   9:     0x56543b147efe - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  10:     0x56543b131135 - std::panicking::try::h181b418ccf9daec0
                        at libstd/panicking.rs:285
                         - std::panic::catch_unwind::h2e22b8787335a1ba
                        at libstd/panic.rs:361
                         - std::rt::lang_start_internal::h4193b9a4ab9d505a
                        at libstd/rt.rs:58
  11:     0x56543abe22c3 - main
  12:     0x7f9f1e4d42e0 - __libc_start_main
  13:     0x56543ab03439 - _start
  14:                0x0 - <unknown>
```

Note:  a subsequent call to grin wallet info worked fine.

**Comment by beaver-tooth** [comment]
+1 I also received this error, sometimes more than once. However, if I ran `grin wallet info` enough times it would work.

**Comment by ignopeverell** [comment]
This very likely happened with the wallet file backend which has now been replaced by the LMDB one. Feel free to reopen if I'm wrong and still occurs.
