### ISSUE TITLE
Grin wallet error message when no fund for fee is unclear

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1299]
Currently trying to spend a coinbase output and sending exactly 60 grins produce this message.
And it looks like the node crash and restart directly.
```
Jul 27 15:42:14.276 DEBG Building input (spending regular output): 60000000000, 660276d6e94571f546ff
Jul 27 15:42:14.293 DEBG Building an output: 18446744073705551616, 9433b4b13cf2cf7af368
Jul 27 15:42:14.377 DEBG Posting transaction slate to http://127.0.0.1:13415/v1/wallet/foreign/receive_tx
Jul 27 15:42:14.381 DEBG Using wallet seed file at: ./wallet.seed
Jul 27 15:42:14.398 DEBG Building an output: 60000000000, 2a3fcc4d59c0975944f9
Jul 27 15:42:14.485 ERRO Communication with receiver failed on SenderInitiation send. Aborting transaction Error { inner: Io(Custom { kind: Other, error: Error("EOF while parsing a value", line: 1, column: 0) })

Client Callback Error: Sending transaction: posting request }
Jul 27 15:42:14.485 ERRO Request Error: Error { inner: Io(Custom { kind: Other, error: Error("EOF while parsing a value", line: 1, column: 0) })

Client Callback Error: Sending transaction: posting request }
Jul 27 15:42:14.485 ERRO Request Error: Error { inner: Io(Custom { kind: Other, error: Error("EOF while parsing a value", line: 1, column: 0) })

Client Callback Error: Sending transaction: posting request }
Jul 27 15:42:17.037 DEBG Using wallet seed file at: ./wallet.seed
Jul 27 15:42:17.057 DEBG receive_coinbase: built candidate output - Identifier(fdad9aaa575420121dab), 179
Jul 27 15:42:17.057 DEBG receive_coinbase: BlockFees { fees: 0, height: 25787, key_id: Some(Identifier(fdad9aaa575420121dab)) }
Jul 27 15:42:17.149 DEBG get_coinbase: BlockFees { fees: 0, height: 25787, key_id: Some(Identifier(fdad9aaa575420121dab)) }
Jul 27 15:42:17.183 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 419, cumulative difficulty 5565699
Jul 27 15:42:17.187 DEBG (Server ID: StratumServer) sending block 25787 with id 2 to stratum clients
Jul 27 15:42:19.155 INFO This is Grin version 0.3.0 (git testnet3-48-g70b97b0), built for x86_64-unknown-linux-gnu by rustc 1.27.0 (3eda71b00 2018-06-19).
Jul 27 15:42:19.155 DEBG Built with profile "release", features "" on Wed, 25 Jul 2018 19:58:28 GMT.
Jul 27 15:42:19.156 INFO Using LMDB Backend for wallet
Jul 27 15:42:19.156 INFO Using LMDB Backend for wallet
Jul 27 15:42:19.156 DEBG Using wallet seed file at: ./wallet.seed
Jul 27 15:42:19.175 DEBG Refreshing wallet outputs
```

**Comment by bladedoyle** [comment]
I get this same error message from the wallet when trying to send grin.  But in my case there are enough funds available, and I dont see any crash.

```
Jul 30 20:07:17.974 ERRO Communication with receiver failed on SenderInitiation send. Aborting transaction Error { inner: Io(Custom { kind: Other, error: Error("EOF while parsing a value", line: 1, column: 0) })\n\nClient Callback Error: Sending transaction: posting request }\nJul 30 20:07:17.974 ERRO Tx not created: Error { inner: Io(Custom { kind: Other, error: Error("EOF while parsing a value", line: 1, column: 0) })\n\nClient Callback Error: Sending transaction: posting request }\nJul 30 20:07:17.974 ERRO Backtrace: \nThread \'main\' panicked with message:\n"explicit panic"\nSee grin.log for further details.\nJul 30 20:07:17.984 ERRO \nthread \'main\' panicked at \'explicit panic\': src/bin/grin.rs:724stack backtrace:\n   0:     0x56373eedafcc - backtrace::backtrace::trace::hc453d8de04fccd1c\n   1:     0x56373eed9752 - backtrace::capture::Backtrace::new::h90cc83bd4260d831\n   2:     0x56373ee52fef - grin_util::logger::send_panic_to_log::{{closure}}::h599079d1fbcb7241\n   3:     0x56373efb40b9 - std::panicking::rust_panic_with_hook::habacef8c65a3b0d4\n                        at libstd/panicking.rs:403\n   4:     0x56373ea2ba65 - std::panicking::begin_panic::h2c40327dc9d36704\n   5:     0x56373ea5c9c8 - grin_wallet::libwallet::controller::owner_single_use::hfb68c91956576c48\n   6:     0x56373ea00a29 - grin::main::h7c23134d911a74c5\n   7:     0x56373e9d69a2 - std::rt::lang_start::{{closure}}::h4a24def3947a60ee\n   8:     0x56373efb3d37 - std::rt::lang_start_internal::{{closure}}::hb3d070a2bac9f126\n                        at libstd/rt.rs:59\n                         - std::panicking::try::do_call::hfce3050be9508e94\n                        at libstd/panicking.rs:306\n   9:     0x56373efc75ae - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:102\n  10:     0x56373efb07e5 - std::panicking::try::h181b418ccf9daec0\n                        at libstd/panicking.rs:285\n                         - std::panic::catch_unwind::h2e22b8787335a1ba\n                        at libstd/panic.rs:361\n                         - std::rt::lang_start_internal::h4193b9a4ab9d505a\n                        at libstd/rt.rs:58\n  11:     0x56373ea03c83 - main\n  12:     0x7fca638832e0 - __libc_start_main\n  13:     0x56373e982689 - _start\n  14:                0x0 - <unknown>\n\n\n'
```

**Comment by quentinlesceller** [comment]
@bladedoyle  I think you encountered something similar but in case your case ```amount_with_fee``` > ```total``` where total is the total funds per outputs selected. In that case the wallet should reselect more  outputs and recalculate fee.
