### ISSUE TITLE
Wallet owner_api fails to run after Hyper upgrade

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#1308]
Following from #1241, trying to run the wallet owner api (which enables the web-wallet) appears to fail consistently with the following in the log:

```
Aug 01 10:37:25.043 INFO Starting HTTP Owner API server at 127.0.0.1:13420.                                                                    
Aug 01 10:37:29.861 DEBG ROUTER stop card                                                                                                         
Aug 01 10:37:29.861 DEBG Using wallet seed file at: ./wallet.seed                                                                                     
Aug 01 10:37:30.140 ERRO                                                                                                                                  
thread 'main' panicked at 'cannot recursively call into `Core`': libcore/option.rs:914stack backtrace:                            
   0:     0x55fcdcac84e5 - backtrace::backtrace::libunwind::trace::ha04d14f8eb87ea0d                                                        
                        at /home/mcordner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h4cd1d2ddd3ac8572                                                                   
                        at /home/mcordner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42 
   1:     0x55fcdcac3d1e - backtrace::capture::Backtrace::new_unresolved::h2865c314ced45500                                            
                        at /home/mcordner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88                    
   2:     0x55fcdcac3c5d - backtrace::capture::Backtrace::new::hc390fad7066458de                                                           
                        at /home/mcordner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63       
   3:     0x55fcdc95654a - grin_util::logger::send_panic_to_log::{{closure}}::hac1fafd1dc1a907d                                             
                        at util/src/logger.rs:118                                                                              
   4:     0x55fcdce85325 - std::panicking::rust_panic_with_hook::h6617a62274b53c0e                                                                
                        at libstd/panicking.rs:467                                                                                
   5:     0x55fcdce84e6c - std::panicking::begin_panic_fmt::hc7dc6580ccb0884f                                                               
                        at libstd/panicking.rs:350                                                                                
   6:     0x55fcdce84e31 - rust_begin_unwind                                                                                                
                        at libstd/panicking.rs:328                                                                                             
   7:     0x55fcdcee2402 - core::panicking::panic_fmt::h802d6f07d666ebad                                                                       
                        at libcore/panicking.rs:71                                                                                                       
   8:     0x55fcdceee0f1 - core::option::expect_failed::h8d126a2329be5673                                                                      
                        at libcore/option.rs:914                                                                                         
   9:     0x55fcdc25070c - <core::option::Option<T>>::expect::hc5686cfe3c1103dc                                                 
                        at /checkout/src/libcore/option.rs:302                                                                          
  10:     0x55fcdc17f04b - tokio_core::reactor::Core::run::h48adc97fe24dd89d                                                     
                        at /home/mcordner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:224     
  11:     0x55fcdc11d030 - grin_api::client::send_request::h2a200d34cc2f1a62                                                                              
                        at api/src/client.rs:136                                                                                               
  12:     0x55fcdc0115d3 - grin_api::client::handle_request::h7a64fed4a67d5849                                                     
                        at /home/mcordner/projects/rust/grin-raw/api/src/client.rs:105                                                            
  13:     0x55fcdc01595d - grin_api::client::get::h96d2566ea4453b77                                                                            
                        at /home/mcordner/projects/rust/grin-raw/api/src/client.rs:49                                                             
  14:     0x55fcdc0bc8ee - <grin_wallet::client::HTTPWalletClient as grin_wallet::libwallet::types::WalletClient>::get_chain_height::hac251c72f4796cb7
                        at wallet/src/client.rs:111                                                                                         
  15:     0x55fcdbcb933d - <grin_wallet::libwallet::api::APIOwner<W, C, K>>::node_height::h14dd2fd036a04a10                       
                        at /home/mcordner/projects/rust/grin-raw/wallet/src/libwallet/api.rs:235                                            
  16:     0x55fcdbc3ffe4 - <grin_wallet::libwallet::controller::OwnerAPIHandler<T, C, K>>::node_height::h5f857d7f8c4f5478              
                        at /home/mcordner/projects/rust/grin-raw/wallet/src/libwallet/controller.rs:245                                     
  17:     0x55fcdbc40e4d - <grin_wallet::libwallet::controller::OwnerAPIHandler<T, C, K>>::handle_get_request::h06442e286d60210f  
```

If you need to reproduce, note this is just on a new `UserTesting` chain mining into the default wallet.

**Comment by hashmap** [comment]
I'll take care of it

**Comment by hashmap** [comment]
I'm able to get response for `curl http://localhost:13420/v1/wallet/owner/retrieve_txs` I hope it has been fixed, could you confirm @yeastplume ?

**Comment by ignopeverell** [comment]
I can confirm :smile:
