### ISSUE TITLE
Wallet send crash

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#1314]
```
Aug 03 20:39:12.852 DEBG HTTP API -> status: 200 OK, text: "{\"protocol_version\":1,\"user_agent\":\"MW/Grin 0.3.0\",\"connections\":19,\"tip\":{\"height\":35913,\"last_block_pushed\":\"06c04690d758a5c8516525443a3b3a9d1e4fe1eaf23b5062caf35dba69ff17ad\",\"prev_block_to_last\":\"0d09faa01cc2bf066ed82054b577cbfef4755de906888b5065f412a0cd42c04a\",\"total_difficulty\":9916871}}"
Aug 03 20:39:15.541 DEBG ROUTER stop card
Aug 03 20:39:15.541 DEBG Using wallet seed file at: ./wallet.seed
Aug 03 20:39:15.571 ERRO 
thread 'wallet_owner_listener' panicked at 'cannot recursively call into `Core`': libcore/option.rs:914stack backtrace:
   0:     0x55cf4f53a0cc - backtrace::backtrace::trace::ha2400a46653aa147
   1:     0x55cf4f539632 - backtrace::capture::Backtrace::new::hba0db67162ef49d0
   2:     0x55cf4f4c3c6f - grin_util::logger::send_panic_to_log::{{closure}}::h7e87405d223a978b
   3:     0x55cf4f60ba05 - std::panicking::rust_panic_with_hook::hd6baf0cfc62bef0f
                        at libstd/panicking.rs:467
   4:     0x55cf4f60b54c - std::panicking::begin_panic_fmt::h067a7944e7e0f96e
                        at libstd/panicking.rs:350
   5:     0x55cf4f60b511 - rust_begin_unwind
                        at libstd/panicking.rs:328
   6:     0x55cf4f6692c2 - core::panicking::panic_fmt::h61b193aee9efb823
                        at libcore/panicking.rs:71
   7:     0x55cf4f674d11 - core::option::expect_failed::h4927e1fef06c4878
                        at libcore/option.rs:914
   8:     0x55cf4f2b842f - tokio_core::reactor::Core::run::h9851c7f7c4d72a74
   9:     0x55cf4f279cf5 - grin_api::client::send_request::h39c1786a752554e4
  10:     0x55cf4f1d6183 - grin_api::client::get::h4cc8e93124826212
  11:     0x55cf4f1cec8b - <grin_wallet::client::HTTPWalletClient as grin_wallet::libwallet::types::WalletClient>::get_chain_height::h33cab95feaa3959b
  12:     0x55cf4f00f28b - grin_wallet::libwallet::internal::tx::create_send_tx::h1257965a3769b04b
  13:     0x55cf4f03abe3 - <grin_wallet::libwallet::api::APIOwner<W, C, K>>::issue_send_tx::ha98f650386a09fef
  14:     0x55cf4f071298 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h684af06b5bf51fb2
  15:     0x55cf4f073165 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h91e139bb81faa1ed
  16:     0x55cf4f06cc3f - <futures::future::or_else::OrElse<A, B, F> as futures::future::Future>::poll::hfe124a7e5be1f722
  17:     0x55cf4f02169a - <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, T>>::poll_inner::hf6896d1c5eb47bf7
  18:     0x55cf4f01c379 - <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, T>>::poll_catch::h78f415d367e58f8d
  19:     0x55cf4f00d3d0 - <hyper::server::conn::upgrades::UpgradeableConnection<I, S> as futures::future::Future>::poll::hfaaf8811a0ba7b77
  20:     0x55cf4f076ff7 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::hec54ecde38db0294
  21:     0x55cf4f046646 - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h828c734248f4c753
  22:     0x55cf4efec3ef - futures::task_impl::std::set::h2b27d2c5f6fcb210
  23:     0x55cf4f017a09 - tokio::executor::current_thread::CurrentRunner::set_spawn::hb86b7402f0589231
  24:     0x55cf4f00784e - <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::h010d70dad6723653
  25:     0x55cf4f01a160 - <tokio::executor::current_thread::Entered<'a, P>>::tick::hfd9c2b1ee1111198
  26:     0x55cf4f01a555 - <tokio::executor::current_thread::Entered<'a, P>>::block_on::haa55e3b33b02afd8
  27:     0x55cf4efb9e3d - <std::thread::local::LocalKey<T>>::with::h138d5b99d560d669
  28:     0x55cf4efbaca7 - <std::thread::local::LocalKey<T>>::with::h7e860f654e1ad17b
  29:     0x55cf4efba89d - <std::thread::local::LocalKey<T>>::with::h5a058e0aeac9d72b
  30:     0x55cf4efbb772 - <std::thread::local::LocalKey<T>>::with::hcd570ef2e94725e6
  31:     0x55cf4f04534e - grin_api::rest::ApiServer::start::h0f8e28ccaae3191b
  32:     0x55cf4efb99b7 - <std::thread::local::LocalKey<T>>::with::h0b69963288da18fd
  33:     0x55cf4efa51d5 - grin_wallet::libwallet::controller::owner_listener::h550b343f7c6c1048
  34:     0x55cf4efcba5b - std::sys_common::backtrace::__rust_begin_short_backtrace::h92ec2957bf8ee12d
  35:     0x55cf4efcbbdf - std::panicking::try::do_call::h479731368eaf946a
  36:     0x55cf4f62f789 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  37:     0x55cf4efeabec - <F as alloc::boxed::FnBox<A>>::call_box::hca5b5dbd92c7a4ac
  38:     0x55cf4f6233da - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output=R> + 'a> as core::ops::function::FnOnce<A>>::call_once::h69e8f44b3723e1ca
                        at /checkout/src/liballoc/boxed.rs:648
                         - std::sys_common::thread::start_thread::hd31f5c5fa3e47024
                        at libstd/sys_common/thread.rs:24
  39:     0x55cf4f60bf45 - std::sys::unix::thread::Thread::new::thread_start::hb3e7825324ee0f62
                        at libstd/sys/unix/thread.rs:90
  40:     0x7fc8746226b9 - start_thread
  41:     0x7fc87414241c - clone
  42:                0x0 - <unknown>
```

**Comment by hashmap** [comment]
Make sure you run the latest master, if the issue still exists https://github.com/mimblewimble/grin/pull/1312 is supposed to fix it.

**Comment by hashmap** [comment]
@quentinlesceller do you still have this issue with the latest master?

**Comment by quentinlesceller** [comment]
Looks like it is fixed @hashmap!
