### ISSUE TITLE
thread 'main' panicked at 'Unable to find libclang

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#1606]
On a centos7 machine I get the following error when trying to compile grin
```console
[kargakis@localhost grin]$ RUST_BACKTRACE=1 cargo build --release
   Compiling croaring-sys v0.3.6                                                                                                                                                                                   
error: failed to run custom build command for `croaring-sys v0.3.6`
process didn't exit successfully: `/home/kargakis/projects/grin/target/release/build/croaring-sys-89fb8fffe9e038b0/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-std=c11" "-march=native" "-O3" "-Wall" "-Wextra" "-o" "/home/kargakis/projects/grin/target/release/build/croaring-sys-a4c254c9aaa21bd5/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c"
cargo:warning=In file included from CRoaring/roaring.c:2:0:
cargo:warning=CRoaring/roaring.c: In function ‘roaring_bitmap_remove_range_closed’:
cargo:warning=CRoaring/roaring.h:6109:22: warning: ‘new_type’ may be used uninitialized in this function [-Wmaybe-uninitialized]
cargo:warning=     ra->typecodes[i] = typecode;
cargo:warning=                      ^
cargo:warning=CRoaring/roaring.c:7619:17: note: ‘new_type’ was declared here
cargo:warning=         uint8_t new_type;
cargo:warning=                 ^
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
running: "ar" "crs" "/home/kargakis/projects/grin/target/release/build/croaring-sys-a4c254c9aaa21bd5/out/libroaring.a" "/home/kargakis/projects/grin/target/release/build/croaring-sys-a4c254c9aaa21bd5/out/CRoaring/roaring.o"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
cargo:rustc-link-lib=static=roaring
cargo:rustc-link-search=native=/home/kargakis/projects/grin/target/release/build/croaring-sys-a4c254c9aaa21bd5/out

--- stderr
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.5.0 could not be opened: libclangAST.so.5: cannot open shared object file: No such file or directory"', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: std::sync::once::Once::call_once::{{closure}}
  10: std::sync::once::Once::call_inner
             at libstd/sync/once.rs:349
  11: bindgen::Builder::generate
  12: build_script_build::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  17: main
  18: __libc_start_main
  19: <unknown>

[kargakis@localhost grin]$ ls /usr/lib64/clang-private/
libclangAnalysis.so           libclangCodeGen.so.5                 libclangFrontend.so.5.0.0         libclangRewrite.so                       libclangStaticAnalyzerCore.so.5
libclangAnalysis.so.5         libclangCodeGen.so.5.0.0             libclangFrontendTool.so           libclangRewrite.so.5                     libclangStaticAnalyzerCore.so.5.0.0
libclangAnalysis.so.5.0.0     libclangDriver.so                    libclangFrontendTool.so.5         libclangRewrite.so.5.0.0                 libclangStaticAnalyzerFrontend.so
libclangARCMigrate.so         libclangDriver.so.5                  libclangFrontendTool.so.5.0.0     libclangSema.so                          libclangStaticAnalyzerFrontend.so.5
libclangARCMigrate.so.5       libclangDriver.so.5.0.0              libclangIndex.so                  libclangSema.so.5                        libclangStaticAnalyzerFrontend.so.5.0.0
libclangARCMigrate.so.5.0.0   libclangDynamicASTMatchers.so        libclangIndex.so.5                libclangSema.so.5.0.0                    libclangToolingCore.so
libclangASTMatchers.so        libclangDynamicASTMatchers.so.5      libclangIndex.so.5.0.0            libclangSerialization.so                 libclangToolingCore.so.5
libclangASTMatchers.so.5      libclangDynamicASTMatchers.so.5.0.0  libclangLex.so                    libclangSerialization.so.5               libclangToolingCore.so.5.0.0
libclangASTMatchers.so.5.0.0  libclangEdit.so                      libclangLex.so.5                  libclangSerialization.so.5.0.0           libclangToolingRefactor.so
libclangAST.so                libclangEdit.so.5                    libclangLex.so.5.0.0              libclang.so                              libclangToolingRefactor.so.5
libclangAST.so.5              libclangEdit.so.5.0.0                libclangParse.so                  libclang.so.5                            libclangToolingRefactor.so.5.0.0
libclangAST.so.5.0.0          libclangFormat.so                    libclangParse.so.5                libclang.so.5.0                          libclangTooling.so
libclangBasic.so              libclangFormat.so.5                  libclangParse.so.5.0.0            libclangStaticAnalyzerCheckers.so        libclangTooling.so.5
libclangBasic.so.5            libclangFormat.so.5.0.0              libclangRewriteFrontend.so        libclangStaticAnalyzerCheckers.so.5      libclangTooling.so.5.0.0
libclangBasic.so.5.0.0        libclangFrontend.so                  libclangRewriteFrontend.so.5      libclangStaticAnalyzerCheckers.so.5.0.0
libclangCodeGen.so            libclangFrontend.so.5                libclangRewriteFrontend.so.5.0.0  libclangStaticAnalyzerCore.so
```

**Comment by ignopeverell** [comment]
Please check the instructions here:

https://github.com/KyleMayes/clang-sys

**Comment by kargakis** [comment]
Thanks for the link will try to go through it and once I am done and this is still an issue, I will reopen.
