### ISSUE TITLE
tui showing a panic...

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#1834]
Node running on latest master (deployed and restarted ~12 hours ago).

```
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│Grin Version 0.4.0                                                                                                                                                                      │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌──────────────────┐┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│Basic Status      ││                                                                                                                                                                    │
│Peers and Sync    ││ Current Status: Running                                                                                                                                            │
│Mining            ││ Connected Peers: 16                                                                                                                                                │
│Version Info      ││ ------------------------                                                                                                                                           │
│                  ││ Header Chain Height: 10184                                                                                                                                         │
│                  ││ Header Cumulative Difficulty: 303926730                                                                                                                            │
│                  ││ ------------------------                                                                                                                                           │
│                  ││ Chain Height: 10184                                                                                                                                                │
│                  ││ Cumulative Difficulty: 303926730                                                                                                                                   │
│                  ││ ------------------------                                                                                                                                           │
│                  ││                                                                                                                                                                    │
│                  ││                                                                                                                                                                    │
│                  ││   Thread 'p2p-server' panicked with message:                                                                                                                       │
│                  ││                                             "index out of bounds: the len is 1 but the index is 1"                                                                 │
│                  ││                                                                                                   See /grin/node1/grin-server.log for further details.             │
│                  ││                                                                                                                                                                    │
│------------------││                                                                                                                                                                    │
│Tab/Arrow : Cycle ││                                                                                                                                                                    │
│Enter     : Select││                                                                                                                                                                    │
│Q         : Quit  ││                                                                                                                                                                    │
└──────────────────┘└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

**Comment by antiochp** [comment]
```
Oct 20 06:37:18.840 ERRO
thread 'p2p-server' panicked at 'index out of bounds: the len is 1 but the index is 1': /checkout/src/libcore/slice/mod.rs:2085stack backtrace:
   0:     0x55fdb63d9e8c - backtrace::backtrace::trace::h272577bfc2626f7d
   1:     0x55fdb63d9c42 - <backtrace::capture::Backtrace as core::default::Default>::default::h5424c6e0dc8dba7e
   2:     0x55fdb63d9cb8 - backtrace::capture::Backtrace::new::h942c8e16ca0eb93f
   3:     0x55fdb6371d0e - grin_util::logger::send_panic_to_log::{{closure}}::ha24ba54226de3517
   4:     0x55fdb64e8863 - std::panicking::rust_panic_with_hook::hcee6c3e2546f0536
                        at libstd/panicking.rs:479
   5:     0x55fdb64e8409 - std::panicking::continue_panic_fmt::h4eabd8b3f6ed92ef
                        at libstd/panicking.rs:390
   6:     0x55fdb64e8305 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55fdb65437eb - core::panicking::panic_fmt::he96889401c792f2b
                        at libcore/panicking.rs:77
   8:     0x55fdb654379f - core::panicking::panic_bounds_check::hd8121da93ba8d162
                        at libcore/panicking.rs:59
   9:     0x55fdb62330f5 - <grin_p2p::msg::SockAddr as grin_core::ser::Readable>::read::h446b05553c68f048
  10:     0x55fdb6230d07 - <grin_p2p::msg::Hand as grin_core::ser::Readable>::read::h452b6ed3072c014f
  11:     0x55fdb622eb74 - grin_p2p::msg::read_message::h6ef511849d19626c
  12:     0x55fdb620adc3 - grin_p2p::handshake::Handshake::accept::hafa3b3a92f01361a
  13:     0x55fdb6201a51 - grin_p2p::peer::Peer::accept::h90b2343b8722667a
  14:     0x55fdb6229fc8 - grin_p2p::serv::Server::listen::h9a5a4fcb71504f9a
  15:     0x55fdb5eb65b5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5adba401f079fdbe
  16:     0x55fdb5ed8944 - std::panicking::try::do_call::h72fa9a8f8cc6e0d6
  17:     0x55fdb650cd29 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  18:     0x55fdb5ee51de - <F as alloc::boxed::FnBox<A>>::call_box::he9c1efd471410aaf
  19:     0x55fdb64eadfa - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h4fe25736d1ad023e
                        at /checkout/src/liballoc/boxed.rs:652
                         - std::sys_common::thread::start_thread::h724c65d574104979
                        at libstd/sys_common/thread.rs:24
  20:     0x55fdb64e8d75 - std::sys::unix::thread::Thread::new::thread_start::hbcaf0e9db87ae467
                        at libstd/sys/unix/thread.rs:90
  21:     0x7f5a0f2bf6b9 - start_thread
  22:     0x7f5a0eddf41c - clone
  23:                0x0 - <unknown>
```

**Comment by eupn** [comment]
Will tackle on it. Probably regression from one of mine #1789 or #1815.

**Comment by antiochp** [comment]
This line jumps out - 
```
   9:     0x55fdb62330f5 - <grin_p2p::msg::SockAddr as grin_core::ser::Readable>::read::h446b05553c68f048
```

There was a conversation on gitter yesterday about testing against ipv6?

Maybe related.

**Comment by eupn** [comment]
>Maybe related

I've been fixed the panic-when-in-tui part of this issue. TBH I know about cause of panic.
