### ISSUE TITLE
Failure to start when "archive_mode = true"

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#1877]
Note that the crash may be caused by an external service calling the API requesting low numbered blocks which are not available due to  #1809

```
2018-10-29T19:00:06.704243313+00:00 ERROR grin_util::logger - 
thread 'sync' panicked at 'index out of bounds: the len is 0 but the index is 0': /checkout/src/libcore/slice/mod.rs:2085stack backtrace:
   0:     0x5624906e288c - backtrace::backtrace::trace::h0d480c688c6e5983
   1:     0x5624906e2642 - <backtrace::capture::Backtrace as core::default::Default>::default::hbf23cd498c62c039
   2:     0x5624906e26b8 - backtrace::capture::Backtrace::new::hb00f34110e8fb8d2
   3:     0x56249067168e - grin_util::logger::send_panic_to_log::{{closure}}::h18715ddb0d691e90
   4:     0x5624907f1573 - std::panicking::rust_panic_with_hook::h542dacac3f3a20d8
                        at libstd/panicking.rs:479
   5:     0x5624907f10d9 - std::panicking::continue_panic_fmt::hd989cd729c0c5a4b
                        at libstd/panicking.rs:390
   6:     0x5624907f0fd5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x56249084c2eb - core::panicking::panic_fmt::h26b7cf0675909ac6
                        at libcore/panicking.rs:77
   8:     0x56249084c29f - core::panicking::panic_bounds_check::hb7240398d20f0b17
                        at libcore/panicking.rs:59
   9:     0x5624901ac8cf - grin_servers::grin::sync::syncer::SyncRunner::sync_loop::hf4626aafea7e7c92
  10:     0x56249022d5ac - std::sys_common::backtrace::__rust_begin_short_backtrace::hbd4df521220b4e03
  11:     0x5624901d6c1b - std::panicking::try::do_call::h118ed84ab714dccd
  12:     0x562490815879 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  13:     0x5624901ed1aa - <F as alloc::boxed::FnBox<A>>::call_box::h470dd4784264ebd2
  14:     0x5624907f3aea - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9a3d5ac4c96bb201
                        at /checkout/src/liballoc/boxed.rs:652
                         - std::sys_common::thread::start_thread::h24226b876494ff77
                        at libstd/sys_common/thread.rs:24
  15:     0x5624907f1a85 - std::sys::unix::thread::Thread::new::thread_start::h0aab6afcd022cdd8
                        at libstd/sys/unix/thread.rs:90
  16:     0x7fc7734fe493 - start_thread
  17:     0x7fc773029ace - __clone
  18:                0x0 - <unknown>


Thread 'sync' panicked with message:
"index out of bounds: the len is 0 but the index is 0"
```

**Comment by bladedoyle** [comment]
Old issue was fixed at some point along the way....all good now.
