### ISSUE TITLE
Crash when doing grin wallet init second time

### ISSUE THREAD

**Issue by illera88** [mimblewimble/grin#2020]
To reproduce just do `grin wallet init` two times. The second one it panics:

```
user@instance-1:~/grin$ ./target/release/grin wallet init
Please enter a password for your new wallet
Password:
Confirm Password:
20181125 23:09:08.441 WARN grin_wallet::types - Generating wallet seed file at: /home/user/.grin/wallet_data/wallet.seed
Your recovery phrase is:
[redacted]
Please back-up these words in a non-digital format.
user@instance-1:~/grin$ screen -r grin_node
                        at libstd/panicking.rs:481
   5:     0x561e14586259 - std::panicking::continue_panic_fmt::h2d2d2bfb065a70b2
                        at libstd/panicking.rs:391
   6:     0x561e14586155 - rust_begin_unwind
                        at libstd/panicking.rs:326
   7:     0x561e145e245b - core::panicking::panic_fmt::h2155aa66b67fe83c
                        at libcore/panicking.rs:77
   8:     0x561e13d835b8 - core::result::unwrap_failed::h79846a1c4a7a70e5
   9:     0x561e13e0ba7d - grin::real_main::h400924db3933ad72
  10:     0x561e13e055d5 - grin::main::h528ac062e526aa0c
  11:     0x561e13d88952 - std::rt::lang_start::{{closure}}::ha951655b798225dc
  12:     0x561e145860f2 - std::rt::lang_start_internal::{{closure}}::hf358dd5cfeb0e6cb
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h47665672c57b11e4
                        at libstd/panicking.rs:310
  13:     0x561e145ab699 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  14:     0x561e14591425 - std::panicking::try::h8475f4f88883fab0
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::hf17f60e34fd385b1
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::had9505969b8e20a2
                        at libstd/rt.rs:58
  15:     0x561e13e0d2a3 - main
  16:     0x7fa78c62b2e0 - __libc_start_main
  17:     0x561e13d4fa69 - _start
  18:                0x0 - <unknown>


Thread 'main' panicked with message:
"Failed to init wallet seed file.: Error { inner:

Wallet seed exists error }"
See /home/user/.grin/grin-wallet.log for further details.
user@instance-1:~/grin$ cat /home/user/.grin/grin-wallet.log
20181126 03:12:12.603 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug
20181126 03:12:12.603 INFO grin - Using wallet configuration file at /home/user/.grin/grin-wallet.toml
20181126 03:12:12.603 INFO grin - This is Grin version 0.4.1 (git 0.4.0-134-g1ea82d9), built for x86_64-unknown-linux-gnu by rustc 1.30.1 (1433507eb 2018-11-07).
20181126 03:12:12.603 DEBUG grin - Built with profile "release", features "".
20181126 03:12:17.639 WARN grin_wallet::types - Generating wallet seed file at: /home/user/.grin/wallet_data/wallet.seed
20181126 03:12:17.642 INFO grin::cmd::wallet - Wallet seed file created
20181126 03:12:17.648 INFO grin::cmd::wallet - Wallet database backend created
20181126 03:12:23.479 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug
20181126 03:12:23.479 INFO grin - Using wallet configuration file at /home/user/.grin/grin-wallet.toml
20181126 03:12:23.479 INFO grin - This is Grin version 0.4.1 (git 0.4.0-134-g1ea82d9), built for x86_64-unknown-linux-gnu by rustc 1.30.1 (1433507eb 2018-11-07).
20181126 03:12:23.479 DEBUG grin - Built with profile "release", features "".
20181126 03:12:28.311 WARN grin_wallet::types - Generating wallet seed file at: /home/user/.grin/wallet_data/wallet.seed
20181126 03:12:28.331 ERROR grin_util::logger -
thread 'main' panicked at 'Failed to init wallet seed file.: Error { inner:

Wallet seed exists error }': libcore/result.rs:1009stack backtrace:
   0:     0x561e1447462c - backtrace::backtrace::trace::h342407aacfccaa6d
   1:     0x561e144738a2 - <backtrace::capture::Backtrace as core::default::Default>::default::h37593dc9d5a9f86d
   2:     0x561e14473918 - backtrace::capture::Backtrace::new::ha2a3d34ce8fdbf26
   3:     0x561e144014df - grin_util::logger::send_panic_to_log::{{closure}}::hf1fe78813a52192f
   4:     0x561e145866f3 - std::panicking::rust_panic_with_hook::h86e619a638415243
                        at libstd/panicking.rs:481
   5:     0x561e14586259 - std::panicking::continue_panic_fmt::h2d2d2bfb065a70b2
                        at libstd/panicking.rs:391
   6:     0x561e14586155 - rust_begin_unwind
                        at libstd/panicking.rs:326
   7:     0x561e145e245b - core::panicking::panic_fmt::h2155aa66b67fe83c
                        at libcore/panicking.rs:77
   8:     0x561e13d835b8 - core::result::unwrap_failed::h79846a1c4a7a70e5
   9:     0x561e13e0ba7d - grin::real_main::h400924db3933ad72
  10:     0x561e13e055d5 - grin::main::h528ac062e526aa0c
  11:     0x561e13d88952 - std::rt::lang_start::{{closure}}::ha951655b798225dc
  12:     0x561e145860f2 - std::rt::lang_start_internal::{{closure}}::hf358dd5cfeb0e6cb
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h47665672c57b11e4
                        at libstd/panicking.rs:310
  13:     0x561e145ab699 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  14:     0x561e14591425 - std::panicking::try::h8475f4f88883fab0
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::hf17f60e34fd385b1
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::had9505969b8e20a2
                        at libstd/rt.rs:58
  15:     0x561e13e0d2a3 - main
  16:     0x7fa78c62b2e0 - __libc_start_main
  17:     0x561e13d4fa69 - _start
  18:                0x0 - <unknown>

```

**Comment by yeastplume** [comment]
Thanks for reporting! Not actually a crash, just a lot more output than is necessary to tell you the wallet isn't going to init a wallet because it would overwrite an existing seed file. Changed in #2021 to make the error output less scary looking.
