### ISSUE TITLE
LmdbErr(Error::Code(11, 'Resource temporarily unavailable'))

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2041]
I see the following failure in "grin wallet send" intermittently (ya, I know, sorry).  
I can get more logs to confirm, but it looks a bit like a coinbase is being built at the same time, so maybe that process legitimately has the db locked?  Should the second process wait and/or retry a little bit before failing?  A default 5 second wait would probably help a lot.

```
20181129 00:56:12.490 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 0, height: 59860, key_id: Some(Identifier(0300000000000000000000018e00000000)) }
20181129 00:56:57.477 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed
20181129 00:56:57.518 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000018e00000000), 0300000000000000000000018e00000000
20181129 00:56:57.519 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 0, height: 59861, key_id: Some(Identifier(0300000000000000000000018e00000000)) } 
20181129 00:57:37.658 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed 
20181129 00:57:37.683 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000018e00000000), 0300000000000000000000018e00000000 
20181129 00:57:37.683 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 8000000, height: 59862, key_id: Some(Identifier(0300000000000000000000018e00000000)) } 
20181129 01:00:16.923 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Debug, min. level: Debug 
20181129 01:00:16.923 INFO grin - Using wallet configuration file at /wallet/grin-wallet.toml 
20181129 01:00:16.923 INFO grin - This is Grin version 0.4.1 (git 0.4.0-134-g1ea82d9), built for x86_64-unknown-linux-gnu by rustc 1.30.1 (1433507eb 2018-11-07). 
20181129 01:00:16.923 DEBUG grin - Built with profile "release", features "". 
20181129 01:00:16.924 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed 
20181129 01:00:16.953 ERROR grin_util::logger -  
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LmdbErr(Error::Code(11, 'Resource temporarily unavailable'))': libcore/result.rs:1009stack backtrace: 
   0:     0x556d81dc962c - backtrace::backtrace::trace::h342407aacfccaa6d 
   1:     0x556d81dc88a2 - <backtrace::capture::Backtrace as core::default::Default>::default::h37593dc9d5a9f86d 
   2:     0x556d81dc8918 - backtrace::capture::Backtrace::new::ha2a3d34ce8fdbf26 
   3:     0x556d81d564df - grin_util::logger::send_panic_to_log::{{closure}}::hf1fe78813a52192f 
   4:     0x556d81edafe3 - std::panicking::rust_panic_with_hook::h86e619a638415243 
                        at libstd/panicking.rs:481 
   5:     0x556d81edab49 - std::panicking::continue_panic_fmt::h2d2d2bfb065a70b2 
                        at libstd/panicking.rs:391 
   6:     0x556d81edaa45 - rust_begin_unwind 
                        at libstd/panicking.rs:326 
   7:     0x556d81f36d4b - core::panicking::panic_fmt::h2155aa66b67fe83c 
                        at libcore/panicking.rs:77 
   8:     0x556d818fecf8 - core::result::unwrap_failed::h4cb13a052906581a 
   9:     0x556d819122ed - <grin_wallet::lmdb_wallet::LMDBBackend<C, K> as grin_wallet::libwallet::types::WalletBackend<C, K>>::set_parent_key_id_by_name::hcb71e44e8810b200 
  10:     0x556d818f6fac - grin_wallet::instantiate_wallet::h48829e0d8d23a017 
  11:     0x556d81760245 - grin::real_main::h400924db3933ad72 
  12:     0x556d8175a5d5 - grin::main::h528ac062e526aa0c 
  13:     0x556d816dd952 - std::rt::lang_start::{{closure}}::ha951655b798225dc 
  14:     0x556d81eda9e2 - std::rt::lang_start_internal::{{closure}}::hf358dd5cfeb0e6cb 
                        at libstd/rt.rs:59 
                         - std::panicking::try::do_call::h47665672c57b11e4 
                        at libstd/panicking.rs:310 
  15:     0x556d81efff89 - __rust_maybe_catch_panic 
                        at libpanic_unwind/lib.rs:103 
  16:     0x556d81ee5d15 - std::panicking::try::h8475f4f88883fab0 
                        at libstd/panicking.rs:289 
                         - std::panic::catch_unwind::hf17f60e34fd385b1 
                        at libstd/panic.rs:392 
                         - std::rt::lang_start_internal::had9505969b8e20a2 
                        at libstd/rt.rs:58 
  17:     0x556d817622a3 - main 
  18:     0x7f2e9a34a2e0 - __libc_start_main 
  19:     0x556d816a4a69 - _start 
  20:                0x0 - <unknown> 
 
 
20181129 01:00:37.058 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed 
20181129 01:00:37.096 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000018e00000000), 0300000000000000000000018e00000000 
20181129 01:00:37.097 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 8000000, height: 59862, key_id: Some(Identifier(0300000000000000000000018e00000000)) } 
20181129 01:00:48.587 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed 
20181129 01:00:48.658 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000018e00000000), 0300000000000000000000018e00000000 
20181129 01:00:48.658 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 0, height: 59863, key_id: Some(Identifier(0300000000000000000000018e00000000)) } 
20181129 01:00:57.195 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed 
20181129 01:00:57.232 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000018e00000000), 0300000000000000000000018e00000000 
20181129 01:00:57.232 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 0, height: 59864, key_id: Some(Identifier(0300000000000000000000018e00000000)) } 
20181129 01:03:57.035 DEBUG grin_wallet::types - Using wallet seed file at: /wallet/wallet_data/wallet.seed 
20181129 01:03:57.091 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: built candidate output - Identifier(0300000000000000000000018e00000000), 0300000000000000000000018e00000000 
20181129 01:03:57.091 DEBUG grin_wallet::libwallet::internal::updater - receive_coinbase: BlockFees { fees: 14000000, height: 59864, key_id: Some(Identifier(0300000000000000000000018e00000000)) }
-- VISUAL --                                                                                                            59        15217,196     99%

```

**Comment by yeastplume** [comment]
I think we need to stress-test the wallet a bit more to uncover these types of errors. Will see if I can get this reproduced in an automated fashion (though most likely not this week)
