### ISSUE TITLE
No root, invalid tree

### ISSUE THREAD

**Issue by garyyu** [mimblewimble/grin#2236]
Just do a `kill` and restart the grin, then it reports `Thread 'main' panicked with message:"no root, invalid tree"`. The graceful exit on kill seems still doesn't work.
```
20181227 01:01:05.824 WARN grin::cmd::server - Starting GRIN w/o UI...
20181227 01:01:05.825 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20181227 01:01:05.825 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20181227 01:01:05.826 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20181227 01:01:05.826 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20181227 01:01:05.826 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20181227 01:01:05.826 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20181227 01:01:05.826 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20181227 01:01:05.826 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20181227 01:01:05.848 ERROR grin_util::logger - 
thread 'main' panicked at 'no root, invalid tree': libcore/option.rs:1008stack backtrace:
   0:     0x5615e6bc099d - backtrace::backtrace::trace::h33a8de1a5de4f598
   1:     0x5615e6bbfbb2 - <backtrace::capture::Backtrace as core::default::Default>::default::h13bf884e561085be
   2:     0x5615e6bbfc29 - backtrace::capture::Backtrace::new::h810796244ae4b8f2
   3:     0x5615e6b4ad40 - grin_util::logger::send_panic_to_log::{{closure}}::h558ad3b25f069faa
   4:     0x5615e6c91cb6 - std::panicking::rust_panic_with_hook::h71214e7ce0f7ac01
                        at libstd/panicking.rs:480
   5:     0x5615e6c91801 - std::panicking::continue_panic_fmt::ha8b8442f4ea9bcac
                        at libstd/panicking.rs:390
   6:     0x5615e6c916e5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x5615e6cdb18c - core::panicking::panic_fmt::h0c93626b89c38af6
                        at libcore/panicking.rs:77
   8:     0x5615e6cdb202 - core::option::expect_failed::h143b3841283cabae
                        at libcore/option.rs:1008
   9:     0x5615e6ac9945 - <grin_core::core::pmmr::pmmr::PMMR<'a, T, B>>::root::h6852c267d7f1e71c
  10:     0x5615e6a7f8fc - grin_chain::txhashset::txhashset::Extension::validate_roots::hef93822142411134
  11:     0x5615e6a7193f - grin_chain::txhashset::txhashset::extending::h6dcd51d5a854f7d1
  12:     0x5615e6a89431 - grin_chain::chain::Chain::init::h097e53a2df99e3d6
  13:     0x5615e65fe79b - grin_servers::grin::server::Server::new::ha7a07993077ed3c4
  14:     0x5615e647f02d - grin::cmd::server::start_server::h8c8ee893084e365c
  15:     0x5615e6480948 - grin::cmd::server::server_command::hd1c5bc30d596419c
  16:     0x5615e645520c - grin::real_main::hfd4b822ff7fb6970
  17:     0x5615e64539d5 - grin::main::h17cba8e3f79dc686
  18:     0x5615e6405ea2 - std::rt::lang_start::{{closure}}::h2a83ee9f05dfcbdd
  19:     0x5615e6c91682 - std::rt::lang_start_internal::{{closure}}::hfa55fa3abac97f1c
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hbafbcad10c689c73
                        at libstd/panicking.rs:310
  20:     0x5615e6ca40b9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  21:     0x5615e6c72d2a - std::panicking::try::hcad0d43659dae567
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h87a4b99f7a6774fd
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::hbcd5a990678800b9
                        at libstd/rt.rs:58
  22:     0x5615e6455864 - main
  23:     0x7f75bad802e0 - __libc_start_main
  24:     0x5615e63b5309 - _start
  25:                0x0 - <unknown>
```

**Comment by garyyu** [comment]
Closed. No more happening on mainnet release 1.0.0.
