### ISSUE TITLE
Panic when trying to receive coins

### ISSUE THREAD

**Issue by bitcoal** [mimblewimble/grin#2281]
got a slate file from mining pool, tried to receive it with `./grin --floonet wallet receive -i ~/txgrin.txt` and get this crash
```
20190102 20:42:02.847 ERROR grin_util::logger -
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:     0x55ebf637ca0d - backtrace::backtrace::trace::hd74837959dc31a2c
   1:     0x55ebf637bc22 - <backtrace::capture::Backtrace as core::default::Default>::default::hfbe03539066da14f
   2:     0x55ebf637bc99 - backtrace::capture::Backtrace::new::hd9d47426559d8b68
   3:     0x55ebf6305330 - grin_util::logger::send_panic_to_log::{{closure}}::h1adee8cd5ece5439
   4:     0x55ebf644d9a6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x55ebf644d4f1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x55ebf644d3d5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x55ebf6496e7c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x55ebf6496dab - core::panicking::panic::hca17aeb7dac42859
                        at libcore/panicking.rs:52
   9:     0x55ebf62d36e2 - grin_core::libtx::slate::Slate::verify_messages::haa9724b8f689266d
  10:     0x55ebf5b99276 - <grin_wallet::libwallet::api::APIOwner<W, C, K>>::verify_slate_messages::h9f577ae78759a476
  11:     0x55ebf5ba1068 - <grin_wallet::libwallet::api::APIForeign<W, C, K>>::verify_slate_messages::hbc47a72c209353f2
  12:     0x55ebf5c2fbb8 - grin_wallet::controller::foreign_single_use::he7bad7e7fa27f7f4
  13:     0x55ebf5c0c1d5 - grin::cmd::wallet_args::wallet_command::hd2295906797b6364
  14:     0x55ebf5c3d9d0 - grin::cmd::wallet::wallet_command::h46b76402d5018eb1
  15:     0x55ebf5bd8c8b - grin::real_main::hc558932e4f6ae27f
  16:     0x55ebf5bd7705 - grin::main::hf1592a3c4bf1d517
  17:     0x55ebf5bd02a2 - std::rt::lang_start::{{closure}}::hb15ae5b8955fe47f
  18:     0x55ebf644d372 - std::rt::lang_start_internal::{{closure}}::hafa8ecdacd368ebb
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h8c0dbb48abbdf4df
                        at libstd/panicking.rs:310
  19:     0x55ebf645fb29 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  20:     0x55ebf642e9fa - std::panicking::try::hbc21637ba5f64d73
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h954917b922b8d970
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::h5b2de3cc38c3b406
                        at libstd/rt.rs:58
  21:     0x55ebf5bd9a44 - main
  22:     0x7f8ed3e9282f - __libc_start_main
  23:     0x55ebf5b6a5b8 - _start
  24:                0x0 - <unknown>


Thread 'main' panicked with message:
"called `Option::unwrap()` on a `None` value"
```

**Comment by sesam** [comment]
What grin version? Have you tried building from source latest master?

Thread 'main' panicked with message:
>
> "called `Option::unwrap()` on a `None` value
>
>

**Comment by bitcoal** [comment]
v0.5.0
have also tried the latest master and the same exact issue is happening.

**Comment by hashmap** [comment]
@bitcoal could you share `~/txgrin.txt`? It seems that it contains a message but a signature is missing.

**Comment by bitcoal** [comment]
OK so now it fails with "participant message doesn't have signature", how do we get the send command to create a signature?  As is it is not even possible to transfer grin using files.

**Comment by hashmap** [comment]
It’s totally possible, you experience a bug in grinmint.com poll, which produces an incomplete file. Afaik this bug should be fixed soon by the pool devs.

**Comment by bitcoal** [comment]
I also tried using the receive_tx api myself and ran into the same issue.
Steps to reproduce:
1. use cli wallet to generate a send file
2. use receive_tx api to process the send file
3. try to use the finalize cli command on the result of step 2: "participant message doesn't have signature."

**Comment by mcdallas** [comment]
it works fine for me

> mike@mike-VirtualBox:\~$ gw send -s smallest -m file -d /tmp/tx2.json 0.1
> Command 'send' completed successfully
> mike@mike-VirtualBox:\~$ gw receive -i /tmp/tx2.json
> Command 'receive' completed successfully
> mike@mike-VirtualBox:\~$ gw finalize -i /tmp/tx2.json.response
> Command 'finalize' completed successfully
>
