### ISSUE TITLE
Crash when running grin server

### ISSUE THREAD

**Issue by fbafelipe** [mimblewimble/grin#2292]
Running on a server thru SSH.
With run_tui=true it just crashes without any messages.
With run_tui=false it dumps this stack trace:

```
$ grin --floonet
20190105 15:41:40.224 WARN grin::cmd::server - Starting GRIN w/o UI...
20190105 15:41:40.293 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })': libcore/result.rs:1009stack backtrace:
   0:     0x56407a68b68d - backtrace::backtrace::trace::hd74837959dc31a2c
   1:     0x56407a68a8a2 - <backtrace::capture::Backtrace as core::default::Default>::default::hfbe03539066da14f
   2:     0x56407a68a919 - backtrace::capture::Backtrace::new::hd9d47426559d8b68
   3:     0x56407a613ca0 - grin_util::logger::send_panic_to_log::{{closure}}::h1adee8cd5ece5439
   4:     0x56407a75c2e6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x56407a75be31 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x56407a75bd15 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x56407a7a57bc - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x564079ece0b9 - core::result::unwrap_failed::h68a1465f5f7f3e96
   9:     0x564079f48030 - grin::cmd::server::start_server::h8986bd05df8d2a48
  10:     0x564079f48c48 - grin::cmd::server::server_command::hef427aa69bd96057
  11:     0x564079ee48d6 - grin::real_main::hc558932e4f6ae27f
  12:     0x564079ee32b5 - grin::main::hf1592a3c4bf1d517
  13:     0x564079edbe22 - std::rt::lang_start::{{closure}}::hb15ae5b8955fe47f
  14:     0x56407a75bcb2 - std::rt::lang_start_internal::{{closure}}::hafa8ecdacd368ebb
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h8c0dbb48abbdf4df
                        at libstd/panicking.rs:310
  15:     0x56407a76e469 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  16:     0x56407a73d33a - std::panicking::try::hbc21637ba5f64d73
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h954917b922b8d970
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::h5b2de3cc38c3b406
                        at libstd/rt.rs:58
  17:     0x564079ee55f4 - main
  18:     0x7f8919744b96 - __libc_start_main
  19:     0x564079e76140 - <unknown>
  20:                0x0 - <unknown>


Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })"
See /home/grin-testnet/.grin/floo/grin-server.log for further details.
```

**Comment by sesam** [comment]
Right, the error message is a bit hidden. There's a problem with your chain_data. Did you previously sync using an older version?

To fix, did you try to stop grin, remove the whole ~/.grin/floo/chain_data folder, then restart grin?

I think you already found it, but anyway, feel welcome to the support chat https://gitter.im/grin_community/support

I think we already have some tickets about improving error messages. So if you no longer need this ticket open, please close this ticket.

**Comment by fbafelipe** [comment]
I found the problem: I didn't had the ncurses lib installed.
Better error messages would really help but since there is an issue for this already, I'm closing this issue.

**Comment by damntoken** [comment]
What exactly was the dependency? There are lots of *ncurses* packages for Ubuntu.

**Comment by fbafelipe** [comment]
I am not sure which. I just installed all ncurses packages and then it worked.
