### ISSUE TITLE
Regression - "not yet implmented" error while creating a file-based tx

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin#2293]
```
20190105 18:54:52.144 DEBUG grin_wallet::libwallet::internal::selection - Building change outputs: total change: 59135656583 (1 outputs)
20190105 18:54:52.181 DEBUG grin_core::libtx::build - Building output: 59135656583, Commitment(09545e175b9258a3c7f992068eadbbb0ad3ab60b2fc87a4a2ddca3b174c875064b)
20190105 18:54:52.282 INFO grin_wallet::controller - Tx created: 182.567807479 grin to 3-api.tx (strategy 'false')
20190105 18:54:52.351 ERROR grin_util::logger - 
thread 'tokio-runtime-worker-0' panicked at 'not yet implemented': wallet/src/adapters/file.rs:41stack backtrace:
   0:     0x55b2a380473d - backtrace::backtrace::trace::h33a8de1a5de4f598
   1:     0x55b2a3803952 - <backtrace::capture::Backtrace as core::default::Default>::default::h13bf884e561085be
   2:     0x55b2a38039c9 - backtrace::capture::Backtrace::new::h810796244ae4b8f2
   3:     0x55b2a378ee90 - grin_util::logger::send_panic_to_log::{{closure}}::ha93bb4f95c14c6f1
   4:     0x55b2a38d5856 - std::panicking::rust_panic_with_hook::h71214e7ce0f7ac01
                        at libstd/panicking.rs:480
   5:     0x55b2a32731a7 - std::panicking::begin_panic::hfbc0507942b3377f
   6:     0x55b2a32f0648 - <grin_wallet::adapters::file::FileWalletCommAdapter as grin_wallet::adapters::WalletCommAdapter>::send_tx_sync::hd1fc46f714458e43
   7:     0x55b2a3061dae - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h8746d722a02bf2fa
   8:     0x55b2a305d386 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h276b58e384a24f6e
   9:     0x55b2a307413f - <futures::future::chain::Chain<A, B, C>>::poll::h85951daafc5fa371
  10:     0x55b2a30f6778 - <futures::future::or_else::OrElse<A, B, F> as futures::future::Future>::poll::h88b8e395ed818cb0
  11:     0x55b2a3451b9d - <hyper::proto::h1::dispatch::Server<S> as hyper::proto::h1::dispatch::Dispatch>::poll_msg::h46cfe2a835a14dc8
  12:     0x55b2a3464e85 - <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, T>>::poll_catch::haf12cb31706f9f18
  13:     0x55b2a344d65c - <futures::future::either::Either<A, B> as futures::future::Future>::poll::had608da4a693608f
  14:     0x55b2a33ee386 - <hyper::server::conn::upgrades::UpgradeableConnection<I, S, E> as futures::future::Future>::poll::hd6c3959a4b8153fe
  15:     0x55b2a34674da - <hyper::server::conn::spawn_all::NewSvcTask<I, N, S, E, W> as futures::future::Future>::poll::h07267b739c6fce78
  16:     0x55b2a35fda61 - futures::task_impl::std::set::h9750f6740044cf9f
  17:     0x55b2a35fe665 - <futures::task_impl::Spawn<T>>::poll_future_notify::h1f8c2c83c5b46304
  18:     0x55b2a3601e70 - std::panicking::try::do_call::hc5971f1473933bba
  19:     0x55b2a38e7b79 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  20:     0x55b2a35ffecb - tokio_threadpool::task::Task::run::h3da35c26de54bb9d
  21:     0x55b2a35f8485 - tokio_threadpool::worker::Worker::run_task::ha0c8340706fb866e
  22:     0x55b2a35f791d - tokio_threadpool::worker::Worker::run::h423d99f6db966bac
  23:     0x55b2a35e2a85 - <std::thread::local::LocalKey<T>>::with::h36e781790fc8931b
  24:     0x55b2a35e2bb1 - <std::thread::local::LocalKey<T>>::with::h3f2370a0fdf06420
  25:     0x55b2a35e2db8 - <std::thread::local::LocalKey<T>>::with::h58ecb1caddb8775f
  26:     0x55b2a35df195 - tokio::runtime::builder::Builder::build::{{closure}}::he8445362c1aba70d
  27:     0x55b2a35ff19c - <std::thread::local::LocalKey<T>>::with::h0f4daf8fe3d3fea3
  28:     0x55b2a35ff421 - <std::thread::local::LocalKey<T>>::with::h65b5f48673fced4e
  29:     0x55b2a36027db - std::sys_common::backtrace::__rust_begin_short_backtrace::h35e2674631627600
  30:     0x55b2a3601ebb - std::panicking::try::do_call::heffdc335a7c397fa
  31:     0x55b2a38e7b79 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  32:     0x55b2a35fc91f - <F as alloc::boxed::FnBox<A>>::call_box::h445fe7e31f914b6e
  33:     0x55b2a38d1ddd - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::he3acfc8f1203786f
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h5213f803a61d7811
                        at libstd/sys_common/thread.rs:24
  34:     0x55b2a38bcec5 - std::sys::unix::thread::Thread::new::thread_start::he89121f566d2a8c7
                        at libstd/sys/unix/thread.rs:90
  35:     0x7fae7f7c8493 - start_thread
  36:     0x7fae7f2f3ace - __clone
  37:                0x0 - <unknown>
```

**Comment by mcdallas** [comment]
https://github.com/mimblewimble/grin/blob/16878dc6a29fc713f3edbe4d974fcf0017bd600d/wallet/src/controller.rs#L357

This should be async in the case of "file". Was replaced in #2280

**Comment by garyyu** [comment]
Thank you for this finding and a quick fix, and sorry for the regression, I must remind myself to test all cases! (I was lazy and only tested `http` and `keybase` method before merging #2280). Just realized now there's a different send_tx there :(
