### ISSUE TITLE
panic in out of range for slice (immediately after restarting a node)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#235]
https://gist.github.com/antiochp/a20291ec4718d6199854f2a06b138a0a

```
thread 'main' panicked at 'index 369980 out of range for slice of length 369330', /checkout/src/libcore/slice/mod.rs:748:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice/mod.rs:748
  10: grin_store::sumtree::AppendOnlyFile::read
  11: <grin_store::sumtree::PMMRBackend<T> as grin_core::core::pmmr::Backend<T>>::get
  12: <grin_core::core::pmmr::PMMR<'a, T, B>>::root
  13: grin_chain::pipe::process_block
  14: grin_chain::chain::Chain::process_block
  15: <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::NetAdapter>::block_received
  16: <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::block_received
  17: <futures::future::chain::Chain<A, B, C>>::poll
  18: <futures::stream::fold::Fold<S, F, Fut, T> as futures::future::Future>::poll
  19: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  20: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  21: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  22: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  23: tokio_core::reactor::Core::poll
  24: grin_grin::server::Server::start
  25: grin::main
  26: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  27: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  28: __libc_start_main
  29: _start
```

**Comment by antiochp** [comment]
This node is repeatedly doing this now - it appears to be unable to startup successfully.
Is there anything else we can look at here? I can leave this node alone for further investigation.

**Comment by ignopeverell** [comment]
This looks like a corruption of the sumtree data file. There are no line number for the stack around lines 13? Otherwise the size of each pmmr_dat.bin may help in checking whether the problem is reading or the actual size of the data.

**Comment by antiochp** [comment]
Ahh - this is built with `--release` which is probably why there are no line numbers.
I can build it without `--release` and see what we get.

**Comment by ignopeverell** [comment]
That would help. Also if you can zip your whole sumtrees dir under .grin and somehow give it to me I can check what's wrong.

**Comment by antiochp** [comment]
```
thread 'main' panicked at 'index 369980 out of range for slice of length 369330', /checkout/src/libcore/slice/mod.rs:748:4
Nov 04 00:32:17.148 DEBG Sync: peer 2358022 vs us 2358032
Nov 04 00:32:17.148 DEBG Requested 0 full blocks to download, total left: 314. Current list: [BlockDownload { hash: e6826ec3, start_time: Instant { tv_sec: 193211, tv_nsec: 426994733 }, retries: 7 }, BlockDownload { hash: ddb1d340, start_time: Instant { tv_sec: 193211, tv_nsec: 427617976 }, retries: 7 }, BlockDownload { hash: 3b21643b, start_time: Instant { tv_sec: 193211, tv_nsec: 428204925 }, retries: 7 }, BlockDownload { hash: 15e8409d, start_time: Instant { tv_sec: 193211, tv_nsec: 428838608 }, retries: 7 }, BlockDownload { hash: 500054c5, start_time: Instant { tv_sec: 193211, tv_nsec: 506650815 }, retries: 7 }, BlockDownload { hash: 43259c7d, start_time: Instant { tv_sec: 193211, tv_nsec: 506935592 }, retries: 7 }, BlockDownload { hash: 1b09ff7b, start_time: Instant { tv_sec: 193211, tv_nsec: 507147200 }, retries: 7 }, BlockDownload { hash: 2ed9aebd, start_time: Instant { tv_sec: 193211, tv_nsec: 507346794 }, retries: 7 }].
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
Nov 04 00:32:19.206 DEBG Sync: peer 2358022 vs us 2358032
Nov 04 00:32:19.206 DEBG Retry 7 on block e6826ec3
Nov 04 00:32:19.206 DEBG Requesting block e6826ec3 from peer 127.0.0.1:13414.
Nov 04 00:32:19.207 DEBG Retry 7 on block ddb1d340
Nov 04 00:32:19.207 DEBG Requesting block ddb1d340 from peer 127.0.0.1:13414.
Nov 04 00:32:19.207 DEBG Retry 7 on block 3b21643b
Nov 04 00:32:19.207 DEBG Requesting block 3b21643b from peer 127.0.0.1:13414.
Nov 04 00:32:19.207 DEBG Retry 7 on block 15e8409d
Nov 04 00:32:19.207 DEBG Requesting block 15e8409d from peer 192.81.220.194:13414.
Nov 04 00:32:19.207 DEBG Retry 7 on block 500054c5
Nov 04 00:32:19.207 DEBG Requesting block 500054c5 from peer 127.0.0.1:13414.
Nov 04 00:32:19.207 DEBG Retry 7 on block 43259c7d
Nov 04 00:32:19.207 DEBG Requesting block 43259c7d from peer 127.0.0.1:13414.
Nov 04 00:32:19.207 DEBG Retry 7 on block 1b09ff7b
Nov 04 00:32:19.207 DEBG Requesting block 1b09ff7b from peer 192.81.220.194:13414.
Nov 04 00:32:19.207 DEBG Retry 7 on block 2ed9aebd
Nov 04 00:32:19.207 DEBG Requesting block 2ed9aebd from peer 192.81.220.194:13414.
Nov 04 00:32:19.207 DEBG Requested 0 full blocks to download, total left: 314. Current list: [BlockDownload { hash: e6826ec3, start_time: Instant { tv_sec: 193211, tv_nsec: 426994733 }, retries: 8 }, BlockDownload { hash: ddb1d340, start_time: Instant { tv_sec: 193211, tv_nsec: 427617976 }, retries: 8 }, BlockDownload { hash: 3b21643b, start_time: Instant { tv_sec: 193211, tv_nsec: 428204925 }, retries: 8 }, BlockDownload { hash: 15e8409d, start_time: Instant { tv_sec: 193211, tv_nsec: 428838608 }, retries: 8 }, BlockDownload { hash: 500054c5, start_time: Instant { tv_sec: 193211, tv_nsec: 506650815 }, retries: 8 }, BlockDownload { hash: 43259c7d, start_time: Instant { tv_sec: 193211, tv_nsec: 506935592 }, retries: 8 }, BlockDownload { hash: 1b09ff7b, start_time: Instant { tv_sec: 193211, tv_nsec: 507147200 }, retries: 8 }, BlockDownload { hash: 2ed9aebd, start_time: Instant { tv_sec: 193211, tv_nsec: 507346794 }, retries: 8 }].
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
Nov 04 00:32:21.265 DEBG Sync: peer 2358022 vs us 2358032
Nov 04 00:32:21.265 DEBG Requested 0 full blocks to download, total left: 314. Current list: [BlockDownload { hash: e6826ec3, start_time: Instant { tv_sec: 193211, tv_nsec: 426994733 }, retries: 8 }, BlockDownload { hash: ddb1d340, start_time: Instant { tv_sec: 193211, tv_nsec: 427617976 }, retries: 8 }, BlockDownload { hash: 3b21643b, start_time: Instant { tv_sec: 193211, tv_nsec: 428204925 }, retries: 8 }, BlockDownload { hash: 15e8409d, start_time: Instant { tv_sec: 193211, tv_nsec: 428838608 }, retries: 8 }, BlockDownload { hash: 500054c5, start_time: Instant { tv_sec: 193211, tv_nsec: 506650815 }, retries: 8 }, BlockDownload { hash: 43259c7d, start_time: Instant { tv_sec: 193211, tv_nsec: 506935592 }, retries: 8 }, BlockDownload { hash: 1b09ff7b, start_time: Instant { tv_sec: 193211, tv_nsec: 507147200 }, retries: 8 }, BlockDownload { hash: 2ed9aebd, start_time: Instant { tv_sec: 193211, tv_nsec: 507346794 }, retries: 8 }].
             at /checkout/src/libcore/panicking.rs:71
   9: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice/mod.rs:748
  10: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /checkout/src/libcore/slice/mod.rs:879
  11: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /checkout/src/libcore/slice/mod.rs:730
  12: grin_store::sumtree::AppendOnlyFile::read
             at store/src/sumtree.rs:96
  13: <grin_store::sumtree::PMMRBackend<T> as grin_core::core::pmmr::Backend<T>>::get
             at /grin/store/src/sumtree.rs:315
  14: <grin_core::core::pmmr::PMMR<'a, T, B>>::root::{{closure}}
             at /grin/core/src/core/pmmr.rs:247
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  16: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  17: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1073
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at /checkout/src/liballoc/vec.rs:1825
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1808
  20: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1695
  21: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1298
  22: <grin_core::core::pmmr::PMMR<'a, T, B>>::root
             at /grin/core/src/macros.rs:23
  23: grin_chain::sumtree::Extension::roots
             at chain/src/sumtree.rs:331
  24: grin_chain::pipe::validate_block
             at chain/src/pipe.rs:252
  25: grin_chain::pipe::process_block::{{closure}}
             at chain/src/pipe.rs:78
  26: grin_chain::sumtree::extending
             at chain/src/sumtree.rs:154
  27: grin_chain::pipe::process_block
             at chain/src/pipe.rs:77
  28: grin_chain::chain::Chain::process_block
             at chain/src/chain.rs:128
  29: <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::NetAdapter>::block_received
             at grin/src/adapters.rs:76
  30: <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::block_received
             at p2p/src/peer.rs:228
  31: grin_p2p::protocol::handle_payload
             at p2p/src/protocol.rs:165
  32: <grin_p2p::protocol::ProtocolV1 as grin_p2p::types::Protocol>::handle::{{closure}}
             at p2p/src/protocol.rs:52
  33: <F as grin_p2p::conn::Handler>::handle
             at p2p/src/conn.rs:66
  34: grin_p2p::conn::TimeoutConnection::listen::{{closure}}
             at p2p/src/conn.rs:275
  35: <F as grin_p2p::conn::Handler>::handle
             at p2p/src/conn.rs:66
  36: grin_p2p::conn::Connection::read_msg::{{closure}}Nov 04 00:32:23.265 DEBG Sync: peer 2358022 vs us 2358032
Nov 04 00:32:23.344 DEBG Retry 8 on block e6826ec3
Nov 04 00:32:23.344 DEBG Requesting block e6826ec3 from peer 127.0.0.1:13414.
Nov 04 00:32:23.344 DEBG Retry 8 on block ddb1d340
Nov 04 00:32:23.344 DEBG Requesting block ddb1d340 from peer 127.0.0.1:13414.
Nov 04 00:32:23.344 DEBG Retry 8 on block 3b21643b
Nov 04 00:32:23.344 DEBG Requesting block 3b21643b from peer 127.0.0.1:13414.
Nov 04 00:32:23.344 DEBG Retry 8 on block 15e8409d
Nov 04 00:32:23.344 DEBG Requesting block 15e8409d from peer 192.81.220.194:13414.
Nov 04 00:32:23.344 DEBG Retry 8 on block 500054c5
Nov 04 00:32:23.344 DEBG Requesting block 500054c5 from peer 192.81.220.194:13414.
Nov 04 00:32:23.344 DEBG Retry 8 on block 43259c7d
Nov 04 00:32:23.344 DEBG Requesting block 43259c7d from peer 127.0.0.1:13414.
Nov 04 00:32:23.344 DEBG Retry 8 on block 1b09ff7b
Nov 04 00:32:23.344 DEBG Requesting block 1b09ff7b from peer 192.81.220.194:13414.
Nov 04 00:32:23.344 DEBG Retry 8 on block 2ed9aebd
Nov 04 00:32:23.344 DEBG Requesting block 2ed9aebd from peer 127.0.0.1:13414.
Nov 04 00:32:23.344 DEBG Requested 0 full blocks to download, total left: 314. Current list: [BlockDownload { hash: e6826ec3, start_time: Instant { tv_sec: 193211, tv_nsec: 426994733 }, retries: 9 }, BlockDownload { hash: ddb1d340, start_time: Instant { tv_sec: 193211, tv_nsec: 427617976 }, retries: 9 }, BlockDownload { hash: 3b21643b, start_time: Instant { tv_sec: 193211, tv_nsec: 428204925 }, retries: 9 }, BlockDownload { hash: 15e8409d, start_time: Instant { tv_sec: 193211, tv_nsec: 428838608 }, retries: 9 }, BlockDownload { hash: 500054c5, start_time: Instant { tv_sec: 193211, tv_nsec: 506650815 }, retries: 9 }, BlockDownload { hash: 43259c7d, start_time: Instant { tv_sec: 193211, tv_nsec: 506935592 }, retries: 9 }, BlockDownload { hash: 1b09ff7b, start_time: Instant { tv_sec: 193211, tv_nsec: 507147200 }, retries: 9 }, BlockDownload { hash: 2ed9aebd, start_time: Instant { tv_sec: 193211, tv_nsec: 507346794 }, retries: 9 }].
::{{closure}}
             at p2p/src/conn.rs:215
  37: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:34
  38: <core::result::Result<T, E>>::map
             at /checkout/src/libcore/result.rs:468
  39: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:33
  40: <futures::future::chain::Chain<A, B, C>>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:39
  41: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:32
  42: <futures::stream::fold::Fold<S, F, Fut, T> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/stream/fold.rs:70
  43: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  44: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  45: <futures::future::select::Select<A, B> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/select.rs:48
  46: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  47: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  48: <futures::future::select::Select<A, B> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/select.rs:52
  49: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  50: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  51: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  52: <futures::future::select::Select<A, B> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/select.rs:48
  53: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  54: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  55: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  56: <futures::future::chain::Chain<A, B, C>>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:26
  57: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/then.rs:32
  58: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  59: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  60: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  61: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  62: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  63: futures::task_impl::std::set
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/std/mod.rs:78
  64: <futures::task_impl::Spawn<T>>::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  65: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  66: tokio_core::reactor::Core::dispatch_task::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:356
  67: <scoped_tls::ScopedKey<T>>::set
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  68: tokio_core::reactor::Core::dispatch_task
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:355
  69: tokio_core::reactor::Core::dispatch
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:316
  70: tokio_core::reactor::Core::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:304
  71: tokio_core::reactor::Core::run
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:241
  72: grin_grin::server::Server::start
             at grin/src/server.rs:76
  73: grin::server_command
             at src/bin/grin.rs:314
  74: grin::main
             at src/bin/grin.rs:243
  75: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  76: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  77: main
  78: __libc_start_main
  79: _start
```

**Comment by antiochp** [comment]
copy of sumtrees dir -
[sumtrees.tar.gz](https://github.com/mimblewimble/grin/files/1442783/sumtrees.tar.gz)

**Comment by ignopeverell** [comment]
Thanks! Time to do some binary file spelunking...

**Comment by antiochp** [comment]
👍 looks good - updated my server and it appears to be resyncing happily now.
