### ISSUE TITLE
Server subcommand in Docker ignores config_file option

### ISSUE THREAD

**Issue by MatthewDarnell** [mimblewimble/grin#2430]
Not sure if this was fixed in issue `2317`, but I'm running into it on Docker.

```
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y build-essential cmake curl git libgit2-dev clang libncurses5-dev libncursesw5-dev zlib1g-dev pkg-config libssl-dev llvm
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
  && . $HOME/.cargo/env \
  && mv /root/.cargo/bin/* /usr/local/bin/
WORKDIR /usr/src
RUN git clone https://github.com/mimblewimble/grin.git
WORKDIR /usr/src/grin
RUN cargo build \
  && mkdir -p /root/.grin/main /var/lib/grin \
  && mv target/debug/grin /usr/local/bin/grin
WORKDIR /var/lib/grin
ENV RUST_BACKTRACE=1
EXPOSE 3414
EXPOSE 3415
RUN grin server config;
RUN sed -i 's/.*run_tui.*/run_tui = false/g' /var/lib/grin/grin-server.toml
RUN sed -i 's/.*stdout_log_level.*/stdout_log_level = "Trace"/g' /var/lib/grin/grin-server.toml
RUN sed -i 's@.*wallet_listener_url.*@wallet_listener_url = "http://127.0.0.1:3000"@g' /var/lib/grin/grin-server.toml
RUN touch /usr/local/bin/entrypoint.sh \
  && chmod +x /usr/local/bin/entrypoint.sh \
  && echo "#!/bin/sh" >> /usr/local/bin/entrypoint.sh \
  && echo 'grin;' >> /usr/local/bin/entrypoint.sh \
  && echo "grin wallet -p 'random password' init;" >> /usr/local/bin/entrypoint.sh \
  && echo "grin wallet -p 'random password' listen;" >> /usr/local/bin/entrypoint.sh \
  && echo 'grin server --config_file="/var/lib/grin/grin-server.toml" --api_port=13000 --port=8000 start;' >> /usr/local/bin/entrypoint.sh
WORKDIR /root/.grin
ENTRYPOINT ["entrypoint.sh"]
RUN ln -sf /dev/stdout /root/.grin/main/grin-server.log
```

As you can see, I am disabling tui and setting the stdout log level in `/var/lib/grin/grin-server.toml`, then passing it to `grin server --config_file="/var/lib/grin/grin-server.toml"`. (I have verified that the file exists by adding a `RUN cat /var/lib/grin/grin-server.toml` line)

The logs when I run it are as follows:

```$ docker run grin
20190119 21:59:43.455 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190119 21:59:43.455 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20190119 21:59:43.456 INFO grin - This is Grin version 1.0.0 (git v1.0.0-14-gef5d838), built for x86_64-unknown-linux-gnu by rustc 1.32.0 (9fda7c223 2019-01-16).
20190119 21:59:43.456 WARN grin::cmd::server - Starting GRIN in UI mode...
```

It then proceeds to log a panic in thread 'ui'. I'm not sure yet whether or not it's recognizing `api_port` and `port` flags.

Docker: 2.0.0.2 on MacOS

**Comment by chisa0a** [comment]
Same problem outside Docker, panics on startup, ignores config option:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 17, kind: AlreadyExists, message: "File exists" })': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::... (0x...)
             at util/src/logger.rs:240
   1: rust_panic_with_hook (0x...)
             at src/libstd/panicking.rs:482
   2: continue_panic_fmt (0x...)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x...)
   4: panic_fmt (0x...)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::... (0x...)
             at /rustc/.../src/libcore/macros.rs:17
   6: <core::result::Result<T, E>>::unwrap::... (0x...)
             at /rustc/.../src/libcore/result.rs:798
   7: grin::cmd::server::start_server_tui::... (0x...)
             at src/bin/cmd/server.rs:62
   8: grin::cmd::server::start_server::... (0x...)
             at src/bin/cmd/server.rs:33
   9: grin::cmd::server::server_command::... (0x...)
             at src/bin/cmd/server.rs:131
  10: grin::real_main::... (0x...)
             at src/bin/grin.rs:149
  11: grin::main::... (0x...)
             at src/bin/grin.rs:67
  12: std::rt::lang_start::{{closure}}::... (0x...)
             at /rustc/.../src/libstd/rt.rs:64
  13: {{closure}} (0x...)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:297
  14: __rust_maybe_catch_panic (0x...)
             at src/libpanic_unwind/lib.rs:87
  15: try<i32,closure> (0x...)
             at src/libstd/panicking.rs:276
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  16: std::rt::lang_start::... (0x...)
             at /rustc/.../src/libstd/rt.rs:64
  17: main (0x...)
  18: __libc_start_main (0x...)
  19: _start (0x...)
  20: <unknown> (0x0)
```
