### ISSUE TITLE
Request error: Cannot make request: parsed HTTP message from remote is incomplete

### ISSUE THREAD

**Issue by superphly** [mimblewimble/grin#2515]
**Describe the bug**
After using `grin` and `grin wallet check` and doing some successful transfers, I'm unable to check my balance now with `grin wallet check`. I'm getting this error:

20190201 15:13:31.976 ERROR grin_wallet::node_clients::http - get_outputs_by_pmmr_index: unable to contact API http://127.0.0.1:3413. Error: Request error: Cannot make request: parsed HTTP message from remote is incomplete

**To Reproduce**
1. Run 'grin wallet check'
2. Expect data on my balance

**Comment by hashmap** [comment]
> I'm unable to check my balance now with `grin wallet check`

Do I understand correctly that you use `check` to check your balance? You sholud use `grin wallet info` for that, `check` tries to repair your wallet

**Comment by BitHighlander** [comment]
I can confirm this issue. My Wallet is reporting a 0 balance on multiple wallet tiles and I am unable to restore outputs and fix wallet. 

```
20190223 02:18:20.698 DEBUG grin_p2p::protocol - handle_payload: GetTransaction: 14c43b9340e2, msg_len: 32
20190223 02:18:29.062 ERROR grin_util::logger - 
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: 

Other Error: get header by height }': src/libcore/result.rs:1009stack backtrace:
   0:     0x556d9ae9b75d - backtrace::backtrace::trace::h2309a19e9582c4ed
   1:     0x556d9ae9a882 - backtrace::capture::Backtrace::new::h93a1fac54c6e6f9e
   2:     0x556d9ae1bc80 - grin_util::logger::send_panic_to_log::{{closure}}::h71a59b48864f140f
   3:     0x556d9af5c819 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                        at src/libstd/panicking.rs:495
   4:     0x556d9af5c2c1 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                        at src/libstd/panicking.rs:398
   5:     0x556d9af5c1a5 - rust_begin_unwind
                        at src/libstd/panicking.rs:325
   6:     0x556d9af7941c - core::panicking::panic_fmt::h4d67173bc68f6d5a
                        at src/libcore/panicking.rs:95
   7:     0x556d9aabcfa9 - core::result::unwrap_failed::hc00cc6347659530a
   8:     0x556d9ab089ff - grin_api::types::OutputPrintable::from_output::h0aad3fa4e1fb8fd4
   9:     0x556d9aaf1d20 - <core::iter::Map<I, F> as core::iter::iterator::Iterator>::fold::hb176d3fa22c5c2bb
  10:     0x556d9aa4001a - <grin_api::handlers::transactions_api::TxHashSetHandler as grin_api::router::Handler>::get::hf9f57eea0da35184
  11:     0x556d9aa41630 - grin_api::router::Handler::call::hdf9af6c2726afac7
  12:     0x556d9aa2330c - <grin_api::auth::BasicAuthMiddleware as grin_api::router::Handler>::call::hbcb896e5b286832e
  13:     0x556d9aa43136 - <grin_api::router::Router as hyper::service::service::Service>::call::h8a06d075931692db
  14:     0x556d9aae6805 - <hyper::proto::h1::dispatch::Server<S> as hyper::proto::h1::dispatch::Dispatch>::recv_msg::h9c179c2dbd06f2af
  15:     0x556d9aaf8958 - <hyper::proto::h1::dispatch::Dispatcher<D, Bs, I, T>>::poll_catch::heff8cad15ee6b26c
  16:     0x556d9aa78f73 - <hyper::server::conn::upgrades::UpgradeableConnection<I, S, E> as futures::future::Future>::poll::h4fc121e2d99ec473
  17:     0x556d9aae6e23 - <hyper::server::conn::spawn_all::NewSvcTask<I, N, S, E, W> as futures::future::Future>::poll::h388e45cef580132f
  18:     0x556d9ac8acd1 - futures::task_impl::std::set::hfb25dbb354d1630c
  19:     0x556d9ac8c205 - <futures::task_impl::Spawn<T>>::poll_future_notify::hb7f0a5dbc2616f0a
  20:     0x556d9ac8ef10 - std::panicking::try::do_call::hcd450f721db3b625
  21:     0x556d9af72749 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  22:     0x556d9ac8dc8b - tokio_threadpool::task::Task::run::h5861175888dcb9c7
  23:     0x556d9ac85c85 - tokio_threadpool::worker::Worker::run_task::hd2f5592e9e45bcd1
  24:     0x556d9ac8512d - tokio_threadpool::worker::Worker::run::h817f755e22fbf52d
  25:     0x556d9ac718f6 - <std::thread::local::LocalKey<T>>::with::hff033a066f1986ee
  26:     0x556d9ac715d7 - <std::thread::local::LocalKey<T>>::with::h2f90e3d514f1cb0f
  27:     0x556d9ac71741 - <std::thread::local::LocalKey<T>>::with::he3a3f0ececf20c13
  28:     0x556d9ac6d319 - tokio::runtime::builder::Builder::build::{{closure}}::h4ab12451eda31f7b
  29:     0x556d9ac8f612 - <std::thread::local::LocalKey<T>>::with::hd3b9662812b9f262
  30:     0x556d9ac8f009 - <std::thread::local::LocalKey<T>>::with::h0984e29c2f224183
  31:     0x556d9ac8ebcd - std::sys_common::backtrace::__rust_begin_short_backtrace::h50d98373971b3fe7
  32:     0x556d9ac8eecb - std::panicking::try::do_call::hb70f234518a8ed4f
  33:     0x556d9af72749 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  34:     0x556d9ac8a93f - <F as alloc::boxed::FnBox<A>>::call_box::hf4687687d5d552e0
  35:     0x556d9af6632d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                         - std::sys_common::thread::start_thread::h9605a7df0f911844
                        at src/libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
                        at src/libstd/sys/unix/thread.rs:90
  36:     0x7efce9be150a - start_thread
  37:     0x7efce970238e - clone
  38:                0x0 - <unknown>


Thread 'tokio-runtime-worker-0' panicked with message:
"called `Result::unwrap()` on an `Err` value: Error { inner: 

Other Error: get header by height }"
See /home/highlander/.grin/main/grin-server.log for further details.
20190223 02:18:29.371 DEBUG grin_servers::grin::seed - monitor_peers: on 0.0.0.0:3414, 8 connected (7 most_work). all 4920 = 2236 healthy + 0 banned + 2684 defunct
20190223 02:18:37.398 DEBUG grin_p2p::peer - Client 91.246.3.21:3414 connection lost: Connection(Custom { kind: ConnectionAborted, error: StringError("read_exact") })
20190223 02:18:43.372 DEBUG grin_p2p::peer - Client 35.192.117.152:3414 connection lost: Connection(Custom { kind: ConnectionAborted, error: StringError("read_exact") })
20190223 02:18:49.375 DEBUG grin_servers::grin::seed - monitor_peers: on 0.0.0.0:3414, 6 connected (6 most_work). all 4923 = 2241 healthy + 0 banned + 2682 defunct
```
Error from server


```
20190223 02:18:28.541 WARN grin_wallet::libwallet::internal::restore - Scanning 1000 outputs in the current Grin utxo set
20190223 02:18:29.063 ERROR grin_wallet::node_clients::http - get_outputs_by_pmmr_index: error contacting http://127.0.0.1:3413. Error: Request error: Cannot make request: parsed HTTP message from remote is incomplete
20190223 02:18:29.063 ERROR grin_wallet::command - Wallet check failed: Restore Error
20190223 02:18:29.063 ERROR grin_wallet::command - Backtrace: 
Wallet command failed: LibWallet Error: Restore Error

```
error from wallet 

The result of this is preventing me from accessing funds.

I have not tried a restore from seed yet, that will be next.
