### ISSUE TITLE
Binary release don't run in VPS vmare based

### ISSUE THREAD

**Issue by nikito7** [mimblewimble/grin#2640]
[code]
20190228 13:54:12.158 INFO grin_util::logger - log4rs is initialized, file level: Trace, stdout level: Trace, min. level: Trace
20190228 13:54:12.158 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20190228 13:54:12.158 INFO grin - This is Grin version 1.0.2 (git v1.0.2), built for x86_64-unknown-linux-gnu by rustc 1.32.0 (9fda7c223 2019-01-16).
20190228 13:54:12.158 DEBUG grin - Built with profile "release", features "".20190228 13:54:12.158 WARN grin::cmd::server - Starting GRIN in UI mode...
20190228 13:54:12.158 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190228 13:54:12.189 TRACE grin_chain::txhashset::txhashset - Starting new txhashset extension.
20190228 13:54:12.189 DEBUG grin_chain::txhashset::txhashset - Error returned, discarding txhashset extension: Other Error: output vs rproof MMRs different sizes
 Cause: Unknown
 Backtrace:
20190228 13:54:12.233 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner:

Other Error: output vs rproof MMRs different sizes })': src/libcore/result.rs:1009stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h4b7ede3e7432d241 (0x55e6f187b300)
   1: std::panicking::rust_panic_with_hook::h8cbdfe43764887be (0x55e6f19be079)
             at src/libstd/panicking.rs:495
   2: std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1 (0x55e6f19bdb21)
             at src/libstd/panicking.rs:398
   3: rust_begin_unwind (0x55e6f19bda05)
             at src/libstd/panicking.rs:325
   4: core::panicking::panic_fmt::h4d67173bc68f6d5a (0x55e6f19dab5c)
             at src/libcore/panicking.rs:95
   5: core::result::unwrap_failed::ha3b6d28e2c27cf9e (0x55e6f111d429)
   6: grin::cmd::server::start_server::h067c5f88ceecc92f (0x55e6f1112f5b)
   7: grin::cmd::server::server_command::h6c6aa04c5da5fbb1 (0x55e6f11138de)
   8: grin::real_main::h2ab25ccf59433f48 (0x55e6f116db2c)
   9: grin::main::h469d63eef75c4821 (0x55e6f116bfd5)
  10: std::rt::lang_start::{{closure}}::h9fb037da8f4b23ba (0x55e6f115cb22)
  11: std::rt::lang_start_internal::{{closure}}::hdfc28107b5be47c9 (0x55e6f19bd9a2)
             at src/libstd/rt.rs:59
      std::panicking::try::do_call::h69790245ac2d03fe
             at src/libstd/panicking.rs:310
  12: __rust_maybe_catch_panic (0x55e6f19d3e69)
             at src/libpanic_unwind/lib.rs:102
  13: std::panicking::try::h9c1cbc5599e1efbf (0x55e6f19be373)
             at src/libstd/panicking.rs:289
      std::panic::catch_unwind::h0562757d03ff60b3
             at src/libstd/panic.rs:398
      std::rt::lang_start_internal::h540c897fe52ba9c5
             at src/libstd/rt.rs:58
  14: main (0x55e6f116e481)
  15: __libc_start_main (0x7f1f9265609a)
  16: <unknown> (0x55e6f10a3580)
  17: <unknown> (0x0)
[/code]

**Comment by nikito7** [comment]
https://github.com/mimblewimble/grin/issues/2494
