### ISSUE TITLE
Grin server crashed right after start.

### ISSUE THREAD

**Issue by Incrediblez7** [mimblewimble/grin#2877]
`grin server` crashed right after start. `grin` didn't crash.

**Log file**
Log file at **debug** level:
```
20190607 07:37:59.007 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Info, min. level: Debug
20190607 07:37:59.007 INFO grin - Using configuration file at /Users/mac/Grin/grin-server.toml
20190607 07:37:59.007 INFO grin - This is Grin version 1.1.0 (git v1.1.0), built for x86_64-apple-darwin by rustc 1.35.0 (3c235d560 2019-05-20).
20190607 07:37:59.007 DEBUG grin - Built with profile "release", features "".
20190607 07:37:59.007 WARN grin::cmd::server - Starting GRIN in UI mode...
20190607 07:37:59.007 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190607 07:37:59.008 DEBUG grin_store::lmdb - DB Mapsize for /Users/mac/Grin/daemon_data/chain_state/lmdb is 134217728
20190607 07:37:59.008 DEBUG grin_store::leaf_set - bitmap 1 pos (18 bytes)
20190607 07:37:59.008 DEBUG grin_store::leaf_set - bitmap 1 pos (18 bytes)
20190607 07:37:59.009 DEBUG grin_chain::txhashset::txhashset - Rewind to header 40adad0aec27 at 0
20190607 07:37:59.009 DEBUG grin_chain::txhashset::txhashset - txhashset: rewind_to_pos: header 1, output 1, kernel 1
20190607 07:37:59.009 DEBUG grin_chain::chain - init: rewinding and validating before we start... 40adad0aec27 at 0
20190607 07:37:59.011 DEBUG grin_chain::chain - init: head: 17179869184 @ 0 [40adad0aec27]
20190607 07:37:59.012 DEBUG grin_chain::chain - init: header_head: 17179869184 @ 0 [40adad0aec27]
20190607 07:37:59.012 DEBUG grin_chain::chain - init: sync_head: 17179869184 @ 0 [40adad0aec27]
20190607 07:37:59.013 DEBUG grin_store::lmdb - DB Mapsize for /Users/mac/Grin/daemon_data/chain_state/peer is 1048576
20190607 07:37:59.013 DEBUG grin_servers::common::types - sync_state: sync_status: Initial -> AwaitingPeers(true)
20190607 07:37:59.013 INFO grin_servers::grin::server - Starting rest apis at: 127.0.0.1:3413
20190607 07:37:59.013 DEBUG grin_servers::grin::seed - Retrieving seed nodes from dns mainnet.seed.grin-tech.org
20190607 07:37:59.110 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: Other, message: "Is a directory" }': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h400bde7a53b4aaae (0x109407fd1)
   1: std::panicking::rust_panic_with_hook::hfcf2d0777bc6c409 (0x109535b80)
   2: std::panicking::continue_panic_fmt::h4d668741ea600293 (0x1095355cc)
   3: _rust_begin_unwind (0x1095354b8)
   4: core::panicking::panic_fmt::hdf67eedb88644e1e (0x10954e381)
   5: core::result::unwrap_failed::h783ac007f310c551 (0x109404202)
   6: grin_util::file::get_first_line::hd8f911a55cb75e92 (0x109402f93)
   7: grin_servers::grin::server::Server::new::h610b4be0de1cee18 (0x108f7aa00)
   8: grin_servers::grin::server::Server::start::h2c6d2a1207800733 (0x108d87ea4)
   9: grin::cmd::server::start_server::h5b18765de0ba3507 (0x108d7c338)
  10: grin::cmd::server::server_command::h6f88d628fbeeaf86 (0x108d7cabe)
  11: grin::real_main::hc27c60257b6aa087 (0x108daead2)
  12: grin::main::h5130721eaf781394 (0x108dad908)
  13: std::rt::lang_start::{{closure}}::h841a79a595a643b6 (0x108d88fb5)
  14: std::panicking::try::do_call::h1252fc9a2ff235eb (0x109535437)
  15: ___rust_maybe_catch_panic (0x10953a5ce)
  16: std::rt::lang_start_internal::h4c054360e442146c (0x109535e5d)
  17: _main (0x108db1e88)
```

Log file at **Trace** level:
```
20190607 07:38:49.266 INFO grin_util::logger - log4rs is initialized, file level: Trace, stdout level: Info, min. level: Trace
20190607 07:38:49.268 INFO grin - Using configuration file at /Users/mac/Grin/grin-server.toml
20190607 07:38:49.268 INFO grin - This is Grin version 1.1.0 (git v1.1.0), built for x86_64-apple-darwin by rustc 1.35.0 (3c235d560 2019-05-20).
20190607 07:38:49.268 DEBUG grin - Built with profile "release", features "".
20190607 07:38:49.268 WARN grin::cmd::server - Starting GRIN in UI mode...
20190607 07:38:49.280 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190607 07:38:49.281 DEBUG grin_store::lmdb - DB Mapsize for /Users/mac/Grin/daemon_data/chain_state/lmdb is 134217728
20190607 07:38:49.281 DEBUG grin_store::leaf_set - bitmap 1 pos (18 bytes)
20190607 07:38:49.281 DEBUG grin_store::leaf_set - bitmap 1 pos (18 bytes)
20190607 07:38:49.282 TRACE grin_store::lmdb - DB map size: 134217728
20190607 07:38:49.282 TRACE grin_store::lmdb - Space used: 40960
20190607 07:38:49.282 TRACE grin_store::lmdb - Space remaining: 134176768
20190607 07:38:49.282 TRACE grin_store::lmdb - Percent used: 0.0003  Percent threshold: 0.9000
20190607 07:38:49.282 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
20190607 07:38:49.282 TRACE grin_chain::txhashset::txhashset - Starting new txhashset header extension.
20190607 07:38:49.301 TRACE grin_chain::txhashset::txhashset - Committing txhashset header extension. size 1
20190607 07:38:49.301 TRACE grin_chain::txhashset::txhashset - TxHashSet header extension done.
20190607 07:38:49.301 TRACE grin_chain::txhashset::txhashset - Starting new txhashset extension.
20190607 07:38:49.301 DEBUG grin_chain::txhashset::txhashset - Rewind to header 40adad0aec27 at 0
20190607 07:38:49.301 DEBUG grin_chain::txhashset::txhashset - txhashset: rewind_to_pos: header 1, output 1, kernel 1
20190607 07:38:49.301 DEBUG grin_chain::chain - init: rewinding and validating before we start... 40adad0aec27 at 0
20190607 07:38:49.301 TRACE grin_chain::txhashset::txhashset - Committing txhashset extension. sizes (1, 1, 1, 1)
20190607 07:38:49.303 TRACE grin_chain::txhashset::txhashset - TxHashSet extension done.
20190607 07:38:49.303 DEBUG grin_chain::chain - init: head: 17179869184 @ 0 [40adad0aec27]
20190607 07:38:49.303 DEBUG grin_chain::chain - init: header_head: 17179869184 @ 0 [40adad0aec27]
20190607 07:38:49.303 DEBUG grin_chain::chain - init: sync_head: 17179869184 @ 0 [40adad0aec27]
20190607 07:38:49.305 DEBUG grin_store::lmdb - DB Mapsize for /Users/mac/Grin/daemon_data/chain_state/peer is 1048576
20190607 07:38:49.305 DEBUG grin_servers::common::types - sync_state: sync_status: Initial -> AwaitingPeers(true)
20190607 07:38:49.305 INFO grin_servers::grin::server - Starting rest apis at: 127.0.0.1:3413
20190607 07:38:49.305 DEBUG grin_servers::grin::seed - Retrieving seed nodes from dns mainnet.seed.grin-tech.org
20190607 07:38:49.407 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 21, kind: Other, message: "Is a directory" }': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h400bde7a53b4aaae (0x103181fd1)
   1: std::panicking::rust_panic_with_hook::hfcf2d0777bc6c409 (0x1032afb80)
   2: std::panicking::continue_panic_fmt::h4d668741ea600293 (0x1032af5cc)
   3: _rust_begin_unwind (0x1032af4b8)
   4: core::panicking::panic_fmt::hdf67eedb88644e1e (0x1032c8381)
   5: core::result::unwrap_failed::h783ac007f310c551 (0x10317e202)
   6: grin_util::file::get_first_line::hd8f911a55cb75e92 (0x10317cf93)
   7: grin_servers::grin::server::Server::new::h610b4be0de1cee18 (0x102cf4a00)
   8: grin_servers::grin::server::Server::start::h2c6d2a1207800733 (0x102b01ea4)
   9: grin::cmd::server::start_server::h5b18765de0ba3507 (0x102af6338)
  10: grin::cmd::server::server_command::h6f88d628fbeeaf86 (0x102af6abe)
  11: grin::real_main::hc27c60257b6aa087 (0x102b28ad2)
  12: grin::main::h5130721eaf781394 (0x102b27908)
  13: std::rt::lang_start::{{closure}}::h841a79a595a643b6 (0x102b02fb5)
  14: std::panicking::try::do_call::h1252fc9a2ff235eb (0x1032af437)
  15: ___rust_maybe_catch_panic (0x1032b45ce)
  16: std::rt::lang_start_internal::h4c054360e442146c (0x1032afe5d)
  17: _main (0x102b2be88)
```

**Desktop:**
 - OS: macOS Mojave
 - Version: 10.14 Beta (18A377a)
 - CPU: 2.9GHz i7
 - RAM: 16GB 2133MHz

**Comment by mcdallas** [comment]
Did you change anything in grin-server.toml ? Seems like it was expecting a file somewhere and it got a dir

**Comment by Incrediblez7** [comment]
The only thing I changed was the `peer_max_count` option. I uncommented and changed it from `125` to `1000`.
I'll try with a new grin-server.toml.

**Comment by Incrediblez7** [comment]
It's working. Thanks.
