### ISSUE TITLE
Grin node failed to start Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by josephmike2014** [mimblewimble/grin#2891]
**Describe the bug**
I installed Grin node as usual, but the grin can't be started in my new VPS. It seems issue is from CPU support?

When I run ./grin, only message Illegal instruction (core dumped) appeared.
I tried to view grin-server.log the log shown below:

```
20190612 07:14:19.926 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190612 07:14:19.926 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20190612 07:14:19.926 INFO grin - This is Grin version 1.1.0 (git v1.1.0), built for x86_64-unknown-linux-gnu by rustc 1.34.2 (6c2484dc3 2019-05-13).
20190612 07:14:19.926 WARN grin::cmd::server - Starting GRIN in UI mode...
20190612 07:14:19.927 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190612 07:14:19.938 INFO grin_store::lmdb - Resized database from 1048576 to 134217728
20190612 07:17:14.765 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190612 07:17:14.765 INFO grin - Using configuration file at /root/.grin/main/grin-server.toml
20190612 07:17:14.765 INFO grin - This is Grin version 1.1.0 (git v1.1.0), built for x86_64-unknown-linux-gnu by rustc 1.34.2 (6c2484dc3 2019-05-13).
20190612 07:17:14.765 WARN grin::cmd::server - Starting GRIN in UI mode...
20190612 07:17:14.765 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20190612 07:17:14.767 INFO grin_store::lmdb - Resized database from 1048576 to 134217728
20190612 07:17:14.880 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner:

Other Error: output vs rproof MMRs different sizes })': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h31e197f4be311b52 (0x55e5ff607e80)
   1: rust_panic_with_hook (0x55e5ff736018)
             at src/libstd/panicking.rs:482
   2: continue_panic_fmt (0x55e5ff735ab1)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x55e5ff735995)
   4: panic_fmt (0x55e5ff75001c)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::hfc1b09440a9a8f0b (0x55e5fef984c8)
   6: grin::cmd::server::start_server::h40388d9cf11a099e (0x55e5fef9a326)
   7: grin::cmd::server::server_command::h0b2e6e63b2bd560e (0x55e5fef9fcd9)
   8: grin::real_main::h43b137cc612879ad (0x55e5fefcbe41)
   9: grin::main::hd56d1cc8c7d71611 (0x55e5fefcaa25)
  10: std::rt::lang_start::{{closure}}::h17bdba1538e6cc74 (0x55e5fefa7182)
  11: {{closure}} (0x55e5ff735932)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic (0x55e5ff73bf49)
             at src/libpanic_unwind/lib.rs:87
  13: try<i32,closure> (0x55e5ff73643c)
             at src/libstd/panicking.rs:276
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  14: main (0x55e5fefcf0a1)
  15: __libc_start_main (0x7fc33890fb96)
  16: _start (0x55e5fef86e38)
  17: <unknown> (0x0)

```

 - OS: Ubuntu 18.04
 - CPU Info:

```
processor       : 1
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2397.400
cache size      : 16384 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl
xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
bogomips        : 4794.80
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual

```

**Comment by wsy2220** [comment]
Build from source will solve this.

**Comment by josephmike2014** [comment]
> Build from source will solve this.
Any tutorial reference? I followed https://github.com/mimblewimble/docs/wiki/How-to%3A-Run-a-Grin-node-on-Google-Cloud-for-free
 I'm new to this.

**Comment by kargakis** [comment]
@josephmike2014 the build docs can be found at https://github.com/mimblewimble/grin/blob/master/doc/build.md

**Comment by josephmike2014** [comment]
> @josephmike2014 the build docs can be found at https://github.com/mimblewimble/grin/blob/master/doc/build.md

I just carefully followed it but same issue. Let me know if want to test it in my VPS.

**Comment by kargakis** [comment]
Seems like you are hitting https://github.com/mimblewimble/grin/issues/2494

**Comment by hashmap** [comment]
@josephmike2014 could you please post an output of ` cat /proc/cpuinfo`? I agree it looks like #2494 which we should fix finally

**Comment by kargakis** [comment]
@hashmap cpu info is already posted in the initial post, there is no sign of avx in the cpu flags.

**Comment by hashmap** [comment]
@kargakis oh, thanks. Closing as a duplicate
