### ISSUE TITLE
test miner panic on ctrl+c

### ISSUE THREAD

**Issue by wsy2220** [mimblewimble/grin#2895]
**Describe the bug**
test miner panic on ctrl+c

**To Reproduce**
1. Run UserTesting chain with test miner on to produce blocks
2. Hit ctrl+c

**Logs**
```
20190613 14:21:05.716 DEBUG grin_servers::mining::mine_block - get_coinbase: BlockFees { fees: 0, height: 361, key_id: Some(Identifier(0300000000000000000000010a00000000)) }
20190613 14:21:05.721 DEBUG grin_servers::mining::mine_block - Built new block with 0 inputs and 1 outputs, block difficulty: 116, cumulative difficulty 11073
20190613 14:21:05.721 DEBUG grin_servers::mining::test_miner - (Server ID: Port 23414) Mining Cuckoo15 for max 60s on 11073 @ 361 [3509862c849d].
20190613 14:21:05.967 INFO grin_servers::mining::test_miner - (Server ID: Port 23414) Found valid proof of work, adding block 193f1bfb3b2a (prev_root f58b3e4d7259).
20190613 14:21:05.967 DEBUG grin_chain::pipe - pipe: process_block 193f1bfb3b2a at 361 [in/out/kern: 0/1/1]
20190613 14:21:05.967 DEBUG grin_chain::pipe - pipe: header_head updated to 193f1bfb3b2a at 361
20190613 14:21:06.003 DEBUG grin_chain::pipe - pipe: head updated to 193f1bfb3b2a at 361
20190613 14:21:06.008 DEBUG grin_servers::common::hooks - block_accepted (head+): 193f1bfb3b2a at 361 (diff: 11073)
20190613 14:21:06.008 DEBUG grin_p2p::peers - broadcast_compact_block: 193f1bfb3b2a, 11073 at 361, to 1 peers, done.
20190613 14:21:06.008 DEBUG grin_pool::transaction_pool - truncate_reorg_cache: size: 0
20190613 14:21:06.086 DEBUG grin_servers::mining::mine_block - get_coinbase: BlockFees { fees: 0, height: 362, key_id: Some(Identifier(0300000000000000000000010b00000000)) }
20190613 14:21:06.092 DEBUG grin_servers::mining::mine_block - Built new block with 0 inputs and 1 outputs, block difficulty: 116, cumulative difficulty 11189
20190613 14:21:06.092 DEBUG grin_servers::mining::test_miner - (Server ID: Port 23414) Mining Cuckoo15 for max 60s on 11189 @ 362 [193f1bfb3b2a].
^C20190613 14:21:07.744 WARN grin::cmd::server - Received SIGINT (Ctrl+C) or SIGTERM (kill).
20190613 14:21:07.744 DEBUG grin_servers::common::types - sync_state: sync_status: NoSync -> Shutdown
20190613 14:21:07.753 INFO grin_servers::grin::server - connect_and_monitor thread stopped
20190613 14:21:07.844 INFO grin_servers::grin::server - sync thread stopped
20190613 14:21:08.743 INFO grin_servers::grin::server - dandelion_monitor thread stopped
20190613 14:21:08.743 DEBUG grin_p2p::peer - Stopping peer PeerAddr(V4(172.17.0.2:23414))
20190613 14:21:08.743 DEBUG grin_p2p::peer - Waiting for peer PeerAddr(V4(172.17.0.2:23414)) to stop
20190613 14:21:08.743 DEBUG grin_p2p::conn - waiting for thread ThreadId(11) exit
20190613 14:21:08.744 DEBUG grin_p2p::conn - Shutting down connection with 172.17.0.2:23414
20190613 14:21:08.744 INFO grin_servers::grin::server - p2p thread stopped
20190613 14:21:08.744 WARN grin::cmd::server - Shutting down...
20190613 14:21:09.544 INFO grin_servers::mining::test_miner - (Server ID: Port 23414) Found valid proof of work, adding block 1f73574cae65 (prev_root 7f264163cc9e).
20190613 14:21:09.544 DEBUG grin_chain::pipe - pipe: process_block 1f73574cae65 at 362 [in/out/kern: 0/1/1]
20190613 14:21:09.544 DEBUG grin_chain::pipe - pipe: header_head updated to 1f73574cae65 at 362
20190613 14:21:09.586 DEBUG grin_chain::pipe - pipe: head updated to 1f73574cae65 at 362
20190613 14:21:09.591 DEBUG grin_servers::common::hooks - block_accepted (head+): 1f73574cae65 at 362 (diff: 11189)
20190613 14:21:09.612 ERROR grin_util::logger - 
thread 'test_miner' panicked at 'Failed to upgrade weak ref to our peers.': src/libcore/option.rs:1038stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h38543c8a04ad5059 (0x559d11b272e0)
   1: rust_panic_with_hook (0x559d11c4bda8)
             at src/libstd/panicking.rs:482
   2: continue_panic_fmt (0x559d11c4b841)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x559d11c4b725)
   4: panic_fmt (0x559d11c65dac)
             at src/libcore/panicking.rs:85
   5: expect_failed (0x559d11c65e16)
             at src/libcore/option.rs:1038
   6: <grin_servers::common::adapters::ChainToPoolAndNetAdapter as grin_chain::types::ChainAdapter>::block_accepted::h0bff065b3b8ff0cd (0x559d11666d21)
   7: grin_chain::chain::Chain::process_block_single::hcc4d536fd725bd6a (0x559d11a0146c)
   8: grin_chain::chain::Chain::process_block::h4622588f45f5087f (0x559d11a00237)
   9: grin_servers::mining::test_miner::Miner::run_loop::h0d8d901df4af838c (0x559d116e1e1a)
  10: std::sys_common::backtrace::__rust_begin_short_backtrace::hc55456c267de6117 (0x559d1167f034)
  11: std::panicking::try::do_call::h08153d29fd437130 (0x559d116b25b3)
  12: __rust_maybe_catch_panic (0x559d11c51cd9)
             at src/libpanic_unwind/lib.rs:87
  13: <F as alloc::boxed::FnBox<A>>::call_box::hf5987a689c1e0ddf (0x559d116c84c7)
  14: call_once<(),()> (0x559d11c5104d)
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/boxed.rs:759
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:81
  15: start_thread (0x7f6f4a2b6fa2)
  16: clone (0x7f6f4a1cb4ce)
  17: <unknown> (0x0)


Thread 'test_miner' panicked with message:
"Failed to upgrade weak ref to our peers."
See /root/grin/user/grin-server.log for further details.
20190613 14:21:09.744 WARN grin::cmd::server - Shutdown complete.

```

**Comment by quentinlesceller** [comment]
The whole test suite is going to be revamped through #3295.
