### ISSUE TITLE
2.0.0.beta1 floonet crashes if chain data is present

### ISSUE THREAD

**Issue by PositronicBrain** [mimblewimble/grin#2926]
When upgrading from 1.1.0 to 2.0.0.beta1 Grin server crashes. It works again if chain_data is removed.

Stack trace:
```
20190627 09:08:13.134 INFO grin_util::logger - log4rs is initialized, file level: Trace, stdout level: Trace, min. level: Trace
20190627 09:08:13.134 INFO grin - Using configuration file at /home/federico/.grin/floo/grin-server.toml
20190627 09:08:13.134 INFO grin - This is Grin version 2.0.0-beta.1 (git v2.0.0-beta.1), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190627 09:08:13.134 DEBUG grin - Built with profile "release", features "".
20190627 09:08:13.134 WARN grin::cmd::server - Starting GRIN w/o UI...
20190627 09:08:13.144 INFO grin_servers::grin::server - Starting server, genesis block: edc758c1370d
20190627 09:08:13.151 DEBUG grin_store::lmdb - DB Mapsize for /home/federico/.grin/floo/chain_data/lmdb is 549755813888
20190627 09:08:13.153 DEBUG grin_store::leaf_set - bitmap 78529 pos (65608 bytes)
20190627 09:08:13.390 DEBUG grin_store::prune_list - bitmap 29248 pos (34338 bytes), pruned_cache 125094 pos (39879 bytes), shift_cache 29248, leaf_shift_cache 29248
20190627 09:08:13.390 DEBUG grin_store::leaf_set - bitmap 78529 pos (65608 bytes)
20190627 09:08:13.616 DEBUG grin_store::prune_list - bitmap 29248 pos (34338 bytes), pruned_cache 125094 pos (39879 bytes), shift_cache 29248, leaf_shift_cache 29248
20190627 09:08:13.616 TRACE grin_store::lmdb - DB map size: 549755813888
20190627 09:08:13.616 TRACE grin_store::lmdb - Space used: 213454848
20190627 09:08:13.616 TRACE grin_store::lmdb - Space remaining: 549542359040
20190627 09:08:13.616 TRACE grin_store::lmdb - Percent used: 0.0004  Percent threshold: 0.9000
20190627 09:08:13.616 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
20190627 09:08:13.711 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: SerErr("invalid block version")

Store Error: SerErr("invalid block version"), reason: Serialization Error })': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h407ca12626e3bc50 (0x560ee45a8540)
   1: rust_panic_with_hook (0x560ee46d91b8)
             at src/libstd/panicking.rs:478
   2: continue_panic_fmt (0x560ee46d8c51)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x560ee46d8b35)
   4: panic_fmt (0x560ee46f2b4c)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h9708b2d1d8976fc2 (0x560ee3f37a88)
   6: grin::cmd::server::start_server::h5926bf86043f5205 (0x560ee3f394f8)
   7: grin::cmd::server::server_command::h75bc9cc4dbae941c (0x560ee3f39fb2)
   8: grin::real_main::had3ad3f948ca287a (0x560ee3f6c241)
   9: grin::main::hcf76114cd6498f05 (0x560ee3f6ae25)
  10: std::rt::lang_start::{{closure}}::h01c0b09074366bd2 (0x560ee3f46352)
  11: {{closure}} (0x560ee46d8ad2)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic (0x560ee46dea39)
             at src/libpanic_unwind/lib.rs:87
  13: try<i32,closure> (0x560ee46d95dc)
             at src/libstd/panicking.rs:272
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  14: main (0x560ee3f6f4a1)
  15: __libc_start_main (0x7f33ea14aee2)
  16: _start (0x560ee3f2641d)
  17: <unknown> (0x0)


Thread 'main' panicked with message:
"called `Result::unwrap()` on an `Err` value: Chain(Error { inner: SerErr("invalid block version")

Store Error: SerErr("invalid block version"), reason: Serialization Error })"
```

**Comment by antiochp** [comment]
Hmm `invalid block version`. Was this node part of the "private floonet" fork test?

**Comment by PositronicBrain** [comment]
I am using the standard floonet, but I only upgraded after the hard fork and in the meanwhile there were a few new blocks mined on the old chain

**Comment by PositronicBrain** [comment]
Just tested 2.0.0.beta2. Same problem.
```
20190628 18:21:36.298 INFO grin_util::logger - log4rs is initialized, file level: Trace, stdout level: Trace, min. level: Trace
20190628 18:21:36.298 INFO grin - Using configuration file at /home/federico/.grin/floo/grin-server.toml
20190628 18:21:36.298 INFO grin - This is Grin version 2.0.0-beta.2 (git 2.0.0-beta.2), built for x86_64-unknown-linux-gnu by rustc 1.35.0 (3c235d560 2019-05-20).
20190628 18:21:36.298 DEBUG grin - Built with profile "release", features "".
20190628 18:21:36.298 WARN grin::cmd::server - Starting GRIN in UI mode...
20190628 18:21:36.298 INFO grin_servers::grin::server - Starting server, genesis block: edc758c1370d
20190628 18:21:36.298 DEBUG grin_store::lmdb - DB Mapsize for /home/federico/.grin/floo/chain_data/lmdb is 549755813888
20190628 18:21:36.299 DEBUG grin_store::leaf_set - bitmap 78507 pos (65608 bytes)
20190628 18:21:36.541 DEBUG grin_store::prune_list - bitmap 29248 pos (34338 bytes), pruned_cache 125094 pos (39879 bytes), shift_cache 29248, leaf_shift_cache 29248
20190628 18:21:36.541 DEBUG grin_store::leaf_set - bitmap 78507 pos (65608 bytes)
20190628 18:21:36.780 DEBUG grin_store::prune_list - bitmap 29248 pos (34338 bytes), pruned_cache 125094 pos (39879 bytes), shift_cache 29248, leaf_shift_cache 29248
20190628 18:21:36.780 TRACE grin_store::lmdb - DB map size: 549755813888
20190628 18:21:36.780 TRACE grin_store::lmdb - Space used: 213454848
20190628 18:21:36.780 TRACE grin_store::lmdb - Space remaining: 549542359040
20190628 18:21:36.780 TRACE grin_store::lmdb - Percent used: 0.0004  Percent threshold: 0.9000
20190628 18:21:36.780 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
20190628 18:21:36.813 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: SerErr("invalid block version")

Store Error: SerErr("invalid block version"), reason: Serialization Error })': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h1efdc20708d8e013 (0x564e4a7d66c1)
   1: rust_panic_with_hook (0x564e4a907aa9)
             at src/libstd/panicking.rs:478
   2: continue_panic_fmt (0x564e4a907542)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x564e4a907426)
   4: panic_fmt (0x564e4a92143d)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h46d5a9249fe73ffd (0x564e4a155f89)
   6: grin::cmd::server::start_server::hd8e9bcfdf6a22484 (0x564e4a1585c7)
   7: grin::cmd::server::server_command::h9fbaa192691a6a70 (0x564e4a15e223)
   8: grin::real_main::h0a04d9981822bd84 (0x564e4a189cf2)
   9: grin::main::hcd815e69b6f352c5 (0x564e4a1888d6)
  10: std::rt::lang_start::{{closure}}::hff1bb98b880024b0 (0x564e4a164f03)
  11: {{closure}} (0x564e4a9073c3)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic (0x564e4a90d32a)
             at src/libpanic_unwind/lib.rs:87
  13: try<i32,closure> (0x564e4a907ecd)
             at src/libstd/panicking.rs:272
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  14: main (0x564e4a18cf52)
  15: __libc_start_main (0x7fbbfbf91ee3)
  16: _start (0x564e4a14541e)
  17: <unknown> (0x0)
```

**Comment by antiochp** [comment]
Yes the problem is you have an invalid block in your db (from the floonet HF).
A miner running pre-HF code mined a block _after_ the HF block height.
Your node was running pre-HF code and accepted this block as valid.

The only way to resolve this will be a resync from scratch to clear your db out.

**Comment by PositronicBrain** [comment]
It is annoying because I have a full archive, is there any way to salvage it?

**Comment by antiochp** [comment]
If you are comfortable making a change to the code and recompiling then you _might_ be able to get your node past this point.
I'm not recommending you do this but its a possible option. And only for `floonet`.

https://github.com/mimblewimble/grin/blob/e6bdc5987cab272cb47a54a992947bc9cf88d6a5/core/src/consensus.rs#L133-L148

The code here checks the header version if the chain type is floonet.
If you modify this locally to simply return true then it should allow you to sync past this point on floonet.

```
global::ChainTypes::Floonet => {
    true
}
```

I'm pretty sure you would only need to sync once with these temporary code changes. And once you got past that point you should be good. I can't guarantee that though.

You would want to verify that you sync'd to the correct `floonet` chain before relying on this for anything.

**Comment by PositronicBrain** [comment]
It does not work. It starts running but the chain height does not increase, and the node proceeds to ban all the peers one after the other until there are no connections left. I am not sure of the reason, but I think this line of the log maybe the relevant one.

```
20190703 16:52:23.284 DEBUG grin_p2p::peers - Banning peer 35.247.29.132:3414 20190703 16:52:23.284 DEBUG grin_p2p::peers - ban reason FraudHeight was sent to 35.247.29.132:3414 20190703 16:52:23.284 DEBUG grin_p2p::peer - Stopping peer PeerAddr(V4(35.247.29.132:3414)) 20190703 16:52:23.284 INFO grin_servers::grin::sync::header_sync - sync: ban a fraud peer: 35.247.29.132:3414, claimed height: 198255, total difficulty: 16889248010 20190703 16:52:23.288 DEBUG grin_p2p::conn - Shutting down connection with 35.247.29.132:44512
```

**Comment by antiochp** [comment]
Oh that's frustrating.
Your best bet may be ping the dev gitter channel and see if anyone has a full floonet db that they would be willing to export.
I believe lmdb has export/import functionality - but it is not something I have used personally.

* obtain a full floonet db export
* import it locally into a fresh floonet node
* ensure `archive` mode is enabled
* run a fast sync on that node (historical db entries should remain untouched)
* end result - you _should_ have a full archive node up and running

Note: I'm not sure if anybody has actually attempted this process before.
I know various people have asked about it previously on gitter.

Let me know if this actually works.

**Comment by quentinlesceller** [comment]
Closing due to lack of activity.
