### ISSUE TITLE
[Server] thread '<unnamed>' panicked at 'Box<Any>', grin/src/miner.rs

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin#306]
Log below:

````
Nov 18 12:43:08.466 INFO (Server ID: Port 13414) Found valid proof of work, adding block 51ac4d5f.
Nov 18 12:43:08.467 INFO Starting validation pipeline for block 51ac4d5f at 2543 with 0 inputs and 1 outputs.
Nov 18 12:43:08.467 DEBG Validating block with cuckoo size 16
Nov 18 12:43:08.468 DEBG Starting new sumtree extension.
Nov 18 12:43:08.500 DEBG Block at 2543 with hash 51ac4d5f is valid, going to save and append.
Nov 18 12:43:08.500 INFO Updated head to 51ac4d5f at 2543.
Nov 18 12:43:08.500 DEBG Committing sumtree extension.
Nov 18 12:43:08.512 DEBG Sumtree extension done.
Nov 18 12:43:08.515 DEBG resetting key_id in miner to None
Nov 18 12:43:08.515 DEBG in miner loop...
Nov 18 12:43:08.619 DEBG block_fees here: BlockFees { fees: 0, height: 2544, key_id: Some(Identifier(9f36c34f8c14c71b8558)) }
Nov 18 12:43:08.620 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 499
Nov 18 12:43:08.649 DEBG Starting new sumtree extension.
Nov 18 12:43:08.649 DEBG Error returned, discarding sumtree extension.
Nov 18 12:43:08.728 DEBG block_fees here: BlockFees { fees: 0, height: 2544, key_id: Some(Identifier(4054bc82c309fc896a34)) }
Nov 18 12:43:08.728 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 499
Nov 18 12:43:08.759 DEBG Starting new sumtree extension.
thread '<unnamed>' panicked at 'Box<Any>', grin/src/miner.rs:597:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Nov 18 12:43:08.760 DEBG Error returned, discarding sumtree extension.
Nov 18 12:43:08.886 DEBG Received block 51ac4d5f at 2543 from network, going to process.
Nov 18 12:43:08.887 INFO Starting validation pipeline for block 51ac4d5f at 2543 with 0 inputs and 1 outputs.
Nov 18 12:43:08.887 DEBG Block 51ac4d5f at 2543 is unfit at this time: already known
Nov 18 12:43:08.887 DEBG Block 51ac4d5f refused by chain: Unfit("already known")
Nov 18 12:43:08.972 DEBG Received block 51ac4d5f at 2543 from network, going to process.
Nov 18 12:43:08.972 INFO Starting validation pipeline for block 51ac4d5f at 2543 with 0 inputs and 1 outputs.
Nov 18 12:43:08.973 DEBG Block 51ac4d5f at 2543 is unfit at this time: already known
Nov 18 12:43:08.973 DEBG Block 51ac4d5f refused by chain: Unfit("already known")
Nov 18 12:43:09.047 DEBG Received block 51ac4d5f at 2543 from network, going to process.
Nov 18 12:43:09.048 INFO Starting validation pipeline for block 51ac4d5f at 2543 with 0 inputs and 1 outputs.
Nov 18 12:43:09.048 DEBG Block 51ac4d5f at 2543 is unfit at this time: already known
Nov 18 12:43:09.048 DEBG Block 51ac4d5f refused by chain: Unfit("already known")
Nov 18 12:43:09.070 DEBG Received block 51ac4d5f at 2543 from network, going to process.
Nov 18 12:43:09.070 INFO Starting validation pipeline for block 51ac4d5f at 2543 with 0 inputs and 1 outputs.
Nov 18 12:43:09.071 DEBG Block 51ac4d5f at 2543 is unfit at this time: already known
Nov 18 12:43:09.071 DEBG Block 51ac4d5f refused by chain: Unfit("already known")
Nov 18 12:43:09.525 DEBG Received block 51ac4d5f at 2543 from network, going to process.
Nov 18 12:43:09.526 INFO Starting validation pipeline for block 51ac4d5f at 2543 with 0 inputs and 1 outputs.
Nov 18 12:43:09.526 DEBG Block 51ac4d5f at 2543 is unfit at this time: already known
Nov 18 12:43:09.526 DEBG Block 51ac4d5f refused by chain: Unfit("already known")
Nov 18 12:43:14.702 DEBG monitoring peers (7)
````

**Comment by photis** [comment]
I tried again with a backtrace this time, got the same error
````
$ RUST_BACKTRACE=1 grin server --mine run
Nov 18 12:52:10.606 INFO Using configuration file at: /home/bitman/Projects/mimble/server/grin.toml
Nov 18 12:52:10.606 INFO Starting the Grin server...
Nov 18 12:52:10.656 WARN P2P server started on 0.0.0.0:13414
Nov 18 12:52:10.657 INFO Starting rest apis at: 0.0.0.0:13413
Nov 18 12:52:10.657 INFO Sync: starting sync
Nov 18 12:52:10.658 WARN Grin server started.
Nov 18 12:52:10.659 INFO Starting HTTP API server at 0.0.0.0:13413.
Nov 18 12:52:10.662 DEBG Connecting to seed: 192.241.168.77:13414.
Nov 18 12:52:10.662 DEBG Connecting to seed: 165.227.63.166:13414.
Nov 18 12:52:10.663 DEBG Connecting to seed: 138.68.30.5:13414.
Nov 18 12:52:10.664 DEBG Connecting to seed: 54.175.216.250:13414.
Nov 18 12:52:10.664 DEBG Connecting to seed: 174.138.116.153:13414.
Nov 18 12:52:10.664 DEBG Connecting to seed: 138.68.178.20:13414.
Nov 18 12:52:10.665 DEBG Connecting to seed: 109.74.202.16:13414.
Nov 18 12:52:10.665 DEBG New peer address to connect to: 192.241.168.77:13414.
Nov 18 12:52:10.666 DEBG 0.0.0.0:13414 connecting to 192.241.168.77:13414
Nov 18 12:52:10.837 DEBG handshake connect with nonce - 4269344756659489958, sender - V4(0.0.0.0:13414), receiver - V4(192.241.168.77:13414)
Nov 18 12:52:11.311 INFO Connected to peer PeerInfo { capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", version: 1, addr: V4(192.241.168.77:13414), total_difficulty: Difficulty { num: 9135460 } }
Nov 18 12:52:11.312 DEBG Saving newly connected peer 192.241.168.77:13414.
Nov 18 12:52:11.312 DEBG saving peer to store PeerData { addr: V4(192.241.168.77:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Healthy }
Nov 18 12:52:11.314 DEBG Asking 192.241.168.77:13414 for more peers.
Nov 18 12:52:11.314 DEBG New peer address to connect to: 165.227.63.166:13414.
Nov 18 12:52:11.315 DEBG 0.0.0.0:13414 connecting to 165.227.63.166:13414
Nov 18 12:52:11.497 DEBG Received 122 peer addrs, saving.
Nov 18 12:52:11.588 DEBG handshake connect with nonce - 14975839918075040268, sender - V4(0.0.0.0:13414), receiver - V4(165.227.63.166:13414)
Nov 18 12:52:12.386 INFO Connected to peer PeerInfo { capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", version: 1, addr: V4(165.227.63.166:13414), total_difficulty: Difficulty { num: 9135460 } }
Nov 18 12:52:12.386 DEBG Saving newly connected peer 165.227.63.166:13414.
Nov 18 12:52:12.387 DEBG saving peer to store PeerData { addr: V4(165.227.63.166:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Healthy }
Nov 18 12:52:12.389 DEBG Asking 165.227.63.166:13414 for more peers.
Nov 18 12:52:12.390 DEBG New peer address to connect to: 138.68.30.5:13414.
Nov 18 12:52:12.390 DEBG 0.0.0.0:13414 connecting to 138.68.30.5:13414
Nov 18 12:52:12.667 DEBG handshake connect with nonce - 14900713374085975888, sender - V4(0.0.0.0:13414), receiver - V4(138.68.30.5:13414)
Nov 18 12:52:12.682 DEBG Received 54 peer addrs, saving.
Nov 18 12:52:13.521 INFO Connected to peer PeerInfo { capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", version: 1, addr: V4(138.68.30.5:13414), total_difficulty: Difficulty { num: 9135460 } }
Nov 18 12:52:13.521 DEBG Saving newly connected peer 138.68.30.5:13414.
Nov 18 12:52:13.522 DEBG saving peer to store PeerData { addr: V4(138.68.30.5:13414), capabilities: FULL_HIST | UTXO_HIST | PEER_LIST | FULL_NODE, user_agent: "MW/Grin 0.1", flags: Healthy }
Nov 18 12:52:13.524 DEBG Asking 138.68.30.5:13414 for more peers.
Nov 18 12:52:13.525 DEBG New peer address to connect to: 54.175.216.250:13414.
Nov 18 12:52:13.525 DEBG 0.0.0.0:13414 connecting to 54.175.216.250:13414
Nov 18 12:52:13.783 DEBG Received 33 peer addrs, saving.
Nov 18 12:52:20.656 DEBG monitoring peers (3)
Nov 18 12:52:20.658 DEBG Got 47 more peers from db, trying to connect.
Nov 18 12:52:20.666 DEBG Added 0 full block hashes to download.
Nov 18 12:52:20.666 INFO Starting sync loop.
Nov 18 12:52:20.666 DEBG Sync: peer 9135460 vs us 9126779
Nov 18 12:52:20.667 DEBG Sync: blocks to download 0, block downloading 0
Nov 18 12:52:20.667 DEBG Loc heights: [2552, 2550, 2548, 2544, 2536, 2520, 2488, 2424, 2296, 2040, 0]
Nov 18 12:52:20.766 DEBG Asking peer 138.68.30.5:13414 for more block headers, locator: [5f9a4fb7, 4862c040, c5316fd8, 14cdcdc0, e65f0be3, e597635c, 76da7c1c, 75f9e6c7, 2828d6b0, 080cd6b1, e17ea64f]
Nov 18 12:52:21.082 INFO Received 1 block headers
Nov 18 12:52:21.083 INFO Starting validation pipeline for block header 7b47646c at 2553.
Nov 18 12:52:21.083 DEBG Validating block with cuckoo size 16
Nov 18 12:52:21.092 INFO Updated block header head to 7b47646c at 2553.
Nov 18 12:52:21.093 INFO Added 1 headers to the header chain.
Nov 18 12:52:22.766 DEBG Sync: peer 9135460 vs us 9135460
Nov 18 12:52:22.766 DEBG Sync: blocks to download 1, block downloading 0
Nov 18 12:52:22.766 DEBG Requesting block 7b47646c from peer 138.68.30.5:13414.
Nov 18 12:52:22.766 DEBG Requested 1 full blocks to download, total left: 0. Current list: [BlockDownload { hash: 7b47646c, start_time: Instant { tv_sec: 6380, tv_nsec: 33243545 }, retries: 0 }].
Nov 18 12:52:23.021 DEBG Received block 7b47646c at 2553 from network, going to process.
Nov 18 12:52:23.022 INFO Starting validation pipeline for block 7b47646c at 2553 with 0 inputs and 1 outputs.
Nov 18 12:52:23.022 DEBG Validating block with cuckoo size 16
Nov 18 12:52:23.033 DEBG Starting new sumtree extension.
Nov 18 12:52:23.127 DEBG Block at 2553 with hash 7b47646c is valid, going to save and append.
Nov 18 12:52:23.127 INFO Updated head to 7b47646c at 2553.
Nov 18 12:52:23.127 DEBG Committing sumtree extension.
Nov 18 12:52:23.138 DEBG Sumtree extension done.
Nov 18 12:52:24.767 DEBG Sync: peer 9135460 vs us 9135460
Nov 18 12:52:24.767 DEBG Sync: blocks to download 0, block downloading 0
Nov 18 12:52:24.768 INFO Sync: done.
Nov 18 12:52:25.658 INFO (Server ID: Port 13414) Starting miner loop.
Nov 18 12:52:25.900 INFO Mining plugin 0 - /home/bitman/Projects/mimble/grin/target/debug/plugins/mean_compat_cpu_16.cuckooplugin
Nov 18 12:52:25.900 DEBG in miner loop...
Nov 18 12:52:25.979 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(aed62d10b8c9c3fe6524)) }
Nov 18 12:52:25.979 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.009 DEBG Starting new sumtree extension.
Nov 18 12:52:26.009 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.088 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(bf23e032e72fdcb28779)) }
Nov 18 12:52:26.088 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.118 DEBG Starting new sumtree extension.
Nov 18 12:52:26.118 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.118 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:26.197 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(95a517101539971e0def)) }
Nov 18 12:52:26.197 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.227 DEBG Starting new sumtree extension.
Nov 18 12:52:26.227 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.227 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:26.306 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(e73e7cb572bf8a2428cb)) }
Nov 18 12:52:26.307 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.337 DEBG Starting new sumtree extension.
Nov 18 12:52:26.337 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.337 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:26.418 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(53f10eb27a9077703abf)) }
Nov 18 12:52:26.418 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.449 DEBG Starting new sumtree extension.
Nov 18 12:52:26.449 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.449 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:26.530 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(b83bea57b4b7cf031988)) }
Nov 18 12:52:26.530 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.560 DEBG Starting new sumtree extension.
Nov 18 12:52:26.560 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.561 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:26.642 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(c687e4357038fe1b41f0)) }
Nov 18 12:52:26.642 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.672 DEBG Starting new sumtree extension.
Nov 18 12:52:26.672 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.672 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:26.754 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(54d96d83c267f60d9cb3)) }
Nov 18 12:52:26.754 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.785 DEBG Starting new sumtree extension.
Nov 18 12:52:26.785 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.785 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:26.867 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(902aef87e53e6704adf3)) }
Nov 18 12:52:26.867 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:26.898 DEBG Starting new sumtree extension.
Nov 18 12:52:26.898 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:26.898 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:26.981 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(3957cab0f90332556f1f)) }
Nov 18 12:52:26.981 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:27.011 DEBG Starting new sumtree extension.
Nov 18 12:52:27.011 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:27.011 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:27.093 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(9e9c34fc03d13ae16551)) }
Nov 18 12:52:27.094 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:27.124 DEBG Starting new sumtree extension.
Nov 18 12:52:27.124 DEBG Error returned, discarding sumtree extension.
Nov 18 12:52:27.124 WARN Duplicate commit for potential coinbase detected. Trying next derivation.
Nov 18 12:52:27.208 DEBG block_fees here: BlockFees { fees: 0, height: 2554, key_id: Some(Identifier(2a12a3518f29f535382b)) }
Nov 18 12:52:27.208 DEBG (Server ID: Port 13414) Built new block with 0 inputs and 1 outputs, difficulty: 503
Nov 18 12:52:27.238 DEBG Starting new sumtree extension.
thread '<unnamed>' panicked at 'Box<Any>', grin/src/miner.rs:597:13
Nov 18 12:52:27.239 DEBG Error returned, discarding sumtree extension.
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: grin_grin::miner::Miner::build_block
             at grin/src/miner.rs:597
   7: grin_grin::miner::Miner::run_loop
             at grin/src/miner.rs:452
   8: grin_grin::server::Server::start_miner::{{closure}}
             at grin/src/server.rs:212
Nov 18 12:52:30.656 DEBG monitoring peers (3)
Nov 18 12:52:30.658 DEBG Got 47 more peers from db, trying to connect.
Nov 18 12:52:37.764 DEBG Received block c1d161cd at 2554 from network, going to process.
Nov 18 12:52:37.764 INFO Starting validation pipeline for block c1d161cd at 2554 with 0 inputs and 1 outputs.
Nov 18 12:52:37.765 DEBG Validating block with cuckoo size 16
Nov 18 12:52:37.773 DEBG Starting new sumtree extension.
Nov 18 12:52:37.813 DEBG Block at 2554 with hash c1d161cd is valid, going to save and append.
Nov 18 12:52:37.814 INFO Updated head to c1d161cd at 2554.
Nov 18 12:52:37.814 DEBG Committing sumtree extension.
Nov 18 12:52:37.824 DEBG Sumtree extension done.
````

**Comment by ignopeverell** [comment]
Can you still reproduce this? Unfortunately the underlying error is a bit eaten and there isn't enough details. I've added another log statement that would help diagnose.

**Comment by photis** [comment]
Unfortunately I've git pulled to the latest version now, it doesn't happen anymore.

**Comment by ignopeverell** [comment]
I'll close this until we can reproduce then. Thanks!

**Comment by sesam** [comment]
Possibly related; a strange Box<Any> error pasted below.

I can't even begin to guess how Box got in there. Bubbled up from deep below somewhere, not much other options.

There aren't many Box<...something in the codebase though, so maybe instrument more of those? I can do, but prefer guidance before I try anything.

// IP:port taken from gitter Lobby chat, and was giving HTTP 200 right before the `grin send` below.

RUST_BACKTRACE=1 target/debug/grin wallet send -s smallest -d 185.8.164.22:13415  2.71828
Nov 19 01:01:35.534 INFO Using configuration file at: [...]/grin.toml
Nov 19 01:01:35.547 DEBG Using wallet seed file at: ./wallet.seed
Nov 19 01:01:35.630 DEBG Refreshing wallet outputs
thread 'main' panicked at 'Box<Any>', src/bin/grin.rs:443:14
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: grin::wallet_command
   6: grin::main
   7: __rust_maybe_catch_panic
   8: std::rt::lang_start
   9: main
