### ISSUE TITLE
'MDB_MAP_FULL: Environment mapsize limit reached' for grin (server) v2.1.0

### ISSUE THREAD

**Issue by photis** [mimblewimble/grin#3099]
Pulled the latest grin server from github, build as usual (replacing v2.1.0 beta 3)
Upon startup I get the above error, see log below. I re-built after a cargo clean with the same result.

```
20191024 16:42:30.199 INFO grin_util::logger - log4rs is initialized, file level: Debug, stdout level: Warn, min. level: Debug
20191024 16:42:30.200 INFO grin - Using configuration file at /home/photis/.grin/main/grin-server.toml
20191024 16:42:30.200 INFO grin - This is Grin version 2.1.0 (git v2.1.0), built for x86_64-unknown-linux-gnu by rustc 1.38.0 (625451e37 2019-09-23).
20191024 16:42:30.200 DEBUG grin - Built with profile "release", features "".
20191024 16:42:30.200 WARN grin::cmd::server - Starting GRIN in UI mode...
20191024 16:42:30.204 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20191024 16:42:30.206 DEBUG grin_store::lmdb - DB Mapsize for /home/photis/.grin/main/chain_data/lmdb is 1342177280
20191024 16:42:30.212 DEBUG grin_store::leaf_set - bitmap 111605 pos (212678 bytes)
20191024 16:42:31.420 DEBUG grin_store::prune_list - bitmap 292847 pos (421420 bytes), pruned_cache 3752817 pos (487255 bytes), shift_cache 292847, leaf_shift_cache 292847
20191024 16:42:31.427 DEBUG grin_store::leaf_set - bitmap 111605 pos (212678 bytes)
20191024 16:42:32.590 DEBUG grin_store::prune_list - bitmap 292847 pos (421420 bytes), pruned_cache 3752817 pos (487255 bytes), shift_cache 292847, leaf_shift_cache 292847
20191024 16:42:32.637 DEBUG grin_chain::txhashset::txhashset - attempting to open kernel PMMR using ProtocolVersion(2) - FAIL (verify failed)
20191024 16:42:32.661 DEBUG grin_chain::txhashset::txhashset - attempting to open kernel PMMR using ProtocolVersion(1) - SUCCESS
20191024 16:42:32.671 DEBUG grin_chain::txhashset::txhashset - Rewind header extension to 0000038bef42 at 402977 from 0000038bef42 at 402977
20191024 16:42:32.671 DEBUG grin_chain::txhashset::txhashset - Rewind extension to 0000038bef42 at 402977 from 0000038bef42 at 402977
20191024 16:42:32.686 DEBUG grin_chain::chain - init: rewinding and validating before we start... 0000038bef42 at 402977
20191024 16:42:32.756 DEBUG grin_chain::chain - init: head: 1193352373328337 @ 402977 [0000038bef42]
20191024 16:42:32.756 DEBUG grin_chain::chain - init: header_head: 1193352373328337 @ 402977 [0000038bef42]
20191024 16:42:32.756 DEBUG grin_chain::chain - init: sync_head: 1193352373328337 @ 402977 [0000038bef42]
20191024 16:42:45.659 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: LmdbErr(Error::Code(-30792, 'MDB_MAP_FULL: Environment mapsize limit reached'))

Store Error: LmdbErr(Error::Code(-30792, 'MDB_MAP_FULL: Environment mapsize limit reached')), reason: LMDB error })': src/libcore/result.rs:1084stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h80009c0a29eb6333 (0x56239bda2ce1)
   1: std::panicking::rust_panic_with_hook::h92f98b46e22f14ed (0x56239beda016)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::h25abfbb4e5b7043a (0x56239bed9ab2)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x56239bed9996)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h7e9f94035af782b3 (0x56239bef7aed)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::hf7591c1dd9412006 (0x56239bef7be7)
             at src/libcore/result.rs:1084
   6: grin::cmd::server::start_server::hf58e5b70e1b81a47 (0x56239b73ed89)
   7: grin::cmd::server::server_command::hcdf35ffd64ad40f7 (0x56239b73f5d6)
   8: grin::real_main::h2c195aa7d1b83c3f (0x56239b770534)
   9: grin::main::h1af3f469c3b854fd (0x56239b76ed86)
  10: std::rt::lang_start::{{closure}}::hfc7a4228232cd6d9 (0x56239b74ed43)
  11: std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955 (0x56239bed9933)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h9440ccd4dc467eaa
             at src/libstd/panicking.rs:296
  12: __rust_maybe_catch_panic (0x56239bedf5ba)
             at src/libpanic_unwind/lib.rs:80
  13: std::panicking::try::hc046e7ee42ee744f (0x56239beda43d)
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind::h27dfc457c200aee0
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::hea1b49a567afe309
             at src/libstd/rt.rs:48
  14: main (0x56239b770b42)
  15: __libc_start_main (0x7f9301e16b97)
  16: _start (0x56239b722bfa)
  17: <unknown> (0x0)
```

Operating system Ubuntu Linux 18.04.1
Kernel and CPU Linux 4.15.0-33-generic on x86_64
Processor information Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, 8 cores 

gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
rustc 1.38.0 (625451e37 2019-09-23)

**Comment by codeb2cc** [comment]
Same error here with TRACE log:

```
20191028 03:20:14.138 TRACE grin_store::lmdb - DB map size: 1879048192
20191028 03:20:14.138 TRACE grin_store::lmdb - Space used: 1489543168
20191028 03:20:14.138 TRACE grin_store::lmdb - Space remaining: 389505024
20191028 03:20:14.138 TRACE grin_store::lmdb - Percent used: 0.7927  Percent threshold: 0.9000
20191028 03:20:14.138 TRACE grin_store::lmdb - Resize threshold not met (percent-based)
20191028 03:20:17.128 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: LmdbErr(Error::Code(-30792, 'MDB_MAP_FULL: Environment mapsize limit reached'))
```

**Comment by codeb2cc** [comment]
The problem is lmdb has not been resized while migrating in `chain.migrate_db_v1_v2`. I think there's no quick fix since the batch is fetch once and  `batch.migrate_block` in an iteration: 

```
         fn migrate_db_v1_v2(&self) -> Result<(), Error> {
                 let store_v1 = self.store.with_version(ProtocolVersion(1));
                 let batch = store_v1.batch()?;
                 for (_, block) in batch.blocks_iter()? {                   
                         batch.migrate_block(&block, ProtocolVersion(2))?;
                 }        
                 batch.commit()?;
                 Ok(())   
         }                
```
But we do have a workaround. We can temporarily change the lmdb resize threshold to 50% to make sure we have enough space during the migration. After the migration is finish we can use the origin one to continue to run grin server.

```
diff --git a/store/src/lmdb.rs b/store/src/lmdb.rs
index 71eb85c9..9db30c32 100644
--- a/store/src/lmdb.rs
+++ b/store/src/lmdb.rs
@@ -27,10 +27,10 @@ use crate::util::{RwLock, RwLockReadGuard};
 
 /// number of bytes to grow the database by when needed
 pub const ALLOC_CHUNK_SIZE: usize = 134_217_728; //128 MB
-const RESIZE_PERCENT: f32 = 0.9;
+const RESIZE_PERCENT: f32 = 0.5;
 /// Want to ensure that each resize gives us at least this %
 /// of total space free
-const RESIZE_MIN_TARGET_PERCENT: f32 = 0.65;
+const RESIZE_MIN_TARGET_PERCENT: f32 = 0.5;
 
 /// Main error type for this lmdb
 #[derive(Clone, Eq, PartialEq, Debug, Fail)]
```

**Comment by antiochp** [comment]
> The problem is lmdb has not been resized while migrating in chain.migrate_db_v1_v2.

Oh good catch. Let me take a look over this as well (I'm to blame for `migrate_db_v1_v2`).

**Comment by antiochp** [comment]
Yeah this is kind of nasty. We can't resize _during_ a batch as it involves actually rewriting the db data files. And the "migrate" batch can be large.
If _any_ batch is in excess of 10% of the overall db size then the 90% resize target fails.

**Comment by antiochp** [comment]
Paging @yeastplume - thoughts on this?

**Comment by antiochp** [comment]
Maybe we can make `needs_resize()` more flexible and allow a percentage to be passed in.
Then we can explicitly do a `needs_resize() + do_resize()` prior to starting the db migration as @codeb2cc suggests. Less of a workaround and more of a pre-emptive resize before starting a potentially large db batch.

**Comment by photis** [comment]
Thank you guys for looking into this. For the moment I have resorted to deleting and re-building chain_data. That worked. I was surprised though that not more people have reported running into this snag.

**Comment by yeastplume** [comment]
> Maybe we can make `needs_resize()` more flexible and allow a percentage to be passed in.
> Then we can explicitly do a `needs_resize() + do_resize()` prior to starting the db migration as @codeb2cc suggests. Less of a workaround and more of a pre-emptive resize before starting a potentially large db batch.

I think that's a relatively okay quick-fix. There's nothing magical about the

**Comment by antiochp** [comment]
> I was surprised though that not more people have reported running into this snag.

I'm guessing this is a particular edge case where the db needs migrating and we are almost at the limit of the current db size. So it needs to be a "legacy" db at some particular block height.

**Comment by photis** [comment]
Ah, okay, yes, makes sense. I had been running grin since January and my server crashed around mid September. I had no access until a few weeks ago when I could remedy the situation and decided to upgrade all grin components as I was at it anyway. 
Thanks for taking the time to explain.

**Comment by xiaojay** [comment]
same issue when i try to run grin3 on chain data which previous synced by a archive mode grin2 node
