### ISSUE TITLE
grin v5.1.0 doesn't work on a Linux (Ubuntu)

### ISSUE THREAD

**Issue by gagarin55** [mimblewimble/grin#3676]
Just downloaded grin v5.1.0 from official grin.mw. Trying `./grin` and getting nothing. Log shows:

```
20211223 15:48:36.350 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20211223 15:48:36.350 INFO grin - Using configuration file at /home/user/.grin/main/grin-server.toml
20211223 15:48:36.350 INFO grin - This is Grin version 5.1.0 (git v5.1.0), built for x86_64-unknown-linux-gnu by rustc 1.51.0 (2fd73fabe 2021-03-23).
20211223 15:48:36.350 INFO grin - Chain: Mainnet
20211223 15:48:36.350 INFO grin - Accept Fee Base: 500000
20211223 15:48:36.350 INFO grin - Future Time Limit: 300
20211223 15:48:36.350 INFO grin - Feature: NRD kernel enabled: false
20211223 15:48:36.350 WARN grin::cmd::server - Starting GRIN in UI mode...
20211223 15:48:36.350 INFO grin_servers::grin::server - Starting server, genesis block: 40adad0aec27
20211223 15:48:36.350 INFO grin_store::lmdb - Resized database from 1048576 to 134217728
20211223 15:48:36.395 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner:

Other Error: output vs rproof MMRs different sizes })': src/bin/cmd/server.rs:57   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300
   7: grin::cmd::server::start_server_tui
   8: grin::cmd::server::server_command
   9: grin::real_main
  10: grin::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259
      std::panicking::try::do_call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379
      std::panicking::try
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343
      std::panic::catch_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431
      std::rt::lang_start_internal
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51
  14: main
  15: __libc_start_main
  16: _start

```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

```
$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           94
Model name:                      Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
Stepping:                        3
CPU MHz:                         2711.996
BogoMIPS:                        5423.99
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX EPT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm 
                                 constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2ap
                                 ic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti tpr_shadow flexpriority fsgsb
                                 ase avx2 invpcid rdseed clflushopt md_clear flush_l1d

```

**Comment by phyro** [comment]
@gagarin55 are you syncing from the start or continuing sync on a new version?

**Comment by gagarin55** [comment]
> @gagarin55 are you syncing from the start or continuing sync on a new version?

I suppose I'm syncing from the start. With clean `~/.grin` folder

**Comment by phyro** [comment]
That's interesting. Did you just let it sync or have you ever shut down the node and continued syncing it later? I'm not sure what the issue is, I'm just trying to get a better understandig of how it could come to this scenario.

**Comment by gagarin55** [comment]
```
$ ./grin 
Illegal instruction (core dumped)
```

Any chance to use GRIN somehow ? :)))) I just want to receive and send this super-puper crypto

**Comment by phyro** [comment]
@gagarin55 sorry for that. Could you try https://github.com/mimblewimble/grin/releases/tag/v5.1.1 ? The v5.1.1 has a fix for some roaring_arch issue which might be related to what you're getting.

**Comment by gagarin55** [comment]
> @gagarin55 sorry for that. Could you try https://github.com/mimblewimble/grin/releases/tag/v5.1.1 ? The v5.1.1 has a fix for some roaring_arch issue which might be related to what you're getting.

It's reality works, thanks a lot!
