### ISSUE TITLE
[server] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"'

### ISSUE THREAD

**Issue by AsrielBelacqua** [mimblewimble/grin#375]
After a "failed to download block" panic:

```
stack backtrace:
   0:     0x56434fc3d3d3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hfc7985b08e763a82
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x56434fc393c4 - std::sys_common::backtrace::_print::h16a1db02a59ead63
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x56434fc40943 - std::panicking::default_hook::{{closure}}::h48ecee46f2eefc30
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x56434fc406b2 - std::panicking::default_hook::hb4c92ae8d005ca44
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x56434fc40e07 - std::panicking::rust_panic_with_hook::h25d461655d60b1a5
                               at /checkout/src/libstd/panicking.rs:611
   5:     0x56434fc40c64 - std::panicking::begin_panic::h0f6fdd9abfd7dfb9
                               at /checkout/src/libstd/panicking.rs:572
   6:     0x56434fc40bd9 - std::panicking::begin_panic_fmt::ha31e26b280c9e878
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x56434fc40b6a - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x56434fc79980 - core::panicking::panic_fmt::h67504914198d0451
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x56434e67da8c - core::result::unwrap_failed::h8c84e35c3e3080ec
                               at /checkout/src/libcore/macros.rs:41
  10:     0x56434e60b35b - <core::result::Result<T, E>>::unwrap::hf958d66f748cb37e
                               at /checkout/src/libcore/result.rs:772
  11:     0x56434e794a2f - grin_grin::sync::Syncer::block_received::h5dc16640ba4f06f3
                               at /home/stelmaria/src/grin/grin/src/sync.rs:232
  12:     0x56434e782548 - <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::NetAdapter>::block_received::he2b41549a2c86b34
                               at /home/stelmaria/src/grin/grin/src/adapters.rs:86
  13:     0x56434f1968d3 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::block_received::h7bbc13118d66e5f4
                               at /home/stelmaria/src/grin/p2p/src/peer.rs:229
  14:     0x56434f19959f - grin_p2p::protocol::handle_payload::hfffb81ff86d76348
                               at /home/stelmaria/src/grin/p2p/src/protocol.rs:188
  15:     0x56434f197384 - <grin_p2p::protocol::ProtocolV1 as grin_p2p::types::Protocol>::handle::{{closure}}::h1c9beef163e2de6c
                               at /home/stelmaria/src/grin/p2p/src/protocol.rs:55
  16:     0x56434f17da8a - <F as grin_p2p::conn::Handler>::handle::h45e9f1422c225cbd
                               at /home/stelmaria/src/grin/p2p/src/conn.rs:66
  17:     0x56434f183a54 - grin_p2p::conn::TimeoutConnection::listen::{{closure}}::h90f180716c890b9c
                               at /home/stelmaria/src/grin/p2p/src/conn.rs:275
  18:     0x56434f17dbea - <F as grin_p2p::conn::Handler>::handle::hca1de4a16edb4b46
                               at /home/stelmaria/src/grin/p2p/src/conn.rs:66
  19:     0x56434f180278 - grin_p2p::conn::Connection::read_msg::{{closure}}::{{closure}}::h2debf053ac765ebc
                               at /home/stelmaria/src/grin/p2p/src/conn.rs:215
  20:     0x56434f09e150 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}::{{closure}}::hc61700673fc12d54
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:34
  21:     0x56434f0d29a6 - <core::result::Result<T, E>>::map::he7947fd5de455f20
                               at /checkout/src/libcore/result.rs:468
  22:     0x56434f09bc7f - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}::h8a7a50090a98c9d2
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:33
  23:     0x56434f134e38 - <futures::future::chain::Chain<A, B, C>>::poll::h6d16a3551c558eeb
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:39
  24:     0x56434f09a8a3 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h4484e8a304e57c7a
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:32
  25:     0x56434f0a01a6 - <futures::stream::fold::Fold<S, F, Fut, T> as futures::future::Future>::poll::h10f9e4d9f1784378
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/stream/fold.rs:70
  26:     0x56434f143766 - <alloc::boxed::Box<F> as futures::future::Future>::poll::h4244867df949a9cf
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  27:     0x56434f16a77e - <futures::future::map::Map<A, F> as futures::future::Future>::poll::h0109825193a023f9
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  28:     0x56434f173896 - <futures::future::select::Select<A, B> as futures::future::Future>::poll::h6317b41766eb1e91
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/select.rs:48
  29:     0x56434f16d0ce - <futures::future::map::Map<A, F> as futures::future::Future>::poll::heaefcdf5256b99fc
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  30:     0x56434f17850a - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::hd630504771d3d30c
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  31:     0x56434f1742b8 - <futures::future::select::Select<A, B> as futures::future::Future>::poll::h98729bbdda9e64bf
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/select.rs:52
  32:     0x56434f16c53e - <futures::future::map::Map<A, F> as futures::future::Future>::poll::hb984bc7683d7ac58
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  33:     0x56434f177cea - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h850e5dd771e7befd
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  34:     0x56434f1438f6 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hcb48370ad9305651
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  35:     0x56434f1723c9 - <futures::future::select::Select<A, B> as futures::future::Future>::poll::h4100b8e97376d7d0
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/select.rs:48
  36:     0x56434f16bd9e - <futures::future::map::Map<A, F> as futures::future::Future>::poll::ha826b0fdefa33cf4
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  37:     0x56434f17785a - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h31e3dc1a1d88d4d3
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  38:     0x56434f1438f6 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hcb48370ad9305651
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  39:     0x56434f130a6e - <futures::future::chain::Chain<A, B, C>>::poll::h35bb930315fa0043
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:26
  40:     0x56434f17a4c3 - <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::hbf29063ec1bde875
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/then.rs:32
  41:     0x56434f1438f6 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hcb48370ad9305651
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  42:     0x56434f177ee9 - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h85d58f12f4d48ff3
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  43:     0x56434f48971f - <alloc::boxed::Box<F> as futures::future::Future>::poll::hf68a8a6d89b6a20a
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  44:     0x56434f46e7dc - <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::h4599681781169e7d
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  45:     0x56434f46ec5f - <futures::task_impl::Spawn<T>>::enter::{{closure}}::h1f359600cedb86b2
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  46:     0x56434f48b018 - futures::task_impl::std::set::hfdd56af9979d8d2a
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/std/mod.rs:78
  47:     0x56434f46ea5b - <futures::task_impl::Spawn<T>>::enter::h1f68ea1338268f70
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  48:     0x56434f46e7a4 - <futures::task_impl::Spawn<T>>::poll_future_notify::hd1d9be0c0f6641ad
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  49:     0x56434f496d9f - tokio_core::reactor::Core::dispatch_task::{{closure}}::h93f295274572e9a4
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:356
  50:     0x56434f46b342 - <scoped_tls::ScopedKey<T>>::set::hbee7f45922c69b98
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  51:     0x56434f4966b0 - tokio_core::reactor::Core::dispatch_task::h1b06f815bb4df586
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:355
  52:     0x56434f495975 - tokio_core::reactor::Core::dispatch::h222791201ee03fe9
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:316
  53:     0x56434f495470 - tokio_core::reactor::Core::poll::hb51e0366dfb3392f
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:304
  54:     0x56434e56d2a2 - tokio_core::reactor::Core::run::h7bef39177f07b91d
                               at /home/stelmaria/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:241
  55:     0x56434e788cff - grin_grin::server::Server::start::hf65bcf9cfa39d7c9
                               at /home/stelmaria/src/grin/grin/src/server.rs:77
  56:     0x56434e49066c - grin::server_command::hd95074537eb9b6cc
                               at /home/stelmaria/src/grin/src/bin/grin.rs:342
  57:     0x56434e48ef3a - grin::main::heb73893507a6a4c7
                               at /home/stelmaria/src/grin/src/bin/grin.rs:271
  58:     0x56434fc47eec - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  59:     0x56434fc4152b - std::rt::lang_start::hdcba96cc6d0f043d
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:61
  60:     0x56434e493862 - main
  61:     0x7fa1df35182f - __libc_start_main
  62:     0x56434e454898 - _start
  63:                0x0 - <unknown>
```

[grin-poisonerror.log](https://github.com/mimblewimble/grin/files/1497773/grin-poisonerror.log)

**Comment by AsrielBelacqua** [comment]
That log also contains a record of a curiously large block:
```
Nov 23 00:10:18.024 DEBG Processing block fc2692cf at 7401 with 128 inputs and 245 outputs.
```
Haven't seen one that large before on testnet1!

**Comment by AsrielBelacqua** [comment]
A similar instance of this:
[grin-poisonerror2.log.gz](https://github.com/mimblewimble/grin/files/1497847/grin-poisonerror2.log.gz)

**Comment by ignopeverell** [comment]
Should be fixed by @antiochp new sync. Also PoisonError is usually a consequence of a previous panic that wasn't properly handled.
