### ISSUE TITLE
The sender got the HTTP error of 500 from the wallet listener when sending.

### ISSUE THREAD

**Issue by heunglee** [mimblewimble/grin#422]
Wallet listener's env:
- milestone/testnet1
- Mac OS X El Capitan ver. 10.11.6 on wifi of cable modem/router.
- Wallet listener on port 13415. The port was forwarding in the router.
- server up and running on localhost and default port.

The sender initiated the transaction via IP:port and received the HTTP error of 500. Yet the receiver got grin currency sent as shown below.

Wallet Summary Info - Block Height: 166
--------------------------
 Total                            | 9.984000000 
 Awaiting Confirmation            | 9.984000000 
 Confirmed but Still Locked       | 0.000000000 
 Currently Spendable              | 0.000000000 
 ---------                        | --------- 
 (Locked by previous transaction) | 0.000000000 

The error traces on the listener was:
Dec 03 18:41:48.331 DEBG Received txn and built output - Identifier(7c29a5f37c5929cee102), Identifier(0ca6dfd370216e5a79bc), 2
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: Internal("Error processing partial transaction: Node(Internal(\"Server error.\"))")', src/libcore/result.rs:906:4
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
stack backtrace:
0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:69
2: std::panicking::default_hook::{{closure}}
at src/libstd/sys_common/backtrace.rs:58
at src/libstd/panicking.rs:381
3: std::panicking::default_hook
at src/libstd/panicking.rs:397
4: std::panicking::begin_panic
at src/libstd/panicking.rs:577
5: std::panicking::begin_panic
at src/libstd/panicking.rs:538
6: std::panicking::try::do_call
at src/libstd/panicking.rs:522
7: std::panicking::try::do_call
at src/libstd/panicking.rs:498
8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
at src/libcore/panicking.rs:71
9: core::result::unwrap_failed
at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:23
10: <core::result::Result<T, E>>::unwrap
at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:772
11: grin_wallet::receiver::receive_json_tx::{{closure}}
at wallet/src/receiver.rs:80
12: alloc::slice::<impl [T]>::to_vec
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
13: router::router::Router::handle_method
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:199
14: router::router::Router::handle_method::{{closure}}
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/router-0.5.1/src/router.rs:212
15: alloc::slice::<impl [T]>::to_vec
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/middleware/mod.rs:318
16: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/mount-0.3.0/src/mount.rs:122
17: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.5.1/src/iron.rs:176
18: <hyper::server::Worker<H>>::keep_alive_loop
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:337
19: <hyper::server::Worker<H>>::handle_connection
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:283
20: hyper::server::handle::{{closure}}
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/mod.rs:242
21: hyper::server::listener::spawn_with::{{closure}}
at /Users/checkpartyon/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.13/src/server/listener.rs:50

**Comment by heunglee** [comment]
This issue seemed caused by old mackbook pro (mid 2009). The server was not fully operational at the time when sending some coins due to some unknown incompatibility of hardware/os with grin build. That seemed cause HTTP 500 error on response of the unstable server. This issue is specific to mackbook pro late 2009. For that matter, macbook mid 2009 is not recommended.
