### ISSUE TITLE
DuplicateKernel when enabling mining at height 2922

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#548]
Cannot get a miner to startup successfully against the "valid chain" at height `2922`.

Getting a `DuplicateKernel` as the miner builds the next block - 

```
Dec 27 21:28:32.790 DEBG Starting new sumtree extension.
Dec 27 21:28:32.790 DEBG Error returned, discarding sumtree extension.
Dec 27 21:28:32.791 ERRO Error setting sumtree root to build a block: DuplicateKernel(Commitment(09ebb0d9d49d40f1c2baa3bd951f51881862cf5628d4137fdc
fc86d3128de30fdb))
thread 'miner' panicked at 'Box<Any>', grin/src/miner.rs:599:4
stack backtrace:
   0:     0x5598e4291393 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hfc7985b08e763a82
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5598e428d384 - std::sys_common::backtrace::_print::h16a1db02a59ead63
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x5598e4294903 - std::panicking::default_hook::{{closure}}::h48ecee46f2eefc30
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x5598e4294672 - std::panicking::default_hook::hb4c92ae8d005ca44
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x5598e4294dc7 - std::panicking::rust_panic_with_hook::h25d461655d60b1a5
                               at /checkout/src/libstd/panicking.rs:611
   5:     0x5598e3ccfbdc - std::panicking::begin_panic::h3b3fa4ecb4e5f821
   6:     0x5598e3d3b0d4 - grin_grin::miner::Miner::build_block::h56b3c9bde70468d7
   7:     0x5598e3d34190 - grin_grin::server::Server::start_miner::{{closure}}::h2a48f420241f2f20
   8:     0x5598e3cce4b5 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcc7fbb39dec9bd9e
   9:     0x5598e3ccfc75 - std::panicking::try::do_call::h759499821d6a93e7
  10:     0x5598e429beac - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  11:     0x5598e3cf4d32 - <F as alloc::boxed::FnBox<A>>::call_box::h3cd843130bc5ee04
  12:     0x5598e4293c6b - std::sys::imp::thread::Thread::new::thread_start::hf0e7be833820328e
                               at /checkout/src/liballoc/boxed.rs:692
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  13:     0x7fcc682c46b9 - start_thread
  14:     0x7fcc67de43dc - clone
  15:                0x0 - <unknown>
```

**Comment by antiochp** [comment]
Seems likely this is related to the 2 spent but still in UTXO set outputs I see when running to reconciliation script - 

```
--------------------
Inputs:  195
Outputs:  3157
*** Duplicate (sets) of inputs:  0
*** Duplicate (sets) of outputs:  0
*** Spent yet still in UTXO set:  2
*** Unspent but missing from UTXO set:  0
--------------------
```

I think I attempted a "zero confirmation spend" from one of the nodes at around the same time that this occurred.

**Comment by antiochp** [comment]
Got rid of wallet.dat and wallet.seed and ran wallet init to regenerate a new wallet.seed.
Mining is working fine now.
Keeping an eye on it for now and will test with some txs tomorrow once I have some unlocked grin.

**Comment by antiochp** [comment]
Closing this for now - will reopen and investigate further if it reoccurs.
