### ISSUE TITLE
Build failure on Alpine Linux

### ISSUE THREAD

**Issue by haarts** [mimblewimble/grin#549]
I'm trying to build the latest Grin on Alpine Linux. Mostly good until compiling Rocksdb:
```
--- stderr                                          
thread 'main' panicked at '                         

Internal error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-static" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "." "-std=c++11" "-Wno-unused-parameter" "-DNDEBUG=1" "-DSNAPPY=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-Wall" "-Wextra" "-o" "/root/grin/target/debug/build/librocksdb-sys-54e02bb42ffbb2c0/out/rocksdb/env/env_posix.o" "-c" "rocksdb/env/env_posix.cc" with args "c++" did not execute successfully (status code exit code: 1).                                                   

, /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:522
   7: gcc::fail
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670
   8: gcc::Build::compile
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:783
   9: build_script_build::build_rocksdb
             at ./build.rs:114
  10: build_script_build::main
             at ./build.rs:140
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:361
             at src/libstd/rt.rs:59
  13: main
  14: __libc_start_main

~/grin #


```

cargo 0.22.0
rustc 1.22.1
grin commit 521678bd2306902351bc41d81d34b47021aedc2b
g++ (Alpine 6.4.0) 6.4.0
cmake version 3.9.6
alpine 3.7.0

I'm not even sure where to start really.

**Comment by sesam** [comment]
Good catch. Can you install rocksdb from Alpine? On debian I had some rocksdb issue, likely not the same, but sudo apt-get install rocksdb fixed mine.

If that does nothing, look in source code around
````
 9: build_script_build::build_rocksdb
             at ./build.rs:114
  10: build_script_build::main
             at ./build.rs:140
````
and what the build.rs script is trying there

**Comment by haarts** [comment]
After some spelunking and digging into the build scripts I got:
```
rocksdb/env/env_posix.cc:13:22: fatal error: linux/fs.h: No such file or directory
 #include <linux/fs.h>
```
This error I got after running the compiler command by hand. 
This in turn led me to believe I was missing some silly kernel headers.
So after `apk add linux-headers` I was able to successfully compile! Thanks for the pointer!

**Comment by ignopeverell** [comment]
How to add a PR for a troubleshooting section in the building docs that includes this?

**Comment by haarts** [comment]
Allow me to write that section up!
