### ISSUE TITLE
travis failures on grin_grin

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#772]
Digging into a few recent travis failures on grin_grin crate and seeing the following in several failed builds in the _raw_ build logs (not immediately obvious in the online logs on travis) -

```
[31mFAILED(B[m

failures:

---- basic_wallet_transactions stdout ----
	Tx sent: 50.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Coinbase wallet info: WalletInfo { current_height: 15, total: 850000000000, amount_awaiting_confirmation: 0, amount_confirmed_but_locked: 180000000000, amount_currently_spendable: 670000000000, amount_locked: 0, data_confirmed: true, data_confirmed_from: "from server node" }
Recipient wallet info: WalletInfo { current_height: 15, total: 50000000000, amount_awaiting_confirmation: 0, amount_confirmed_but_locked: 0, amount_currently_spendable: 50000000000, amount_locked: 0, data_confirmed: true, data_confirmed_from: "from server node" }
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Tx not sent to http://127.0.0.1:20002: Error { inner: ErrorImpl { code: EofWhileParsingObject, line: 288, column: 504 }

stack backtrace:
   0:     0x562091534d14 - backtrace::backtrace::libunwind::trace::h7eb3cbdb845f901a
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h792ec9b0a2500d5f
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/mod.rs:42
   1:     0x56209152b8bc - backtrace::capture::Backtrace::new_unresolved::ha67d39c35d78aa11
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:88
   2:     0x562091529977 - failure::backtrace::internal::InternalBacktrace::new::h05579e94dfdfa679
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/internal.rs:44
   3:     0x56209152857e - failure::backtrace::Backtrace::new::h3af47222c7a66d94
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/mod.rs:98
   4:     0x56209082f1f3 - <failure::error::Error as core::convert::From<F>>::from::ha15f247a88c8f8ad
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/error.rs:34
   5:     0x5620909b3c24 - <T as core::convert::Into<U>>::into::hdab42759693bf7c4
                        at /checkout/src/libcore/convert.rs:415
   6:     0x5620908cd258 - <failure::context::Context<D>>::with_err::hf126c04c591bb9a2
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/context.rs:78
   7:     0x5620909b4ae9 - failure::Fail::context::h6f825cec0d2a53c0
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/lib.rs:127
   8:     0x56209086b74b - grin_wallet::types::WalletData::read_outputs::{{closure}}::h17e372d3b8da67fa
                        at wallet/src/types.rs:584
   9:     0x56209097a289 - <core::result::Result<T, E>>::map_err::hbcfb8e10d455d6b0
                        at /checkout/src/libcore/result.rs:500
  10:     0x5620907ee166 - grin_wallet::types::WalletData::read_outputs::h80ed4b99d62d384e
                        at wallet/src/types.rs:583
  11:     0x5620907ee24e - grin_wallet::types::WalletData::read::he38fcbf706d232a2
                        at wallet/src/types.rs:591
  12:     0x5620907edef5 - grin_wallet::types::WalletData::read_or_create::h00aaa1ab24fc1ded
                        at wallet/src/types.rs:570
  13:     0x562090860da4 - grin_wallet::types::WalletData::read_wallet::hc43aa0f5ff77ae2c
                        at wallet/src/types.rs:500
  14:     0x5620908bbf16 - grin_wallet::sender::build_send_tx::h633c4ccc4c38863c
                        at wallet/src/sender.rs:247
  15:     0x5620908bb620 - grin_wallet::sender::issue_send_tx::he5152c53608975f1
                        at wallet/src/sender.rs:52
  16:     0x56209061b5cd - wallet::framework::LocalServerContainer::send_amount_to::ha341659200d9f690
                        at grin/tests/framework/mod.rs:321
  17:     0x562090606766 - wallet::basic_wallet_transactions::hace76a7d41ecdf83
                        at grin/tests/wallet.rs:137
  18:     0x562090640461 - test::run_test::{{closure}}::hd17bd0dbea820acd
                        at /checkout/src/libtest/lib.rs:1449
                         - core::ops::function::FnOnce::call_once::h024d6f5d0e11a564
                        at /checkout/src/libcore/ops/function.rs:223
                         - <F as alloc::boxed::FnBox<A>>::call_box::h9e5aacf2cfbec32f
                        at /checkout/src/liballoc/boxed.rs:815
  19:     0x562091938afe - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  20:     0x56209064bc62 - std::panicking::try::h014b12cf9c6182d4
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind::hb5b8f79cac8d4289
                        at /checkout/src/libstd/panic.rs:365
                         - test::run_test::run_test_inner::{{closure}}::h456672a6e1855568
                        at /checkout/src/libtest/lib.rs:1400
                         - std::sys_common::backtrace::__rust_begin_short_backtrace::h6ea449afa5ecc4f7
                        at /checkout/src/libstd/sys_common/backtrace.rs:133
  21:     0x562090657bd2 - std::thread::Builder::spawn::{{closure}}::{{closure}}::he5f94e30313d120c
                        at /checkout/src/libstd/thread/mod.rs:406
                         - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he8df7e3424549b8f
                        at /checkout/src/libstd/panic.rs:300
                         - std::panicking::try::do_call::hfa0b0672df703a07
                        at /checkout/src/libstd/panicking.rs:480
  22:     0x562091938afe - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  23:     0x562090655c5d - std::panicking::try::h0b3525c2365df5ae
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind::h1b29113cbae772d9
                        at /checkout/src/libstd/panic.rs:365
                         - std::thread::Builder::spawn::{{closure}}::h3aa58fed0c253f3f
                        at /checkout/src/libstd/thread/mod.rs:405
                         - <F as alloc::boxed::FnBox<A>>::call_box::hb2bfcb2a0f4a5513
                        at /checkout/src/liballoc/boxed.rs:815
  24:     0x562091924897 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h45bad4268ff813ab
                        at /checkout/src/liballoc/boxed.rs:825
                         - std::sys_common::thread::start_thread::h97260957c81cf142
                        at /checkout/src/libstd/sys_common/thread.rs:24
  25:     0x5620919163f8 - std::sys::unix::thread::Thread::new::thread_start::h3838be2df5be642c
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  26:     0x7f02e7d3d183 - start_thread
  27:     0x7f02e7852ffc - clone
  28:                0x0 - <unknown>

Wallet data error: Error reading wallet file  }
Tx sent: 1.000000000 grin to http://127.0.0.1:20002 (strategy 'not_all')
Recipient wallet info post little sends: WalletInfo { current_height: 60, total: 59000000000, amount_awaiting_confirmation: 0, amount_confirmed_but_locked: 0, amount_currently_spendable: 59000000000, amount_locked: 0, data_confirmed: true, data_confirmed_from: "from server node" }
thread 'basic_wallet_transactions' panicked at 'assertion failed: recipient_info.data_confirmed &&
    recipient_info.amount_currently_spendable == 60000000000', grin/tests/wallet.rs:153:2
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: wallet::basic_wallet_transactions
             at grin/tests/wallet.rs:153
   7: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libtest/lib.rs:1449
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:815
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101


failures:
    basic_wallet_transactions

test result: [31mFAILED(B[m. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

[m[m[31m[1merror:[m test failed, to rerun pass '--test wallet'

```

**Comment by ignopeverell** [comment]
Tried locally a few times and couldn't reproduce it. Might be one of those Travis-only failures.
