### ISSUE TITLE
Wallet panic when trying to do info in wrong directory

### ISSUE THREAD

**Issue by quentinlesceller** [mimblewimble/grin#807]
Currently when we do ```grin wallet -p password info```, the wallet panic:
```
Mar 18 18:18:43.351 DEBG Using wallet seed file at: ./wallet.seed
Mar 18 18:18:43.352 ERRO wallet seed file ./wallet.seed could not be opened (grin wallet init). Run "grin wallet init" to initialize a new wallet.
Mar 18 18:18:43.774Thread 'main' panicked with message:
"Failed to read wallet seed file.: Error { inner: 

Wallet seed doesn't exist error }"
See grin.log for further details.
 ERRO thread 'main' panicked at 'Failed to read wallet seed file.: Error { inner: 

Wallet seed doesn't exist error }': /checkout/src/libcore/result.rs:916stack backtrace:
   0:     0x55763653a964 - backtrace::backtrace::libunwind::trace::hef4b129fd120e057
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h015c65c5cec514f2
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/mod.rs:42
   1:     0x5576365314cc - backtrace::capture::Backtrace::new_unresolved::h94e04f6ab52f7b92
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:88
   2:     0x55763653141e - backtrace::capture::Backtrace::new::h8fe61528dfe8a939
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:63
   3:     0x55763639990c - grin_util::logger::send_panic_to_log::{{closure}}::haf647e42a19087ce
                        at util/src/logger.rs:113
   4:     0x55763658a155 - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
                        at /checkout/src/libstd/panicking.rs:578
   5:     0x557636589f6e - std::panicking::begin_panic::h215af23ff6354aaf
                        at /checkout/src/libstd/panicking.rs:538
   6:     0x557636589eda - std::panicking::begin_panic_fmt::h752224a2c436be23
                        at /checkout/src/libstd/panicking.rs:522
   7:     0x557636589e72 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:498
   8:     0x5576365eb780 - core::panicking::panic_fmt::h68e7715928be641f
                        at /checkout/src/libcore/panicking.rs:71
   9:     0x557634e31527 - core::result::unwrap_failed::h7b2441baf80f7b49
                        at /checkout/src/libcore/macros.rs:23
  10:     0x557634e2bfd7 - <core::result::Result<T, E>>::expect::h7c82af90063dafe5
                        at /checkout/src/libcore/result.rs:809
  11:     0x557634e3b993 - grin::wallet_command::h3ffc5996d9051321
                        at src/bin/grin.rs:513
  12:     0x557634e38a90 - grin::main::h3fbafccde6da2156
                        at src/bin/grin.rs:312
  13:     0x557634eb64e1 - std::rt::lang_start::{{closure}}::h8b84a522bbc8892e
                        at /checkout/src/libstd/rt.rs:74
  14:     0x557636589dd7 - std::rt::lang_start_internal::{{closure}}::h6ddc513d95d559ac
                        at /checkout/src/libstd/rt.rs:59
                         - std::panicking::try::do_call::h7d33aea9be52481f
                        at /checkout/src/libstd/panicking.rs:480
  15:     0x5576365ad4ce - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  16:     0x5576365911b9 - std::panicking::try::h33108b08b6395be5
                        at /checkout/src/libstd/panicking.rs:459
                         - std::panic::catch_unwind::hb0149e8b5a4339ed
                        at /checkout/src/libstd/panic.rs:365
                         - std::rt::lang_start_internal::h16c0c37ef62d8e5a
                        at /checkout/src/libstd/rt.rs:58
  17:     0x557634eb64c1 - std::rt::lang_start::hbf27c0c2d0cc6e93
                        at /checkout/src/libstd/rt.rs:74
  18:     0x557634e3d19d - main
  19:     0x7f9057b262e0 - __libc_start_main
  20:     0x557634e23ae9 - _start
  21:                0x0 - <unknown>
```

Would be nice to handle this error.

**Comment by quentinlesceller** [comment]
Same for ```wallet send```command which crash with a panic when everything is not correctly written.

**Comment by quentinlesceller** [comment]
Closing this since the wallet crate is under heavy refactoring.
