### ISSUE TITLE
New node failing to sync

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin#912]
New node (basically my dev environment with .grin deleted each time) appears to halt and stop synching every time... and not consistently on the same block. Logs from a couple of runs, first time at 278 with mining enabled and second time at 410 with mining disabled:

[grin.log](https://github.com/mimblewimble/grin/files/1859842/grin.log)

[grin-stuck-1.log](https://github.com/mimblewimble/grin/files/1859843/grin-stuck-1.log)

**Comment by yeastplume** [comment]
Note stopping and restarting seems to get it moving again in each case, which is a good sign indicating something silly instead of some consensus issue

**Comment by tromp** [comment]
My last server run also got stuck, at height 2830. See the grin.log at https://github.com/tromp/tromp.github.io/blob/master/grin.log

It first gets 5235138d at 2831 while it's at height 2828.
Grepping for initial occurences of 5235138d:
```
Mar 29 12:56:08.135 DEBG handle_payload: CompactBlock: 5235138d
Mar 29 12:56:08.135 DEBG Received compact_block 5235138d at 2831 from 198.245.50.26:13414, going to process.
Mar 29 12:56:08.137 DEBG block: hydrate_from: 5235138d, 1 txs
Mar 29 12:56:19.024 DEBG handle_payload: CompactBlock: 5235138d
Mar 29 12:56:19.024 DEBG Received compact_block 5235138d at 2831 from 78.46.193.41:13414, going to process.
Mar 29 12:56:19.026 DEBG block: hydrate_from: 5235138d, 1 txs
Mar 29 12:56:19.053 DEBG handle_payload: CompactBlock: 5235138d
Mar 29 12:56:19.053 DEBG Received compact_block 5235138d at 2831 from 78.46.193.41:13414, going to process.
Mar 29 12:56:19.055 DEBG block: hydrate_from: 5235138d, 1 txs
Mar 29 12:56:35.448 DEBG Received block header 5235138d at 2831 from 139.59.105.169:13414, going to process.
Mar 29 12:56:35.448 DEBG pipe: process_block_header: 5235138d at 2831
Mar 29 12:56:35.448 DEBG Block header 5235138d refused by chain: Orphan
```

Why does it take 27 seconds to go from the first "going to process" to the actual processing?

Later it decides it needs this block after all:
```
Mar 29 12:57:32.389 DEBG Requesting block 5235138d from peer 195.201.95.62:13414.
Mar 29 12:57:32.389 DEBG Requesting block 5235138d from peer 109.74.202.16:13414.
Mar 29 12:57:32.389 DEBG Requesting block 5235138d from peer 139.59.105.169:13414.
```
But why not use the one it already received? When refusing blocks that are just a few steps ahead of you as Orphans, it would be wise to keep them around for when you catch up.

It then runs into many panics:
```
thread 'peer' panicked at 'index 286336 out of range for slice of length 286240': src/libcore/slice/mod.rs:745stack backtrace:
thread 'peer' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': src/libcore/result.rs:906stack backtrace:
```

which seem to prevent it from processing block 5235138d.

**Comment by yeastplume** [comment]
Block 279 received earlier here, then orphaned
```
Mar 29 12:08:56.691 DEBG Received block 5f651b72 at 279 from 37.59.44.69:13414, going to process.
Mar 29 12:08:56.691 DEBG pipe: process_block 5f651b72 at 279 with 0 inputs, 1 outputs, 1 kernels
Mar 29 12:08:56.692 DEBG process_block: orphan: 19c48249, # orphans 143
Mar 29 12:08:56.692 DEBG Received block 10fc8411 at 251 from 51.15.219.12:13414, going to process.
```
Then 278 processed here, then nothing... it does seem possible it's gotten rid of some orphans at that point and isn't requesting them again
```
Mar 29 12:09:27.969 INFO Added 511 headers to the header chain. Last: 34dc8738 at 1084.
Mar 29 12:09:27.971 DEBG Received block 6f63afdd at 278 from 192.241.160.172:13414, going to process.
Mar 29 12:09:27.971 DEBG pipe: process_block 6f63afdd at 278 with 0 inputs, 1 outputs, 1 kernels
Mar 29 12:09:27.991 DEBG pipe: chain head reached 278 @ 12537 [6f63afdd]
Mar 29 12:09:27.991 DEBG Committing txhashset extension. sizes (552, 552, 552)
Mar 29 12:09:28.093 DEBG ping/pong: 104.236.150.29:13414: 17121 @ 2847 vs us: 12536 @ 277
Mar 29 12:09:28.095 DEBG Received tx 90a13779 from ?.?.?.?, going to process.
Mar 29 12:09:28.127 DEBG Transaction 90a13779 rejected: ImmatureTransaction { lock_height: 2847 }
Mar 29 12:09:28.129 DEBG locate_headers: [6b1ea671, 745a3714, 118293c8, 4df56e28, 3f7d042d, 1cfcc6fc, 636dc170, 43f5a05f, 65785e53, 7b7bd403, 1b81cd90, 3346f63c]
Mar 29 12:09:28.129 DEBG locate_headers: common header: 3346f63c
Mar 29 12:09:28.134 DEBG Received block 50041130 at 291 from 192.241.160.172:13414, going to process.
Mar 29 12:09:28.134 DEBG pipe: process_block 50041130 at 291 with 0 inputs, 1 outputs, 1 kernels
Mar 29 12:09:28.140 DEBG process_block: orphan: 50041130, # orphans 119

```

**Comment by yeastplume** [comment]
```
const MAX_ORPHAN_AGE_SECS: u64 = 30;
```
Looks like we've come up exactly against that limit in this case...

**Comment by yeastplume** [comment]
Well, even if I change that to 300 seconds, it still keeps getting stuck.

**Comment by v05** [comment]
Upon initial sync I had to force quit and restart grin (Q didn't work) every 200 blocks.  Once it was synced, it seemed to self-update, but lagged behind significantly and then updated to current height in one jump.

When it failed to sync, logs were full of ping pongs, and some rejected orphan chat, but no warnings or errors.

Perhaps unrelated, but the miner will often get stuck pretty far behind the current block.

**Comment by yeastplume** [comment]
Stuck on 313.. this is 313 and 314 in the header chain:
```
Mar 29 18:39:48.434 DEBG pipe: sync_block_header: 1cdeb157 at 313
Mar 29 18:39:48.437 DEBG header head 12572 @ 313 [1cdeb157]
Mar 29 18:39:48.437 DEBG sync head 12572 @ 313 [1cdeb157]
Mar 29 18:39:48.438 DEBG pipe: sync_block_header: 08226b3a at 314
Mar 29 18:39:48.441 DEBG header head 12573 @ 314 [08226b3a]
```
314 request:
```
Mar 29 18:40:11.884 DEBG Requesting block 08226b3a from peer 144.76.60.11:13414.
```
314 received, orphaned
```
Mar 29 18:40:12.003 DEBG Received block 08226b3a at 314 from 144.76.60.11:13414, going to process.
Mar 29 18:40:12.003 DEBG pipe: process_block 08226b3a at 314 with 0 inputs, 1 outputs, 1 kernels
Mar 29 18:40:12.004 DEBG Received block 437b1602 at 281 from 37.205.10.52:13414, going to process.
Mar 29 18:40:12.004 DEBG pipe: process_block 437b1602 at 281 with 0 inputs, 1 outputs, 1 kernels
Mar 29 18:40:12.011 DEBG Received block 33456b32 at 240 from 138.197.172.101:13414, going to process.
Mar 29 18:40:12.011 DEBG pipe: process_block 33456b32 at 240 with 0 inputs, 1 outputs, 1 kernels
Mar 29 18:40:12.012 DEBG process_block: orphan: 08226b3a, # orphans 156
Mar 29 18:40:12.012 DEBG process_block: orphan: 437b1602, # orphans 157
```
313 received, orphaned:
```
Mar 29 18:40:12.281 DEBG Received block 1cdeb157 at 313 from 192.241.160.172:13414, going to process.
Mar 29 18:40:12.281 DEBG Committing txhashset extension. sizes (240, 240, 240)
Mar 29 18:40:12.281 DEBG pipe: process_block 1cdeb157 at 313 with 0 inputs, 1 outputs, 1 kernels
Mar 29 18:40:12.283 DEBG Received block 289ef955 at 270 from 24.7.36.144:13414, going to process.
Mar 29 18:40:12.283 DEBG pipe: process_block 289ef955 at 270 with 0 inputs, 1 outputs, 1 kernels
Mar 29 18:40:12.285 DEBG process_block: orphan: 1cdeb157, # orphans 184
```
313 processed and added to chain (more than 30 seconds after 314 received and Orphaned):
```
Mar 29 18:40:42.216 DEBG pipe: process_block 1cdeb157 at 313 with 0 inputs, 1 outputs, 1 kernels
Mar 29 18:40:42.241 DEBG pipe: chain head reached 313 @ 12572 [1cdeb157]
```
.
.
.
Crickets chirping re: block 314 in the rest of the log

[grin.log](https://github.com/mimblewimble/grin/files/1861287/grin.log)
