### ISSUE TITLE
thread 'peer' panicked at 'chain validation failed, hard stop: InvalidRoot': /checkout/src/libcore/result.rs:916

### ISSUE THREAD

**Issue by chri2** [mimblewimble/grin#918]
This is Grin version 0.2.0 (git testnet2-24-g3e3fe6c), built for x86_64-unknown-linux-gnu by rustc 1.24.1 (d3ae9a9e0 2018-02-27).

```Mar 30 12:58:07.916 ERRO 
thread 'peer' panicked at 'chain validation failed, hard stop: InvalidRoot': /checkout/src/libcore/result.rs:916stack backtrace:
   0:     0x55e1d43a3a74 - backtrace::backtrace::libunwind::trace::h317bdd130bb41593
                        at /home/grin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h74d3c7bcfacaa15f
                        at /home/grin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/mod.rs:42
   1:     0x55e1d439a5dc - backtrace::capture::Backtrace::new_unresolved::h91cbd3ded83b7d22
                        at /home/grin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:88
   2:     0x55e1d439a52e - backtrace::capture::Backtrace::new::hfde7246ce693b5cd
                        at /home/grin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:63
   3:     0x55e1d4204eac - grin_util::logger::send_panic_to_log::{{closure}}::hfab9cbd6394b7ffb
                        at util/src/logger.rs:120
   4:     0x55e1d43f3255 - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
                        at /checkout/src/libstd/panicking.rs:578
   5:     0x55e1d43f306e - std::panicking::begin_panic::h215af23ff6354aaf
                        at /checkout/src/libstd/panicking.rs:538
   6:     0x55e1d43f2fda - std::panicking::begin_panic_fmt::h752224a2c436be23
                        at /checkout/src/libstd/panicking.rs:522
   7:     0x55e1d43f2f72 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:498
   8:     0x55e1d4454880 - core::panicking::panic_fmt::h68e7715928be641f
                        at /checkout/src/libcore/panicking.rs:71
   9:     0x55e1d3127567 - core::result::unwrap_failed::h24179517147f24a9
                        at /checkout/src/libcore/macros.rs:23
  10:     0x55e1d3120f79 - <core::result::Result<T, E>>::expect::h13d6c4cfe02db817
                        at /checkout/src/libcore/result.rs:809
  11:     0x55e1d3155ef3 - grin_grin::adapters::NetToChainAdapter::validate_chain::h675fd8028d432a6d
                        at grin/src/adapters.rs:450
  12:     0x55e1d3155335 - grin_grin::adapters::NetToChainAdapter::process_block::h2054440c8e35348d
                        at grin/src/adapters.rs:398
  13:     0x55e1d315058e - <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::h77b5b6a0b55ce903
                        at grin/src/adapters.rs:115
  14:     0x55e1d3931dcb - <grin_p2p::peers::Peers as grin_p2p::types::ChainAdapter>::compact_block_received::h2bad93ef7eb887ad
                        at p2p/src/peers.rs:528
  15:     0x55e1d391a468 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::ChainAdapter>::compact_block_received::h88f599f0ef59c213
                        at p2p/src/peer.rs:391
  16:     0x55e1d393d9d8 - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::h0d3e6d417ff5a97d
                        at p2p/src/protocol.rs:145
  17:     0x55e1d3966ffb - grin_p2p::conn::poll::{{closure}}::h16220f479199709e
                        at p2p/src/conn.rs:215
  18:     0x55e1d39c0de5 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc226948d939086a7
                        at /checkout/src/libstd/sys_common/backtrace.rs:133
  19:     0x55e1d3953b49 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h4c18a9f46418eb7d
                        at /checkout/src/libstd/thread/mod.rs:406
  20:     0x55e1d39a6f65 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h14db1057ac292549
                        at /checkout/src/libstd/panic.rs:300
  21:     0x55e1d397ca61 - std::panicking::try::do_call::h805ad24ef3d1cf1d
                        at /checkout/src/libstd/panicking.rs:480
  22:     0x55e1d44165ce - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  23:     0x55e1d397c85c - std::panicking::try::h17d6f658e81eb343
                        at /checkout/src/libstd/panicking.rs:459
  24:     0x55e1d39a6fda - std::panic::catch_unwind::hc2f400e02a6f3b76
                        at /checkout/src/libstd/panic.rs:365
  25:     0x55e1d3953743 - std::thread::Builder::spawn::{{closure}}::h392b96c564147107
                        at /checkout/src/libstd/thread/mod.rs:405
  26:     0x55e1d3953bf6 - <F as alloc::boxed::FnBox<A>>::call_box::hda52c1e6ba4eaa9d
                        at /checkout/src/liballoc/boxed.rs:815
  27:     0x55e1d44028a7 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h45bad4268ff813ab
                        at /checkout/src/liballoc/boxed.rs:825
                         - std::sys_common::thread::start_thread::h97260957c81cf142
                        at /checkout/src/libstd/sys_common/thread.rs:24
  28:     0x55e1d43f37c8 - std::sys::unix::thread::Thread::new::thread_start::h3838be2df5be642c
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  29:     0x7f98c587c063 - start_thread
  30:     0x7f98c539b62c - clone
  31:                0x0 - <unknown>
```

**Comment by chri2** [comment]
Couldn't reproduce, yet, using testnet2-30-gc393910
