### ISSUE TITLE
thread 'unnamed' panicked at 'slog::Fuse Drain

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#946]
Seeins the following panic when killing grin.
```
Apr 08 21:13:59.420 INFO This is Grin version 0.2.0 (git testnet2-48-g65d5bd4), built for armv7-unknown-linux-gnueabihf by rustc 1.25.0 (84203cac6 2018-03-25).
```
```
Apr 08 21:25:17.137 INFO Added 0 headers to the header chain. Last: 2168dfd4 at 82.
Apr 08 21:25:17.385 ERRO 
thread 'unnamed' panicked at 'slog::Fuse Drain: Os { code: 5, kind: Other, message: "Input/output error" }': /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.1.1/src/lib.rs:1695stack backtrace:
   0:   0xc74753 - backtrace::backtrace::trace::h494c2df7607e90db
   1:   0xc72f7f - backtrace::capture::Backtrace::new::h16501fd748ae292c
   2:   0xbfb01b - grin_util::logger::send_panic_to_log::{{closure}}::h07333b9eb265bcf1
   3:   0xd2e1df - std::panicking::rust_panic_with_hook::h2207195920ffa55f
                at libstd/panicking.rs:577
   4:   0xd2e04f - std::panicking::begin_panic::h8d43a09cf6d6e5f1
                at libstd/panicking.rs:537
   5:   0xd2dfd3 - std::panicking::begin_panic_fmt::hd9afc94159ee9735
                at libstd/panicking.rs:521
   6:   0xc0c51f - <slog::Fuse<D> as slog::Drain>::log::{{closure}}::h12e3fb83b042a32e
   7:   0xc07ff7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h80e518d983897776
   8:   0xbfcbff - std::panicking::try::do_call::hdb7ac8faa7b372a1
   9:   0xd387db - __rust_maybe_catch_panic
                at libpanic_unwind/lib.rs:102
  10:   0xbf97a7 - <F as alloc::boxed::FnBox<A>>::call_box::he0a0d3d346fc882a
  11:   0xd326ef - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::he8e6448e04c9339f
                at /checkout/src/liballoc/boxed.rs:798
                 - std::sys_common::thread::start_thread::h00c534d6c8768985
                at libstd/sys_common/thread.rs:24
                 - std::sys::unix::thread::Thread::new::thread_start::hb1d1727b173caaf8
                at libstd/sys/unix/thread.rs:90
```

**Comment by yeastplume** [comment]
Has this been seen recently?

**Comment by kargakis** [comment]
This may be fixed by graceful shutdown, maybe not

Once I get to retry this on ARM and reproduce, I will reopen this issue.

**Comment by kargakis** [comment]
Saw this again on an odroid c2 
```
Sep 19 19:43:07.265 ERRO 
thread 'unnamed' panicked at 'slog::Fuse Drain: Os { code: 5, kind: Other, message: "Input/output error" }': /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.3.3/src/lib.rs:1904stack backtrace:
   0:       0x556aa3e72f - backtrace::backtrace::trace::h6a88c4d04d9d9766
   1:       0x556aa3e51b - <backtrace::capture::Backtrace as core::default::Default>::default::h0dd8b7d51162928b
   2:       0x556a9e203b - grin_util::logger::send_panic_to_log::{{closure}}::hf0414f6dcd0d6c2a
   3:       0x556ab264c7 - std::panicking::rust_panic_with_hook::h22b0068fbbf8b0b4
                        at libstd/panicking.rs:479
   4:       0x556ab2611b - std::panicking::continue_panic_fmt::h015fb5b89d43591d
                        at libstd/panicking.rs:390
   5:       0x556ab2607f - std::panicking::begin_panic_fmt::h622f2d96d14cb1fb
                        at libstd/panicking.rs:345
   6:       0x556a9edb03 - <slog::Fuse<D> as slog::Drain>::log::{{closure}}::h785e0a23c06052d9
   7:       0x556a9edf03 - <slog::Fuse<D> as slog::Drain>::log::{{closure}}::hd308ff25554a79e7
   8:       0x556a9dbfe3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h341500eea1224fa5
   9:       0x556a9dc72f - std::panicking::try::do_call::h9d7d7b9633e90581
  10:       0x556ab43b3b - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  11:       0x556a9e41d3 - <F as alloc::boxed::FnBox<A>>::call_box::h79b05a927f7c5639
  12:       0x556ab269ab - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hc817d849f98aebf6
                        at /checkout/src/liballoc/boxed.rs:652
                         - std::sys_common::thread::start_thread::h834abd292559e1ce
                        at libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::h138f645bf45a5122
                        at libstd/sys/unix/thread.rs:90
  13:       0x7f9939809f - start_thread
```

**Comment by hashmap** [comment]
We don't use `slog` anymore, closing for now, feel free to reopen
