### ISSUE TITLE
thread 'unnamed' panicked at 'failed printing to stderr'

### ISSUE THREAD

**Issue by kargakis** [mimblewimble/grin#948]
Seeins the following panic when killing grin.
```
Apr 08 21:34:05.287 INFO This is Grin version 0.2.0 (git testnet2-48-g65d5bd4), built for armv7-unknown-linux-gnueabihf by rustc 1.25.0 (84203cac6 2018-03-25).
```
```
Apr 08 21:36:40.018 ERRO 
thread 'unnamed' panicked at 'failed printing to stderr: Input/output error (os error 5)': libstd/io/stdio.rs:690stack backtrace:
   0:   0xc85753 - backtrace::backtrace::trace::h494c2df7607e90db
   1:   0xc83f7f - backtrace::capture::Backtrace::new::h16501fd748ae292c
   2:   0xc0c01b - grin_util::logger::send_panic_to_log::{{closure}}::h07333b9eb265bcf1
   3:   0xd3f1df - std::panicking::rust_panic_with_hook::h2207195920ffa55f
                at libstd/panicking.rs:577
   4:   0xd3f04f - std::panicking::begin_panic::h8d43a09cf6d6e5f1
                at libstd/panicking.rs:537
   5:   0xd3efd3 - std::panicking::begin_panic_fmt::hd9afc94159ee9735
                at libstd/panicking.rs:521
   6:   0xd3273b - std::io::stdio::print_to::h85f2555763268c2c
                at libstd/io/stdio.rs:690
                 - std::io::stdio::_eprint::hda469f68c705873b
                at libstd/io/stdio.rs:708
   7:   0xc0c447 - grin_util::logger::send_panic_to_log::{{closure}}::h07333b9eb265bcf1
   8:   0xd3f1df - std::panicking::rust_panic_with_hook::h2207195920ffa55f
                at libstd/panicking.rs:577
   9:   0xd3f04f - std::panicking::begin_panic::h8d43a09cf6d6e5f1
                at libstd/panicking.rs:537
  10:   0xd3efd3 - std::panicking::begin_panic_fmt::hd9afc94159ee9735
                at libstd/panicking.rs:521
  11:   0xc1d51f - <slog::Fuse<D> as slog::Drain>::log::{{closure}}::h12e3fb83b042a32e
  12:   0xc18ff7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h80e518d983897776
  13:   0xc0dbff - std::panicking::try::do_call::hdb7ac8faa7b372a1
  14:   0xd497db - __rust_maybe_catch_panic
                at libpanic_unwind/lib.rs:102
  15:   0xc0a7a7 - <F as alloc::boxed::FnBox<A>>::call_box::he0a0d3d346fc882a
  16:   0xd436ef - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::he8e6448e04c9339f
                at /checkout/src/liballoc/boxed.rs:798
                 - std::sys_common::thread::start_thread::h00c534d6c8768985
                at libstd/sys_common/thread.rs:24
                 - std::sys::unix::thread::Thread::new::thread_start::hb1d1727b173caaf8
                at libstd/sys/unix/thread.rs:90
```

**Comment by yeastplume** [comment]
Shutdown is a bit more graceful now, so this is probably addressed, please reopen if you see it again
